import type { Language } from "../lib/i18n";

export type StatementCategory = "innocent" | "adult" | "gross";

export type StatementEntry = {
  id: string;
  category: StatementCategory;
  en: string;
  sv: string;
};

export const STATEMENT_CATEGORIES: StatementCategory[] = ["innocent", "adult", "gross"];

export const STATEMENTS: StatementEntry[] = [
{ id: "innocent_alarm_snooze", category: "innocent", en: "When you snooze the alarm one too many times", sv: "När du snoozar alarmet en gång för mycket" },
{ id: "innocent_wifi_not_working", category: "innocent", en: "When the WiFi suddenly stops working", sv: "När WiFi plötsligt slutar fungera" },
{ id: "innocent_typo_send", category: "innocent", en: "When you send the message with a typo", sv: "När du skickar meddelandet med ett stavfel" },
{ id: "innocent_meeting_that_could_email", category: "innocent", en: "When the meeting could have been an email", sv: "När mötet kunde varit ett mejl" },
{ id: "innocent_low_battery_outside", category: "innocent", en: "When your phone battery is at 2% and you're not home", sv: "När mobilen är på 2% och du inte är hemma" },
{ id: "innocent_password_wrong_again", category: "innocent", en: "When your password is wrong again", sv: "När lösenordet är fel igen" },
{ id: "innocent_skip_intro_auto", category: "innocent", en: "When Netflix skips the intro automatically", sv: "När Netflix skippar introt automatiskt" },
{ id: "innocent_food_arrives", category: "innocent", en: "When the food finally arrives", sv: "När maten äntligen kommer" },
{ id: "innocent_package_delivery", category: "innocent", en: "When you get a notification that your package has arrived", sv: "När du får notis om att paketet har kommit" },
{ id: "innocent_teacher_calls_name", category: "innocent", en: "When the teacher says your name", sv: "När läraren säger ditt namn" },
{ id: "innocent_group_project", category: "innocent", en: "When nobody in the group project answers", sv: "När ingen i grupparbetet svarar" },
{ id: "innocent_food_too_hot", category: "innocent", en: "When the food is way too hot but you try anyway", sv: "När maten är alldeles för varm men du försöker ändå" },
{ id: "innocent_typing_fast_delete", category: "innocent", en: "When you type a long message and delete it", sv: "När du skriver ett långt meddelande och raderar det" },
{ id: "innocent_outfit_mirror_check", category: "innocent", en: "When you check your outfit one more time", sv: "När du kollar din outfit en gång till" },
{ id: "innocent_snack_disappears", category: "innocent", en: "When the snack disappears faster than expected", sv: "När snacksen försvinner snabbare än väntat" },
{ id: "innocent_friend_running_late", category: "innocent", en: "When your friend says they're 5 minutes away", sv: "När din kompis säger att de är 5 minuter bort" },
{ id: "innocent_movie_plot_twist", category: "innocent", en: "When the movie plot twist hits", sv: "När filmens oväntade vändning kommer" },
{ id: "innocent_spot_taken", category: "innocent", en: "When someone takes your usual seat", sv: "När någon tar din vanliga plats" },
{ id: "innocent_music_hits_right", category: "innocent", en: "When the song hits exactly right", sv: "När låten sitter helt perfekt" },
{ id: "innocent_late_night_snack", category: "innocent", en: "When you go for a late night snack", sv: "När du smyger ut i köket för ett nattmål" },
{ id: "innocent_alarm_weekend", category: "innocent", en: "When you wake up early on a weekend for no reason", sv: "När du vaknar tidigt på helgen utan anledning" },
{ id: "innocent_new_episode_available", category: "innocent", en: "When a new episode is available", sv: "När ett nytt avsnitt finns tillgängligt" },
{ id: "innocent_ice_cream_falls", category: "innocent", en: "When the ice cream falls on the ground", sv: "När glassen faller i marken" },
{ id: "innocent_someone_says_free_food", category: "innocent", en: "When someone says there's free food", sv: "När någon säger att det finns gratis mat" },

{ id: "adult_cant_walk_normal", category: "adult", en: "When walking normally suddenly becomes difficult", sv: "När det plötsligt blir svårt att gå normalt" },
{ id: "adult_bite_mark_problem", category: "adult", en: "When the bite mark is way too visible", sv: "När bitmärket är alldeles för synligt" },
{ id: "adult_neighbors_heard_everything", category: "adult", en: "When you realize the neighbors definitely heard everything", sv: "När du inser att grannarna definitivt hörde allt" },
{ id: "adult_clothes_everywhere", category: "adult", en: "When you notice your clothes are spread across the entire room", sv: "När du inser att dina kläder ligger över hela rummet" },
{ id: "adult_that_escalated_fast", category: "adult", en: "When 'just one drink' escalates very quickly", sv: "När 'bara en drink' eskalerar väldigt snabbt" },
{ id: "adult_text_i_shouldnt_send", category: "adult", en: "When you type a message you definitely shouldn't send", sv: "När du skriver ett meddelande du absolut inte borde skicka" },
{ id: "adult_awkward_morning_exit", category: "adult", en: "When the morning exit feels extremely awkward", sv: "När det känns extremt pinsamt att smita iväg på morgonen" },
{ id: "adult_roommate_knows", category: "adult", en: "When your roommate knows exactly what happened", sv: "När din rumskompis vet exakt vad som hände" },
{ id: "adult_hard_to_focus", category: "adult", en: "When it's suddenly very hard to focus on the conversation", sv: "När det plötsligt blir väldigt svårt att fokusera på konversationen" },
{ id: "adult_one_thing_leads_to_another", category: "adult", en: "When one thing clearly leads to another", sv: "När en sak helt klart leder till en annan" },
{ id: "adult_unexpected_confidence", category: "adult", en: "When the confidence suddenly goes way up", sv: "När självförtroendet plötsligt skjuter i höjden" },
{ id: "adult_everyone_notices_tension", category: "adult", en: "When everyone in the room notices the tension", sv: "När alla i rummet märker spänningen" },
{ id: "adult_message_sent_heart_race", category: "adult", en: "When you send the message and your heart starts racing", sv: "När du skickar meddelandet och hjärtat börjar rusa" },
{ id: "adult_accidental_noise", category: "adult", en: "When you accidentally make way too much noise", sv: "När du råkar låta alldeles för mycket" },
{ id: "adult_caught_smiling_phone", category: "adult", en: "When someone notices you smiling at your phone", sv: "När någon märker att du ler mot mobilen" },
{ id: "adult_chemistry_obvious", category: "adult", en: "When the chemistry is obvious to everyone", sv: "När kemin är uppenbar för alla" },
{ id: "adult_cant_stop_thinking", category: "adult", en: "When you can't stop thinking about what just happened", sv: "När du inte kan sluta tänka på vad som just hände" },
{ id: "adult_wrong_time_flashback", category: "adult", en: "When a memory pops up at the worst possible time", sv: "När ett minne dyker upp vid absolut fel tillfälle" },
{ id: "adult_friend_asks_details", category: "adult", en: "When your friend immediately asks for details", sv: "När din kompis direkt frågar efter detaljer" },
{ id: "adult_situation_gets_heated", category: "adult", en: "When the situation gets very heated very fast", sv: "När situationen blir väldigt het väldigt snabbt" },
{ id: "adult_eye_contact_says_everything", category: "adult", en: "When the eye contact says everything", sv: "När ögonkontakten säger allt" },
{ id: "adult_too_close_personal_space", category: "adult", en: "When personal space suddenly disappears", sv: "När det personliga utrymmet plötsligt försvinner" },
{ id: "adult_cant_concentrate_anymore", category: "adult", en: "When concentrating is no longer possible", sv: "När koncentration inte längre är möjligt" },
{ id: "adult_tension_could_cut", category: "adult", en: "When the tension could be cut with a knife", sv: "När spänningen går att skära med kniv" },

  { id: "gross_mystery_smell", category: "gross", en: "When you open the gym bag you forgot in the car all summer", sv: "När du öppnar gymväskan som legat bortglömd i bilen hela sommaren" },
  { id: "gross_friend_in_background_of_leak", category: "gross", en: "When you spot your friend picking their nose in the background of a group photo", sv: "När du ser din kompis peta näsan i bakgrunden på en gruppbild" },
  { id: "gross_friend_defending_weird_opinion", category: "gross", en: "When your friend is aggressively defending a very weird opinion", sv: "När din kompis aggressivt försvarar en väldigt konstig åsikt" },


  { id: "gross_public_toilet", category: "gross", en: "When you open a public toilet stall and instantly regret it", sv: "När du öppnar ett bås på en offentlig toalett och ångrar det direkt" },
  { id: "gross_leftover_fridge", category: "gross", en: "When you find leftovers in the fridge from a time you can't remember", sv: "När du hittar rester i kylskåpet från en tid du inte minns" },
  { id: "gross_stepped_something", category: "gross", en: "When you step on something wet while wearing socks", sv: "När du trampar i något blött med strumpor på" },
  { id: "gross_hair_drain", category: "gross", en: "When the shower drain starts fighting back", sv: "När duschbrunnen börjar slå tillbaka" },
  { id: "gross_microwave_explosion", category: "gross", en: "When the microwave meal explodes and paints the inside", sv: "När mikromaten exploderar och målar hela insidan" },
  { id: "gross_random_sticky", category: "gross", en: "When you touch a sticky surface and don't know why it's sticky", sv: "När du rör vid något kladdigt och inte vet varför det är kladdigt" },
  { id: "gross_gym_shoe", category: "gross", en: "When someone takes off their shoes after the gym", sv: "När någon tar av sig skorna efter gymmet" },
  { id: "gross_sink_surprise", category: "gross", en: "When the sink spits yesterday's mystery back at you", sv: "När vasken spottar tillbaka gårdagens mysterium på dig" },
  { id: "gross_cough_near_food", category: "gross", en: "When someone coughs way too close to the food", sv: "När någon hostar alldeles för nära maten" },
  { id: "gross_bin_leak", category: "gross", en: "When the trash bag leaks on the floor", sv: "När soppåsen läcker ut på golvet" },

  // --- Innocent (expansion) ---
  { id: "innocent_monday_morning", category: "innocent", en: "The photo that best describes your Monday morning", sv: "Bilden som bäst beskriver din måndagsmorgon" },
  { id: "innocent_last_screenshot", category: "innocent", en: "The last screenshot you took – no explanations allowed", sv: "Den senaste skärmdumpen du tog – inga förklaringar" },
  { id: "innocent_last_cinnamon_bun", category: "innocent", en: "Your face when someone ate the last cinnamon bun", sv: "Din min när någon har ätit upp den sista kanelbullen" },
  { id: "innocent_weekend_reality", category: "innocent", en: "What your weekend actually looked like", sv: "Hur din helg faktiskt såg ut" },
  { id: "innocent_real_boss_at_home", category: "innocent", en: "The real boss of your household", sv: "Den som egentligen bestämmer hemma hos dig" },
  { id: "innocent_too_proud_meal", category: "innocent", en: "A meal you're way too proud of", sv: "Mat du är alldeles för stolt över" },
  { id: "innocent_group_chat_energy", category: "innocent", en: "The energy your group chat brings", sv: "Stämningen i er gruppchatt" },
  { id: "innocent_ikea_just_candles", category: "innocent", en: "This is me walking into IKEA 'just to buy tealights'", sv: "Det här är jag när jag går in på IKEA 'bara för att köpa värmeljus'" },
  { id: "innocent_first_vacation_day", category: "innocent", en: "The feeling on the first day of vacation", sv: "Känslan första semesterdagen" },
  { id: "innocent_camera_off_meeting", category: "innocent", en: "What you look like when your camera is off in a video meeting", sv: "Så ser du ut när kameran är avstängd på videomötet" },
  { id: "innocent_sunday_evening_feeling", category: "innocent", en: "What Sunday evening feels like", sv: "Hur söndagskvällen känns" },
  { id: "innocent_week_before_payday", category: "innocent", en: "Your bank account the week before payday", sv: "Ditt bankkonto veckan innan lön" },
  { id: "innocent_payday_feeling", category: "innocent", en: "The feeling when your salary hits your account", sv: "Känslan när lönen har kommit in" },
  { id: "innocent_healthy_for_one_day", category: "innocent", en: "You after trying to eat healthy for one whole day", sv: "Du efter att ha försökt äta nyttigt en hel dag" },
  { id: "innocent_hairdresser_asks", category: "innocent", en: "Your face when the hairdresser asks 'how does it look?'", sv: "Din min när frisören frågar 'blev det bra?'" },
  { id: "innocent_unposted_sky", category: "innocent", en: "The sky photo you took and never posted", sv: "Himmelbilden du tog men aldrig lade upp" },
  { id: "innocent_parents_texting", category: "innocent", en: "What it looks like when your parents text you", sv: "Så ser det ut när dina föräldrar sms:ar dig" },
  { id: "innocent_meme_life_now", category: "innocent", en: "The meme that describes your life right now", sv: "Memen som beskriver ditt liv just nu" },
  { id: "innocent_exam_week", category: "innocent", en: "You during exam week", sv: "Du under tentaveckan" },
  { id: "innocent_resolution_february", category: "innocent", en: "What your New Year's resolution looks like by February", sv: "Hur ditt nyårslöfte ser ut i februari" },
  { id: "innocent_guests_arriving", category: "innocent", en: "Your home five minutes before the guests arrive", sv: "Ditt hem fem minuter innan gästerna kommer" },
  { id: "innocent_swedish_summer", category: "innocent", en: "Swedish summer in one picture", sv: "Svensk sommar i en bild" },
  { id: "innocent_what_november_does", category: "innocent", en: "What November does to you", sv: "Vad november gör med dig" },
  { id: "innocent_plant_care", category: "innocent", en: "The plant you swear you're taking care of", sv: "Växten du lovar att du tar hand om" },
  { id: "innocent_accidental_front_camera", category: "innocent", en: "A photo you accidentally took with the front camera", sv: "En bild du råkade ta med framkameran" },
  { id: "innocent_before_first_coffee", category: "innocent", en: "You before your first coffee", sv: "Du innan första kaffet" },
  { id: "innocent_nobody_asked_for", category: "innocent", en: "The photo nobody asked for but everyone needs", sv: "Bilden ingen bad om men alla behöver" },
  { id: "innocent_zero_context", category: "innocent", en: "A photo that makes zero sense without context", sv: "En bild som är helt obegriplig utan sammanhang" },
  { id: "innocent_proof_productive", category: "innocent", en: "Proof that you were productive today", sv: "Bevis på att du var produktiv idag" },
  { id: "innocent_procrastination", category: "innocent", en: "What you do instead of the thing you should be doing", sv: "Det du gör istället för det du borde göra" },
  { id: "innocent_airport_5am", category: "innocent", en: "Your mood at the airport at 5 a.m.", sv: "Ditt humör på flygplatsen klockan fem på morgonen" },
  { id: "innocent_train_delayed", category: "innocent", en: "Your face when the train is delayed again", sv: "Din min när tåget är försenat igen" },
  { id: "innocent_bus_drives_off", category: "innocent", en: "When the bus drives off right in front of you", sv: "När bussen kör iväg mitt framför näsan på dig" },
  { id: "innocent_screen_time_reason", category: "innocent", en: "The real reason your screen time is so high", sv: "Den verkliga anledningen till att din skärmtid är så hög" },
  { id: "innocent_dream_home", category: "innocent", en: "Your dream home", sv: "Ditt drömboende" },
  { id: "innocent_you_at_80", category: "innocent", en: "You at 80", sv: "Du när du är 80" },
  { id: "innocent_animal_you_would_be", category: "innocent", en: "The animal you would be", sv: "Djuret du skulle vara" },
  { id: "innocent_friday_feeling", category: "innocent", en: "The Friday feeling", sv: "Fredagskänslan" },
  { id: "innocent_left_on_read", category: "innocent", en: "When they read your message three hours ago and still haven't replied", sv: "När de läste ditt meddelande för tre timmar sen och fortfarande inte har svarat" },
  { id: "innocent_ambitious_cooking", category: "innocent", en: "Your most ambitious cooking attempt", sv: "Ditt mest ambitiösa matlagningsförsök" },
  { id: "innocent_trip_summary", category: "innocent", en: "The vacation photo that sums up the whole trip", sv: "Semesterbilden som sammanfattar hela resan" },
  { id: "innocent_tourist_mode", category: "innocent", en: "You in full tourist mode", sv: "Du i fullt turistläge" },
  { id: "innocent_family_dinner", category: "innocent", en: "A family get-together in one picture", sv: "Släktmiddag i en bild" },
  { id: "innocent_christmas_mood", category: "innocent", en: "Your Christmas mood", sv: "Ditt julhumör" },
  { id: "innocent_midsummer", category: "innocent", en: "What Midsummer looks like for you", sv: "Hur midsommar ser ut för dig" },
  { id: "innocent_birthday_feeling", category: "innocent", en: "How you feel on your birthday", sv: "Hur du känner dig på din födelsedag" },
  { id: "innocent_perfect_rainy_day", category: "innocent", en: "The perfect rainy day", sv: "Den perfekta regniga dagen" },
  { id: "innocent_snow_chaos", category: "innocent", en: "When it snows and the whole country stops working", sv: "När det snöar och hela landet slutar fungera" },
  { id: "innocent_home_office", category: "innocent", en: "Your work-from-home setup, honestly", sv: "Ditt hemmakontor, ärligt talat" },
  { id: "innocent_that_coworker", category: "innocent", en: "That one coworker's energy", sv: "Energin från den där kollegan" },
  { id: "innocent_tuesday_lunch_box", category: "innocent", en: "What your lunch box looks like on a normal Tuesday", sv: "Hur din matlåda ser ut en vanlig tisdag" },
  { id: "innocent_need_more_sleep", category: "innocent", en: "A clear sign you need more sleep", sv: "Ett tydligt tecken på att du behöver sova mer" },
  { id: "innocent_brain_during_test", category: "innocent", en: "Your brain during a test", sv: "Din hjärna under ett prov" },
  { id: "innocent_trying_to_adult", category: "innocent", en: "You trying to act like a grown-up", sv: "Du när du försöker vara vuxen" },
  { id: "innocent_call_instead_of_text", category: "innocent", en: "When someone calls instead of texting", sv: "När någon ringer istället för att sms:a" },
  { id: "innocent_unknown_number", category: "innocent", en: "Your reaction when an unknown number calls", sv: "Din reaktion när ett okänt nummer ringer" },
  { id: "innocent_long_voice_message", category: "innocent", en: "When someone sends you a seven-minute voice message", sv: "När någon skickar ett röstmeddelande på sju minuter" },
  { id: "innocent_plans_cancelled_relief", category: "innocent", en: "When the plans get cancelled and you're secretly relieved", sv: "När planerna ställs in och du i hemlighet är lättad" },
  { id: "innocent_only_know_host", category: "innocent", en: "You at a party where you only know the host", sv: "Du på en fest där du bara känner värden" },
  { id: "innocent_small_talk", category: "innocent", en: "You trying to make small talk", sv: "Du när du försöker kallprata" },
  { id: "innocent_on_the_dance_floor", category: "innocent", en: "What you look like on the dance floor", sv: "Hur du ser ut på dansgolvet" },
  { id: "innocent_shower_singing", category: "innocent", en: "What you think you sound like singing in the shower", sv: "Så tror du att du låter när du sjunger i duschen" },
  { id: "innocent_coziest_photo", category: "innocent", en: "The coziest photo on your phone", sv: "Den mysigaste bilden i din mobil" },
  { id: "innocent_cutest_animal", category: "innocent", en: "The cutest animal photo you have", sv: "Den gulligaste djurbilden du har" },
  { id: "innocent_ugly_cute_animal", category: "innocent", en: "An animal so ugly it's cute", sv: "Ett djur som är så fult att det blir gulligt" },
  { id: "innocent_ugly_but_tasty", category: "innocent", en: "Food that looks terrible but tastes amazing", sv: "Mat som ser hemsk ut men smakar fantastiskt" },
  { id: "innocent_overpriced_buy", category: "innocent", en: "The most overpriced thing you've ever bought", sv: "Det mest överprisade du någonsin har köpt" },
  { id: "innocent_impulse_buy", category: "innocent", en: "Your latest impulse buy", sv: "Ditt senaste impulsköp" },
  { id: "innocent_online_shopping_fiasco", category: "innocent", en: "Your biggest online shopping disaster", sv: "Ditt största nätshoppingfiasko" },
  { id: "innocent_happy_view", category: "innocent", en: "A view that instantly makes you happy", sv: "En utsikt som direkt gör dig glad" },
  { id: "innocent_screams_2010", category: "innocent", en: "Something that screams 2010", sv: "Något som skriker 2010" },
  { id: "innocent_instant_nostalgia", category: "innocent", en: "Something that gives you instant nostalgia", sv: "Något som ger dig direkt nostalgi" },
  { id: "innocent_current_obsession", category: "innocent", en: "Your current obsession", sv: "Det du är besatt av just nu" },
  { id: "innocent_face_every_photo", category: "innocent", en: "The face you make in every single photo", sv: "Minen du gör på varenda bild" },
  { id: "innocent_finally_get_it", category: "innocent", en: "When you finally understand the assignment", sv: "När du äntligen fattar uppgiften" },
  { id: "innocent_parallel_parking", category: "innocent", en: "You trying to parallel park", sv: "Du när du försöker fickparkera" },
  { id: "innocent_clean_instead_of_study", category: "innocent", en: "When you clean the whole apartment just to avoid studying", sv: "När du städar hela lägenheten bara för att slippa plugga" },
  { id: "innocent_hungry_question", category: "innocent", en: "You when you're starving and someone asks you a question", sv: "Du när du är vrålhungrig och någon ställer en fråga" },
  { id: "innocent_waiting_for_reply", category: "innocent", en: "You waiting for them to text back", sv: "Du när du väntar på att de ska svara" },
  { id: "innocent_save_in_fire", category: "innocent", en: "The one thing you'd grab if you had to leave home in 30 seconds", sv: "Det enda du skulle ta med dig om du var tvungen att lämna hemmet på 30 sekunder" },
  { id: "innocent_main_character", category: "innocent", en: "You with headphones on, feeling like the main character", sv: "Du när du har hörlurar i och känner dig som huvudpersonen i en film" },
  { id: "innocent_april_weather", category: "innocent", en: "Swedish weather in April", sv: "Svenskt väder i april" },
  { id: "innocent_self_scan_check", category: "innocent", en: "When you get picked for a random check at the self-scan checkout", sv: "När du blir utvald för kontroll i självscanningen" },
  { id: "innocent_potluck_contribution", category: "innocent", en: "What you bring to the potluck", sv: "Det du tar med dig till knytkalaset" },
  { id: "innocent_bad_decision_face", category: "innocent", en: "The face of someone about to make a bad decision", sv: "Ansiktet på någon som är på väg att fatta ett dåligt beslut" },
  { id: "innocent_best_photo_of_you", category: "innocent", en: "The best photo ever taken of you", sv: "Den bästa bilden som någonsin tagits på dig" },
  { id: "innocent_hidden_talent", category: "innocent", en: "Your hidden talent", sv: "Din dolda talang" },
  { id: "innocent_too_many_tabs", category: "innocent", en: "What your brain looks like with 47 tabs open", sv: "Så ser din hjärna ut med 47 flikar öppna" },
  { id: "innocent_scratch_card_win", category: "innocent", en: "You after winning 50 kronor on a scratch card", sv: "Du när du vinner 50 kronor på en trisslott" },
  { id: "innocent_terms_and_conditions", category: "innocent", en: "You pretending you've read the terms and conditions", sv: "Du när du låtsas att du har läst villkoren" },
  { id: "innocent_autumn_walk", category: "innocent", en: "Autumn in one picture", sv: "Hösten i en bild" },
  { id: "innocent_saturday_candy", category: "innocent", en: "What your Saturday candy looks like", sv: "Hur ditt lördagsgodis ser ut" },
  { id: "innocent_fika_break", category: "innocent", en: "The perfect coffee break", sv: "Den perfekta fikapausen" },
  { id: "innocent_laundry_room_note", category: "innocent", en: "The passive-aggressive note in the laundry room", sv: "Den passivt aggressiva lappen i tvättstugan" },

  // --- Adult (expansion) ---
  { id: "adult_third_drink_dancing", category: "adult", en: "How you dance after the third drink", sv: "Hur du dansar efter tredje drinken" },
  { id: "adult_dating_profile_pic", category: "adult", en: "The photo you'd use as your dating profile picture", sv: "Bilden du skulle ha som profilbild på dejtingappen" },
  { id: "adult_morning_after_picture", category: "adult", en: "The morning after in one picture", sv: "Dagen efter i en bild" },
  { id: "adult_sunday_hangover", category: "adult", en: "Your Sunday hangover", sv: "Din söndagsbakfylla" },
  { id: "adult_ex_3am_text", category: "adult", en: "What you want to text your ex at 3 a.m.", sv: "Det du vill sms:a ditt ex klockan tre på natten" },
  { id: "adult_ex_likes_old_photo", category: "adult", en: "When your ex likes a photo from 2019", sv: "När ditt ex gillar en bild från 2019" },
  { id: "adult_first_date_prep", category: "adult", en: "You getting ready for a first date", sv: "Du när du gör dig i ordning inför en första dejt" },
  { id: "adult_date_going_badly", category: "adult", en: "Your face when the date is going terribly", sv: "Din min när dejten går åt skogen" },
  { id: "adult_date_going_well", category: "adult", en: "When the date is going so well you forget your phone exists", sv: "När dejten går så bra att du glömmer bort mobilen" },
  { id: "adult_instant_swipe_right", category: "adult", en: "What makes you swipe right instantly", sv: "Det som får dig att swipa höger direkt" },
  { id: "adult_ignored_warning_sign", category: "adult", en: "A warning sign you'd ignore anyway if they were hot enough", sv: "En varningsflagga du ändå skulle blunda för om personen var snygg nog" },
  { id: "adult_pregame", category: "adult", en: "What the pregame looks like", sv: "Hur förfesten ser ut" },
  { id: "adult_refusing_to_go_home", category: "adult", en: "You at 4 a.m. refusing to go home", sv: "Du klockan fyra på natten när du vägrar gå hem" },
  { id: "adult_late_night_kebab", category: "adult", en: "The 3 a.m. kebab after a night out", sv: "Nattkebaben efter krogen" },
  { id: "adult_bouncer_id_check", category: "adult", en: "Your face when the bouncer studies your ID a little too long", sv: "Din min när vakten kollar legget lite för länge" },
  { id: "adult_liquor_store_friday", category: "adult", en: "The liquor store on a Friday afternoon", sv: "Systemet en fredag eftermiddag" },
  { id: "adult_tipsy_online_shopping", category: "adult", en: "Something you bought online while tipsy", sv: "Något du har köpt på nätet när du var lite på lyset" },
  { id: "adult_after_midnight_selfie", category: "adult", en: "A selfie you took after midnight", sv: "En selfie du tog efter midnatt" },
  { id: "adult_camera_roll_after_party", category: "adult", en: "What your camera roll looks like after a party", sv: "Så ser kamerarullen ut efter en fest" },
  { id: "adult_remembering_last_night", category: "adult", en: "You trying to remember last night", sv: "Du när du försöker minnas gårdagskvällen" },
  { id: "adult_friend_new_crush", category: "adult", en: "When your friend has a new crush and can't talk about anything else", sv: "När din kompis är nykär och inte kan prata om något annat" },
  { id: "adult_crush_texts_back", category: "adult", en: "When your crush actually texts back", sv: "När ditt crush faktiskt svarar" },
  { id: "adult_sexy_selfie_attempt", category: "adult", en: "Your best attempt at a sexy selfie", sv: "Ditt bästa försök till en sexig selfie" },
  { id: "adult_outfit_to_be_noticed", category: "adult", en: "What you wear when you want to be noticed", sv: "Det du har på dig när du vill bli sedd" },
  { id: "adult_walk_of_shame", category: "adult", en: "The walk of shame in one picture", sv: "Walk of shame i en bild" },
  { id: "adult_flirty_text_wrong_person", category: "adult", en: "When you send the flirty text to the wrong person", sv: "När du skickar flörtsms:et till fel person" },
  { id: "adult_mom_sees_story", category: "adult", en: "When you realize your mom can see your story", sv: "När du inser att mamma kan se din story" },
  { id: "adult_flirting_reality", category: "adult", en: "What your flirting actually looks like", sv: "Hur det faktiskt ser ut när du flörtar" },
  { id: "adult_across_the_bar", category: "adult", en: "When someone across the bar keeps looking at you", sv: "När någon på andra sidan baren inte slutar kolla på dig" },
  { id: "adult_come_here_look", category: "adult", en: "Your 'come here' look", sv: "Din 'kom hit'-blick" },
  { id: "adult_wanna_watch_movie", category: "adult", en: "What 'wanna come over and watch a movie?' really means", sv: "Vad 'vill du komma över och kolla på film?' egentligen betyder" },
  { id: "adult_movie_nobody_watched", category: "adult", en: "The movie nobody actually watched", sv: "Filmen som ingen egentligen såg" },
  { id: "adult_hide_when_parents_visit", category: "adult", en: "The thing you hide when your parents visit", sv: "Det du gömmer när dina föräldrar kommer på besök" },
  { id: "adult_bed_after_good_night", category: "adult", en: "Your bed after a very good night", sv: "Din säng efter en väldigt bra natt" },
  { id: "adult_group_chat_never_leak", category: "adult", en: "A screenshot from the group chat that must never get out", sv: "En skärmdump från gruppchatten som aldrig får läcka ut" },
  { id: "adult_you_up", category: "adult", en: "When 'you up?' lights up your screen", sv: "När 'är du vaken?' lyser upp skärmen" },
  { id: "adult_gym_mirror_selfie", category: "adult", en: "Your gym mirror selfie energy", sv: "Energin i din spegelselfie på gymmet" },
  { id: "adult_hot_neighbor_laundry", category: "adult", en: "When the hot neighbor is also in the laundry room", sv: "När den snygga grannen också är i tvättstugan" },
  { id: "adult_your_type", category: "adult", en: "What your type looks like", sv: "Hur din typ ser ut" },
  { id: "adult_love_language", category: "adult", en: "Your love language", sv: "Ditt kärleksspråk" },
  { id: "adult_ex_new_partner", category: "adult", en: "Your face when you see your ex's new partner", sv: "Din min när du ser ditt ex nya partner" },
  { id: "adult_perfect_date", category: "adult", en: "Your idea of a perfect date", sv: "Din bild av en perfekt dejt" },
  { id: "adult_worst_date", category: "adult", en: "The worst date you've ever been on", sv: "Den sämsta dejten du någonsin varit på" },
  { id: "adult_friends_meet_date", category: "adult", en: "Your friends meeting your new date for the first time", sv: "Dina kompisar när de träffar din nya dejt för första gången" },
  { id: "adult_first_beer_friday", category: "adult", en: "The first beer after a long week", sv: "Första ölen efter en lång vecka" },
  { id: "adult_bottomless_brunch", category: "adult", en: "What happens after a bottomless brunch", sv: "Vad som händer efter en brunch med fri påfyllning" },
  { id: "adult_wine_singing", category: "adult", en: "You after two glasses of wine, convinced you can sing", sv: "Du efter två glas vin när du är övertygad om att du kan sjunga" },
  { id: "adult_round_of_shots", category: "adult", en: "The moment someone orders a round of shots", sv: "Ögonblicket när någon beställer in en runda shots" },
  { id: "adult_afterparty", category: "adult", en: "The afterparty in one picture", sv: "Efterfesten i en bild" },
  { id: "adult_taxi_home_4am", category: "adult", en: "The taxi ride home at 4 a.m.", sv: "Taxiresan hem klockan fyra på natten" },
  { id: "adult_bank_app_morning_after", category: "adult", en: "When you check your bank app the morning after", sv: "När du kollar bankappen dagen efter" },
  { id: "adult_sent_messages_after_night", category: "adult", en: "When you check your sent messages after a night out", sv: "När du kollar dina skickade meddelanden efter en utekväll" },
  { id: "adult_spicy_dream", category: "adult", en: "Your face when you wake up from a very spicy dream", sv: "Din min när du vaknar från en väldigt snuskig dröm" },
  { id: "adult_attractive_new_coworker", category: "adult", en: "When the new coworker is way too attractive", sv: "När den nya kollegan är alldeles för snygg" },
  { id: "adult_wedding_open_bar", category: "adult", en: "You at a wedding once the open bar starts", sv: "Du på bröllopet när baren har öppnat" },
  { id: "adult_bachelor_party", category: "adult", en: "What the bachelor or bachelorette party looked like", sv: "Hur svensexan eller möhippan såg ut" },
  { id: "adult_midnight_skinny_dip", category: "adult", en: "Midnight skinny-dipping energy", sv: "Känslan när man nakenbadar vid midnatt" },
  { id: "adult_who_you_kissed", category: "adult", en: "When you remember who you kissed last night", sv: "När du kommer ihåg vem du hånglade med igår" },
  { id: "adult_face_before_kiss", category: "adult", en: "The face you make right before a kiss", sv: "Minen du gör precis innan en kyss" },
  { id: "adult_flirt_free_drink", category: "adult", en: "You flirting your way to a free drink", sv: "Du när du flörtar till dig en gratis drink" },
  { id: "adult_special_occasion_underwear", category: "adult", en: "Your 'special occasion' underwear", sv: "Dina underkläder för speciella tillfällen" },
  { id: "adult_candles_and_playlist", category: "adult", en: "When you light candles and put on exactly the right playlist", sv: "När du tänder ljus och sätter på precis rätt spellista" },
  { id: "adult_autocorrect_flirt", category: "adult", en: "When autocorrect ruins a flirty text", sv: "När autokorrekt förstör ett flörtigt sms" },
  { id: "adult_single_valentines", category: "adult", en: "Being single on Valentine's Day", sv: "Att vara singel på alla hjärtans dag" },
  { id: "adult_relationship_one_picture", category: "adult", en: "Your love life in one picture", sv: "Ditt kärleksliv i en bild" },
  { id: "adult_just_hanging_out", category: "adult", en: "What 'we're just hanging out' feels like after six months", sv: "Hur det känns att 'bara hänga' med någon i ett halvår" },
  { id: "adult_ghosted_after_great_date", category: "adult", en: "When you get ghosted after a great date", sv: "När du blir ghostad efter en superbra dejt" },
  { id: "adult_told_parents_last_night", category: "adult", en: "What you told your parents you did last night", sv: "Det du sa till dina föräldrar att du gjorde igår kväll" },
  { id: "adult_drunk_cooking", category: "adult", en: "The food you cooked drunk at 2 a.m.", sv: "Maten du lagade full klockan två på natten" },
  { id: "adult_sober_friend_1am", category: "adult", en: "The sober friend at 1 a.m.", sv: "Den nyktra kompisen klockan ett på natten" },
  { id: "adult_ex_same_party", category: "adult", en: "When your ex shows up at the same party", sv: "När ditt ex dyker upp på samma fest" },
  { id: "adult_summer_body_honestly", category: "adult", en: "Your summer body, honestly", sv: "Din sommarkropp, ärligt talat" },
  { id: "adult_pickup_line_picture", category: "adult", en: "Your best pickup line in picture form", sv: "Din bästa raggningsreplik i bildform" },
  { id: "adult_losing_strip_poker", category: "adult", en: "When you're losing badly at strip poker", sv: "När du förlorar stort i strippoker" },
  { id: "adult_truth_or_dare", category: "adult", en: "Your face when someone says 'truth or dare?'", sv: "Din min när någon säger 'sanning eller konsekvens?'" },
  { id: "adult_bottle_points_at_you", category: "adult", en: "When the bottle points at you", sv: "När flaskan pekar på dig" },
  { id: "adult_hot_tub_rules", category: "adult", en: "What happens in the hot tub stays in the hot tub", sv: "Det som händer i bubbelpoolen stannar i bubbelpoolen" },
  { id: "adult_hotel_after_conference", category: "adult", en: "The hotel room after the conference party", sv: "Hotellrummet efter konferensfesten" },
  { id: "adult_office_party_two_hours", category: "adult", en: "The office Christmas party, two hours in", sv: "Jobbets julfest efter två timmar" },
  { id: "adult_monday_after_office_party", category: "adult", en: "Your face at work the Monday after the Christmas party", sv: "Din min på jobbet måndagen efter julfesten" },
  { id: "adult_date_not_like_pictures", category: "adult", en: "When your date looks nothing like their pictures", sv: "När din dejt inte alls ser ut som på bilderna" },
  { id: "adult_seductive_pose", category: "adult", en: "Your most seductive pose", sv: "Din mest förföriska pose" },
  { id: "adult_home_after_night_out", category: "adult", en: "The best feeling when you get home after a night out", sv: "Den bästa känslan när man kommer hem efter en utekväll" },
  { id: "adult_shower_save_water", category: "adult", en: "When you shower together 'to save water'", sv: "När ni duschar ihop 'för att spara vatten'" },
  { id: "adult_parents_home_early", category: "adult", en: "When your parents come home earlier than expected", sv: "När dina föräldrar kommer hem tidigare än väntat" },
  { id: "adult_sober_month_day_three", category: "adult", en: "Day three of a sober month", sv: "Dag tre av en nykter månad" },
  { id: "adult_festival_day_three", category: "adult", en: "You on day three of the festival", sv: "Du dag tre på festivalen" },
  { id: "adult_student_dinner_party", category: "adult", en: "A student dinner party in one picture", sv: "Sittningen i en bild" },
  { id: "adult_first_kiss_teeth", category: "adult", en: "When your teeth clash during the first kiss", sv: "När era tänder krockar under första kyssen" },
  { id: "adult_date_suggests_your_place", category: "adult", en: "Your face when your date says 'your place or mine?'", sv: "Din min när dejten frågar 'hos dig eller mig?'" },
  { id: "adult_forgot_their_name", category: "adult", en: "When you realize you've forgotten their name", sv: "När du inser att du har glömt vad personen heter" },
  { id: "adult_morning_coffee_with_stranger", category: "adult", en: "Morning coffee with someone whose last name you don't know", sv: "Morgonkaffe med någon vars efternamn du inte vet" },
  { id: "adult_new_lingerie_delivery", category: "adult", en: "When the package arrives and your roommate is curious", sv: "När paketet kommer och din rumskompis är lite för nyfiken" },
  { id: "adult_toast_speech_tipsy", category: "adult", en: "You giving a toast after one glass too many", sv: "Du när du håller tal efter ett glas för mycket" },
  { id: "adult_last_call", category: "adult", en: "The panic when the bar announces last call", sv: "Paniken när baren ropar ut sista beställningen" },
  { id: "adult_kiss_at_midnight", category: "adult", en: "Looking for someone to kiss at midnight on New Year's Eve", sv: "Du när du letar efter någon att pussa på tolvslaget på nyår" },
  { id: "adult_date_meets_pet", category: "adult", en: "Your pet watching you bring a date home", sv: "Ditt husdjur när du tar med dig en dejt hem" },

  // --- Gross (expansion) ---
  { id: "gross_bathroom_after_party", category: "gross", en: "The bathroom after the party", sv: "Toaletten efter festen" },
  { id: "gross_dishes_one_week", category: "gross", en: "Your sink after a week without doing the dishes", sv: "Diskhon efter en vecka utan disk" },
  { id: "gross_visible_morning_breath", category: "gross", en: "What morning breath would look like if you could see it", sv: "Hur morgonandedräkt skulle se ut om man kunde se den" },
  { id: "gross_toenail_on_couch", category: "gross", en: "When you find someone else's toenail on the couch", sv: "När du hittar någon annans tånagel i soffan" },
  { id: "gross_sweaty_bus_neighbor", category: "gross", en: "Sitting next to the sweatiest person on the bus", sv: "När du sitter bredvid den svettigaste personen på bussen" },
  { id: "gross_hair_in_food", category: "gross", en: "When you find a hair in your food", sv: "När du hittar ett hårstrå i maten" },
  { id: "gross_mold_after_bite", category: "gross", en: "When you've already taken a bite before you see the mold", sv: "När du redan har tagit en tugga innan du ser mögelfläcken" },
  { id: "gross_milk_turned", category: "gross", en: "When the milk has basically turned into yogurt", sv: "När mjölken i princip har blivit fil" },
  { id: "gross_floor_knows_where", category: "gross", en: "Your bedroom floor when you 'know exactly where everything is'", sv: "Ditt golv när du 'vet exakt var allt ligger'" },
  { id: "gross_clothes_chair", category: "gross", en: "The clothes chair in its final form", sv: "Klädstolen i sin slutgiltiga form" },
  { id: "gross_car_interior", category: "gross", en: "The inside of your car right now", sv: "Insidan av din bil just nu" },
  { id: "gross_keyboard_crumbs", category: "gross", en: "What's living in your keyboard", sv: "Det som bor i ditt tangentbord" },
  { id: "gross_phone_screen_uv", category: "gross", en: "Your phone screen under a UV light", sv: "Din mobilskärm i UV-ljus" },
  { id: "gross_secret_food_combo", category: "gross", en: "The most disgusting food combo you secretly love", sv: "Den äckligaste matkombon du i hemlighet älskar" },
  { id: "gross_dog_kiss_after", category: "gross", en: "When the dog eats something off the ground and then wants to kiss you", sv: "När hunden äter något från marken och sen vill pussas" },
  { id: "gross_cat_throws_up_4am", category: "gross", en: "When the cat throws up at 4 a.m. right next to your bed", sv: "När katten spyr klockan fyra på natten precis bredvid sängen" },
  { id: "gross_sneeze_no_tissue", category: "gross", en: "When you sneeze and there's no tissue anywhere", sv: "När du nyser och det inte finns en näsduk nånstans" },
  { id: "gross_nose_pick_red_light", category: "gross", en: "When someone catches you picking your nose at a red light", sv: "När någon ser dig peta näsan vid rödljuset" },
  { id: "gross_cotton_swab_check", category: "gross", en: "When you clean your ears and inspect the cotton swab", sv: "När du rensar öronen och granskar topsen" },
  { id: "gross_pimple_mirror", category: "gross", en: "Your face when a pimple pops straight onto the mirror", sv: "Din min när en finne spricker rakt på spegeln" },
  { id: "gross_sweaty_handshake", category: "gross", en: "The sweatiest handshake of your life", sv: "Det svettigaste handslaget i ditt liv" },
  { id: "gross_armpit_stains", category: "gross", en: "When you raise your arm and reveal the sweat stains", sv: "När du lyfter armen och avslöjar svettfläckarna" },
  { id: "gross_festival_toilet", category: "gross", en: "The festival toilet on day four", sv: "Festivaltoaletten dag fyra" },
  { id: "gross_public_pool_locker_room", category: "gross", en: "The locker room at the public pool", sv: "Omklädningsrummet på badhuset" },
  { id: "gross_food_on_shirt_meeting", category: "gross", en: "When you discover yesterday's food on your shirt in the middle of a meeting", sv: "När du upptäcker gårdagens mat på tröjan mitt i ett möte" },
  { id: "gross_retired_sponge", category: "gross", en: "The dish sponge that should have retired months ago", sv: "Disksvampen som borde ha gått i pension för flera månader sen" },
  { id: "gross_bin_in_july", category: "gross", en: "When you open the garbage bin in July", sv: "När du öppnar soptunnan i juli" },
  { id: "gross_fermented_herring", category: "gross", en: "What fermented herring smells like", sv: "Hur surströmming luktar" },
  { id: "gross_fish_in_office_microwave", category: "gross", en: "When someone heats up fish in the office microwave", sv: "När någon värmer fisk i mikron i fikarummet" },
  { id: "gross_office_fridge_friday", category: "gross", en: "The shared office fridge on a Friday", sv: "Kylskåpet i fikarummet en fredag" },
  { id: "gross_someone_used_toothbrush", category: "gross", en: "When you realize someone used your toothbrush", sv: "När du inser att någon har använt din tandborste" },
  { id: "gross_walking_socks", category: "gross", en: "Socks that could walk on their own", sv: "Strumpor som kan gå av sig själva" },
  { id: "gross_sheets_last_changed", category: "gross", en: "When you realize how long ago you changed your sheets", sv: "När du inser hur längesen det var du bytte lakan" },
  { id: "gross_no_toilet_paper", category: "gross", en: "When you realize there's no toilet paper. Too late.", sv: "När du inser att toapappret är slut. För sent." },
  { id: "gross_toilet_wont_flush", category: "gross", en: "When the toilet won't flush at someone else's house", sv: "När toaletten inte vill spola hemma hos någon annan" },
  { id: "gross_elevator_fart", category: "gross", en: "When someone farts in a packed elevator", sv: "När någon fiser i en full hiss" },
  { id: "gross_blame_the_dog", category: "gross", en: "Your face when you blame it on the dog", sv: "Din min när du skyller på hunden" },
  { id: "gross_carpet_stain_after_party", category: "gross", en: "When you find a mystery stain on the carpet after the party", sv: "När du hittar en okänd fläck på mattan efter festen" },
  { id: "gross_bathtub_ring", category: "gross", en: "The bathtub ring nobody wants to talk about", sv: "Smutsranden i badkaret som ingen vill prata om" },
  { id: "gross_two_week_coffee_cup", category: "gross", en: "The coffee cup that's been on your desk for two weeks", sv: "Kaffekoppen som har stått på skrivbordet i två veckor" },
  { id: "gross_unwashed_water_bottle", category: "gross", en: "The smell of a water bottle you forgot to wash", sv: "Lukten av en vattenflaska du har glömt att diska" },
  { id: "gross_forgotten_lunch_box", category: "gross", en: "The lunch box you forgot in your bag over the holidays", sv: "Matlådan du glömde i väskan över ledigheten" },
  { id: "gross_bare_feet_plane", category: "gross", en: "When the person next to you on the plane puts their bare feet on the armrest", sv: "När personen bredvid dig på planet lägger upp sina bara fötter på armstödet" },
  { id: "gross_licked_fingers_snacks", category: "gross", en: "When someone licks their fingers and then digs into the snacks", sv: "När någon slickar på fingrarna och sen tar av snacksen" },
  { id: "gross_double_dip", category: "gross", en: "When someone double-dips in the dip", sv: "När någon doppar chipset två gånger i dippen" },
  { id: "gross_open_mouth_chewing", category: "gross", en: "Someone chewing with their mouth open, in picture form", sv: "Någon som tuggar med öppen mun, i bildform" },
  { id: "gross_under_school_desk", category: "gross", en: "What's stuck under the school desk", sv: "Det som sitter fast under skolbänken" },
  { id: "gross_warm_damp_seat", category: "gross", en: "When the bus seat is warm and slightly damp", sv: "När bussätet är varmt och lite fuktigt" },
  { id: "gross_smell_from_your_shoe", category: "gross", en: "When you realize the smell is coming from your shoe", sv: "När du inser att lukten kommer från din sko" },
  { id: "gross_bird_hit_head", category: "gross", en: "When a bird hits you right on the head", sv: "När en fågel prickar dig mitt på huvudet" },
  { id: "gross_grill_after_bbq", category: "gross", en: "What the grill looks like when everyone's done", sv: "Hur grillen ser ut när alla har ätit klart" },
  { id: "gross_food_crimes", category: "gross", en: "A food crime you've witnessed", sv: "Ett matbrott du har bevittnat" },
  { id: "gross_cereal_with_water", category: "gross", en: "Cereal with water because the milk ran out", sv: "Flingor med vatten för att mjölken tog slut" },
  { id: "gross_floor_pizza_breakfast", category: "gross", en: "Eating pizza you found on the floor the morning after", sv: "När du äter pizza som du hittat på golvet dagen efter" },
  { id: "gross_five_second_rule", category: "gross", en: "When you apply the five-second rule to something you really shouldn't", sv: "När du kör femsekundersregeln på något du verkligen inte borde" },
  { id: "gross_never_cleaned_oven", category: "gross", en: "The inside of an oven that has never been cleaned", sv: "Insidan av en ugn som aldrig har blivit rengjord" },
  { id: "gross_inside_vacuum", category: "gross", en: "What's inside your vacuum cleaner", sv: "Det som finns inne i dammsugaren" },
  { id: "gross_under_bed_moving", category: "gross", en: "What you find under the bed when you move out", sv: "Det du hittar under sängen när du flyttar" },
  { id: "gross_between_couch_cushions", category: "gross", en: "What's hiding between your couch cushions", sv: "Det som gömmer sig mellan soffkuddarna" },
  { id: "gross_nobody_takes_trash", category: "gross", en: "The trash bag nobody wants to take out", sv: "Soppåsen ingen vill gå ut med" },
  { id: "gross_dishes_soaking", category: "gross", en: "When your roommate says the dishes are 'soaking'", sv: "När din rumskompis säger att disken 'ligger i blöt'" },
  { id: "gross_smell_last_nights_drink", category: "gross", en: "Your face when you smell last night's drink", sv: "Din min när du känner lukten av gårdagens drink" },
  { id: "gross_full_blown_cold", category: "gross", en: "What you look like with a full-blown cold", sv: "Hur du ser ut när du är ordentligt förkyld" },
  { id: "gross_snot_bubble", category: "gross", en: "When a snot bubble appears at the worst possible moment", sv: "När en snorbubbla dyker upp vid sämsta tänkbara tillfälle" },
  { id: "gross_ran_for_bus_winter", category: "gross", en: "You after running for the bus in a winter jacket", sv: "Du efter att ha sprungit efter bussen i vinterjacka" },
  { id: "gross_old_fry_in_car", category: "gross", en: "When you find a French fry in the car from last summer", sv: "När du hittar en pommes i bilen från förra sommaren" },
  { id: "gross_subway_pole", category: "gross", en: "The pole on the subway at rush hour", sv: "Stången i tunnelbanan i rusningstid" },
  { id: "gross_swallow_pool_water", category: "gross", en: "When you accidentally swallow a mouthful of pool water", sv: "När du råkar svälja en munfull vatten i simhallen" },
  { id: "gross_floating_band_aid", category: "gross", en: "When a used band-aid floats past you in the pool", sv: "När ett använt plåster flyter förbi dig i poolen" },
  { id: "gross_ugliest_feet_photo", category: "gross", en: "The ugliest feet photo on your phone", sv: "Den fulaste fotbilden i din mobil" },
  { id: "gross_first_date_burp", category: "gross", en: "When a burp slips out on the first date", sv: "När en rap slinker ut på första dejten" },
  { id: "gross_unwiped_gym_bench", category: "gross", en: "When the person before you didn't wipe down the bench", sv: "När personen före dig inte torkade av bänken" },
  { id: "gross_kebab_in_bag", category: "gross", en: "Last night's kebab, discovered in your bag the next morning", sv: "Gårdagens kebab som du hittar i väskan morgonen efter" },
  { id: "gross_curly_hair_on_soap", category: "gross", en: "When there's a curly hair stuck to the soap", sv: "När det sitter ett krulligt hårstrå på tvålen" },
  { id: "gross_smelliest_cheese", category: "gross", en: "The smelliest cheese in your fridge", sv: "Osten i kylen som luktar värst" },
  { id: "gross_drowning_in_mayo", category: "gross", en: "A dish drowning in mayonnaise", sv: "En maträtt som drunknar i majonnäs" },
  { id: "gross_worst_school_lunch", category: "gross", en: "The worst school lunch you remember", sv: "Den äckligaste skollunchen du minns" },
  { id: "gross_mystery_tupperware", category: "gross", en: "When you open a container and can't tell what it used to be", sv: "När du öppnar en burk och inte kan avgöra vad det en gång var" },
  { id: "gross_sweaty_gym_clothes_bag", category: "gross", en: "Gym clothes that spent the weekend in your bag", sv: "Träningskläder som har legat i väskan hela helgen" },
  { id: "gross_hangover_breakfast", category: "gross", en: "The hangover breakfast you're not proud of", sv: "Bakisfrukosten du inte är stolt över" },
];

const statementsById = new Map(STATEMENTS.map((statement) => [statement.id, statement]));

const legacyTextToId = new Map<string, string>();
for (const statement of STATEMENTS) {
  legacyTextToId.set(statement.id, statement.id);
  legacyTextToId.set(statement.en, statement.id);
  legacyTextToId.set(statement.sv, statement.id);
}

export function getStatementById(id: string | null | undefined): StatementEntry | null {
  if (!id) return null;
  return statementsById.get(id) ?? null;
}

export function resolveStatementId(statementOrId: string | null | undefined): string | null {
  if (!statementOrId) return null;
  if (statementsById.has(statementOrId)) return statementOrId;
  return legacyTextToId.get(statementOrId) ?? null;
}

export function getStatementText(statementOrId: string | null | undefined, language: Language): string {
  const entry = getStatementById(resolveStatementId(statementOrId));
  if (!entry) return statementOrId ?? "";
  return language === "sv" ? entry.sv : entry.en;
}

export function getRandomStatement(options?: {
  exclude?: string[];
  category?: StatementCategory;
}): string {
  const excludeIds = new Set((options?.exclude ?? []).map((value) => resolveStatementId(value)).filter((value): value is string => !!value));
  const matchingCategory = options?.category ?? "innocent";
  const categoryPool = STATEMENTS.filter((statement) => statement.category === matchingCategory);
  const remaining = categoryPool.filter((statement) => !excludeIds.has(statement.id));
  const pool = remaining.length > 0 ? remaining : categoryPool;
  return pool[Math.floor(Math.random() * pool.length)].id;
}
