export type ImposterCategory = {
  id: string;
  title: string;
  titleSv: string;
  emoji: string;
  accent: string;
  /** English words; this exact text is what the database stores. */
  prompts: string[];
};

export const IMPOSTER_CATEGORIES: ImposterCategory[] = [
  {
    id: "celebrities",
    title: "Celebrities",
    titleSv: "Kändisar",
    emoji: "🌟",
    accent: "#F59E0B",
    prompts: [
      "Taylor Swift",
      "Cristiano Ronaldo",
      "Beyonce",
      "Zendaya",
      "Drake",
      "Rihanna",
      "Leonardo DiCaprio",
      "Ariana Grande",
      "Dwayne Johnson",
      "Billie Eilish",
      "Kim Kardashian",
      "Tom Holland",
      "Justin Bieber",
      "Selena Gomez",
      "Ed Sheeran",
      "Lady Gaga",
      "Bad Bunny",
      "The Weeknd",
      "Elon Musk",
      "MrBeast",
      "Harry Styles",
      "Timothee Chalamet",
      "Margot Robbie",
      "Snoop Dogg",
      "Zara Larsson",
      "PewDiePie",
      "Dua Lipa",
      "Eminem",
      "Sabrina Carpenter",
      "Keanu Reeves",
    ],
  },
  {
    id: "football",
    title: "Football Players",
    titleSv: "Fotbollsspelare",
    emoji: "⚽",
    accent: "#22C55E",
    prompts: [
      "Lionel Messi",
      "Kylian Mbappe",
      "Erling Haaland",
      "Jude Bellingham",
      "Vinicius Junior",
      "Kevin De Bruyne",
      "Harry Kane",
      "Mohamed Salah",
      "Lamine Yamal",
      "Bukayo Saka",
      "Pedri",
      "Robert Lewandowski",
      "Zlatan Ibrahimovic",
      "Alexander Isak",
      "Viktor Gyokeres",
      "Dejan Kulusevski",
      "Neymar",
      "Luka Modric",
      "Virgil van Dijk",
      "Son Heung-min",
      "Florian Wirtz",
      "Phil Foden",
      "Rodri",
      "Jamal Musiala",
      "Antoine Griezmann",
      "Thibaut Courtois",
      "Manuel Neuer",
      "Ousmane Dembele",
      "Achraf Hakimi",
      "Cole Palmer",
    ],
  },
  {
    id: "food",
    title: "Food",
    titleSv: "Mat",
    emoji: "🍕",
    accent: "#F97316",
    prompts: [
      "Pizza",
      "Burger",
      "Sushi",
      "Pasta",
      "Tacos",
      "Ice cream",
      "Pancakes",
      "Ramen",
      "Lasagna",
      "Chocolate cake",
      "French fries",
      "Fried chicken",
      "Hot dog",
      "Kebab",
      "Burrito",
      "Meatballs",
      "Waffles",
      "Cinnamon bun",
      "Popcorn",
      "Donut",
      "Croissant",
      "Falafel",
      "Nachos",
      "Dumplings",
      "Pad thai",
      "Omelette",
      "Sandwich",
      "Paella",
      "Apple pie",
      "Cotton candy",
    ],
  },
  {
    id: "movies",
    title: "Movies",
    titleSv: "Filmer",
    emoji: "🎬",
    accent: "#A855F7",
    prompts: [
      "Titanic",
      "The Dark Knight",
      "Frozen",
      "Interstellar",
      "Barbie",
      "Avatar",
      "Shrek",
      "Toy Story",
      "The Lion King",
      "Harry Potter",
      "Gladiator",
      "Finding Nemo",
      "Star Wars",
      "Jurassic Park",
      "Avengers: Endgame",
      "Spider-Man",
      "Home Alone",
      "The Matrix",
      "Pirates of the Caribbean",
      "Minions",
      "Jaws",
      "E.T.",
      "Back to the Future",
      "Up",
      "Cars",
      "Oppenheimer",
      "The Hunger Games",
      "Inside Out",
      "Mamma Mia!",
      "Moana",
    ],
  },
  {
    id: "countries",
    title: "Countries",
    titleSv: "Länder",
    emoji: "🌍",
    accent: "#38BDF8",
    prompts: [
      "Brazil",
      "Japan",
      "Italy",
      "Spain",
      "Australia",
      "Mexico",
      "France",
      "Norway",
      "Egypt",
      "Argentina",
      "Thailand",
      "Canada",
      "Sweden",
      "Germany",
      "United States",
      "United Kingdom",
      "China",
      "India",
      "Greece",
      "Turkey",
      "Netherlands",
      "Portugal",
      "Iceland",
      "Finland",
      "Denmark",
      "South Korea",
      "Morocco",
      "South Africa",
      "Jamaica",
      "Switzerland",
    ],
  },
  {
    id: "animals",
    title: "Animals",
    titleSv: "Djur",
    emoji: "🐾",
    accent: "#14B8A6",
    prompts: [
      "Dog",
      "Cat",
      "Horse",
      "Lion",
      "Tiger",
      "Elephant",
      "Giraffe",
      "Zebra",
      "Gorilla",
      "Kangaroo",
      "Panda",
      "Polar bear",
      "Penguin",
      "Shark",
      "Dolphin",
      "Octopus",
      "Crocodile",
      "Snake",
      "Frog",
      "Owl",
      "Flamingo",
      "Moose",
      "Hedgehog",
      "Squirrel",
      "Butterfly",
    ],
  },
  {
    id: "sports",
    title: "Sports",
    titleSv: "Sporter",
    emoji: "🏅",
    accent: "#EF4444",
    prompts: [
      "Football",
      "Ice hockey",
      "Basketball",
      "Tennis",
      "Golf",
      "Swimming",
      "Skiing",
      "Boxing",
      "Handball",
      "Volleyball",
      "Floorball",
      "Padel",
      "Table tennis",
      "Cycling",
      "Figure skating",
      "Surfing",
      "Skateboarding",
      "Horse riding",
      "Bowling",
      "Badminton",
      "Baseball",
      "American football",
      "Formula One",
      "Gymnastics",
      "Darts",
    ],
  },
  {
    id: "jobs",
    title: "Jobs",
    titleSv: "Yrken",
    emoji: "💼",
    accent: "#EC4899",
    prompts: [
      "Firefighter",
      "Police officer",
      "Doctor",
      "Nurse",
      "Teacher",
      "Chef",
      "Pilot",
      "Astronaut",
      "Farmer",
      "Dentist",
      "Hairdresser",
      "Mechanic",
      "Carpenter",
      "Plumber",
      "Electrician",
      "Veterinarian",
      "Photographer",
      "Waiter",
      "Bus driver",
      "Mail carrier",
      "Soldier",
      "Baker",
      "Lifeguard",
      "Garbage collector",
      "Architect",
    ],
  },
  {
    id: "landmarks",
    title: "Landmarks",
    titleSv: "Sevärdheter",
    emoji: "🗼",
    accent: "#6366F1",
    prompts: [
      "Eiffel Tower",
      "Statue of Liberty",
      "Great Wall of China",
      "Pyramids of Giza",
      "Colosseum",
      "Big Ben",
      "Taj Mahal",
      "Leaning Tower of Pisa",
      "Sydney Opera House",
      "Christ the Redeemer",
      "Machu Picchu",
      "Stonehenge",
      "Golden Gate Bridge",
      "Mount Rushmore",
      "Burj Khalifa",
      "Sagrada Familia",
      "Niagara Falls",
      "Mount Everest",
      "Hollywood Sign",
      "Acropolis",
      "Brandenburg Gate",
      "Empire State Building",
      "Neuschwanstein Castle",
      "Mount Fuji",
      "Turning Torso",
    ],
  },
  {
    id: "swedes",
    title: "Swedish celebrities",
    titleSv: "Svenska kändisar",
    emoji: "🇸🇪",
    accent: "#FACC15",
    prompts: [
      "Greta Thunberg",
      "Avicii",
      "Armand Duplantis",
      "Loreen",
      "Mans Zelmerlow",
      "Tove Lo",
      "Robyn",
      "Benjamin Ingrosso",
      "Molly Sanden",
      "Felix Sandman",
      "Veronica Maggio",
      "Yung Lean",
      "Carola",
      "Pernilla Wahlgren",
      "Henrik Lundqvist",
      "Peter Forsberg",
      "Sarah Sjostrom",
      "Bjorn Borg",
      "Alicia Vikander",
      "Alexander Skarsgard",
      "Mikael Persbrandt",
      "King Carl XVI Gustaf",
      "Crown Princess Victoria",
      "Astrid Lindgren",
      "Ingvar Kamprad",
    ],
  },
];

type WordInfo = {
  /** Swedish name, when it differs from the English word. */
  sv?: string;
  /** Nicer spelling for display (e.g. accents), when it differs. */
  display?: string;
  image?: string;
  /** Wikimedia images need attribution. */
  credit?: "wikipedia";
};

/** Pictures and translations per word. Photos: Wikipedia / Wikimedia Commons; flags: flagcdn.com. */
export const IMPOSTER_WORDS: Record<string, WordInfo> = {
  "Taylor Swift": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png/330px-Taylor_Swift_at_the_2023_MTV_Video_Music_Awards_%283%29.png","credit":"wikipedia"},
  "Cristiano Ronaldo": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg/330px-Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg","credit":"wikipedia"},
  "Beyonce": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b7/Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg/330px-Beyonc%C3%A9_-_Tottenham_Hotspur_Stadium_-_1st_June_2023_%2810_of_118%29_%2852946364598%29_%28best_crop%29.jpg","credit":"wikipedia","display":"Beyoncé"},
  "Zendaya": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5a/Zendaya-byPhilipRomano.jpg/330px-Zendaya-byPhilipRomano.jpg","credit":"wikipedia"},
  "Drake": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Drake_at_The_Carter_Effect_2017_%2836818935200%29_%28cropped%29.jpg/330px-Drake_at_The_Carter_Effect_2017_%2836818935200%29_%28cropped%29.jpg","credit":"wikipedia"},
  "Rihanna": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Rihanna_Fenty_2018.png/330px-Rihanna_Fenty_2018.png","credit":"wikipedia"},
  "Leonardo DiCaprio": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/LeoPTABFI191125-28_%28cropped%29.jpg/330px-LeoPTABFI191125-28_%28cropped%29.jpg","credit":"wikipedia"},
  "Ariana Grande": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Ariana_Grande_promoting_Wicked_%282024%29.jpg/330px-Ariana_Grande_promoting_Wicked_%282024%29.jpg","credit":"wikipedia"},
  "Dwayne Johnson": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Dwayne_Johnson-1764_%284x5_cropped_with_moderate_headroom%29.jpg/330px-Dwayne_Johnson-1764_%284x5_cropped_with_moderate_headroom%29.jpg","credit":"wikipedia"},
  "Billie Eilish": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg/330px-BillieEilishO2140725-39_-_54665577407_%28cropped%29.jpg","credit":"wikipedia"},
  "Kim Kardashian": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Kim_Kardashian_West_2014.jpg/330px-Kim_Kardashian_West_2014.jpg","credit":"wikipedia"},
  "Tom Holland": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/TomHolland-byPhilipRomano.jpg/330px-TomHolland-byPhilipRomano.jpg","credit":"wikipedia"},
  "Justin Bieber": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/P20260719DT-1213_President_Donald_J._Trump_and_First_Lady_Melania_Trump_attend_the_FIFA_World_Cup_Final_%28cropped_2%29.jpg/330px-P20260719DT-1213_President_Donald_J._Trump_and_First_Lady_Melania_Trump_attend_the_FIFA_World_Cup_Final_%28cropped_2%29.jpg","credit":"wikipedia"},
  "Selena Gomez": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_10_%28cropped%29.jpg/330px-Selena_Gomez_at_the_2024_Toronto_International_Film_Festival_10_%28cropped%29.jpg","credit":"wikipedia"},
  "Ed Sheeran": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Ed_Sheeran-6886_%28cropped%29.jpg/330px-Ed_Sheeran-6886_%28cropped%29.jpg","credit":"wikipedia"},
  "Lady Gaga": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Lady_Gaga_at_Joe_Biden%27s_inauguration_%28cropped_5%29.jpg/330px-Lady_Gaga_at_Joe_Biden%27s_inauguration_%28cropped_5%29.jpg","credit":"wikipedia"},
  "Bad Bunny": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Bad_Bunny_2019_by_Glenn_Francis_%28cropped%29.jpg/330px-Bad_Bunny_2019_by_Glenn_Francis_%28cropped%29.jpg","credit":"wikipedia"},
  "The Weeknd": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/The_Weeknd_Portrait_by_Brian_Ziff.jpg/330px-The_Weeknd_Portrait_by_Brian_Ziff.jpg","credit":"wikipedia"},
  "Elon Musk": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Elon_Musk_-_54820081119_%28cropped%29.jpg/330px-Elon_Musk_-_54820081119_%28cropped%29.jpg","credit":"wikipedia"},
  "MrBeast": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/MrBeast_in_2026_%28cropped_4%29.png/330px-MrBeast_in_2026_%28cropped_4%29.png","credit":"wikipedia"},
  "Harry Styles": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/HarryStylesWembley170623_%2865_of_93%29_%2852982678051%29_%28cropped_2%29.jpg/330px-HarryStylesWembley170623_%2865_of_93%29_%2852982678051%29_%28cropped_2%29.jpg","credit":"wikipedia"},
  "Timothee Chalamet": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Timoth%C3%A9e_Chalamet-63482_%28cropped%29.jpg/330px-Timoth%C3%A9e_Chalamet-63482_%28cropped%29.jpg","credit":"wikipedia","display":"Timothée Chalamet"},
  "Margot Robbie": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Margot_Robbie_at_the_Paris_premiere_of_%22Wuthering_Heights%22.jpg/330px-Margot_Robbie_at_the_Paris_premiere_of_%22Wuthering_Heights%22.jpg","credit":"wikipedia"},
  "Snoop Dogg": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Snoop_Dogg%2C_WrestleMania_XL_%28cropped%29_%28cropped%29.jpg/330px-Snoop_Dogg%2C_WrestleMania_XL_%28cropped%29_%28cropped%29.jpg","credit":"wikipedia"},
  "Zara Larsson": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/Zara_Larsson_Midnight_Sun_European_Tour_%28cropped%29_%28cropped%29.jpg/330px-Zara_Larsson_Midnight_Sun_European_Tour_%28cropped%29_%28cropped%29.jpg","credit":"wikipedia"},
  "PewDiePie": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Pewdiepie_head_shot.jpg/330px-Pewdiepie_head_shot.jpg","credit":"wikipedia"},
  "Dua Lipa": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Dua_Lipa-69798_%28cropped%29.jpg/330px-Dua_Lipa-69798_%28cropped%29.jpg","credit":"wikipedia"},
  "Eminem": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Eminem_2021_Color_Corrected.jpg/330px-Eminem_2021_Color_Corrected.jpg","credit":"wikipedia"},
  "Sabrina Carpenter": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Sabrina_Carpenter_-_O2_Arena_2025_-_086_%28cropped_2%29.jpg/330px-Sabrina_Carpenter_-_O2_Arena_2025_-_086_%28cropped_2%29.jpg","credit":"wikipedia"},
  "Keanu Reeves": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg/330px-Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg","credit":"wikipedia"},
  "Lionel Messi": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg/330px-Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg","credit":"wikipedia"},
  "Kylian Mbappe": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg/330px-Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg","credit":"wikipedia","display":"Kylian Mbappé"},
  "Erling Haaland": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/330px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg","credit":"wikipedia"},
  "Jude Bellingham": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg/330px-Jude_Bellingham_England_v_Ghana_23_June_2026-061_%28cropped%29.jpg","credit":"wikipedia"},
  "Vinicius Junior": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg/330px-Vin%C3%ADcius_J%C3%BAnior_Brazil_V_Morocco_13_June_2026-207_%28cropped%29.jpg","credit":"wikipedia","display":"Vinícius Júnior"},
  "Kevin De Bruyne": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/330px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg","credit":"wikipedia"},
  "Harry Kane": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg/330px-Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg","credit":"wikipedia"},
  "Mohamed Salah": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_%28cropped%29.jpg/330px-Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_%28cropped%29.jpg","credit":"wikipedia"},
  "Lamine Yamal": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Lamine_Yamal_France_v_Spain_7.24.26-142.jpg/330px-Lamine_Yamal_France_v_Spain_7.24.26-142.jpg","credit":"wikipedia"},
  "Bukayo Saka": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Bukayo_Saka_England_v_Ghana_23_June_2026-057_%28cropped%29.jpg/330px-Bukayo_Saka_England_v_Ghana_23_June_2026-057_%28cropped%29.jpg","credit":"wikipedia"},
  "Pedri": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Pedri_France_v_Spain_7.24.26-245.jpg/330px-Pedri_France_v_Spain_7.24.26-245.jpg","credit":"wikipedia"},
  "Robert Lewandowski": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg/330px-2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg","credit":"wikipedia"},
  "Zlatan Ibrahimovic": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Zlatan_Ibrahimovi%C4%87_nyc.jpg/330px-Zlatan_Ibrahimovi%C4%87_nyc.jpg","credit":"wikipedia","display":"Zlatan Ibrahimović"},
  "Alexander Isak": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Alexander_Isak_-_Sweden_-_Greece21_%28cropped%29.jpg/330px-Alexander_Isak_-_Sweden_-_Greece21_%28cropped%29.jpg","credit":"wikipedia"},
  "Viktor Gyokeres": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Viktor_Gy%C3%B6keres_2026-06-04_1_%28cropped%29.jpg/330px-Viktor_Gy%C3%B6keres_2026-06-04_1_%28cropped%29.jpg","credit":"wikipedia","display":"Viktor Gyökeres"},
  "Dejan Kulusevski": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Sweden-Slovenia_Nations_League_2022-09-27_17_Kulusevski_%28cropped%29.jpg/330px-Sweden-Slovenia_Nations_League_2022-09-27_17_Kulusevski_%28cropped%29.jpg","credit":"wikipedia"},
  "Neymar": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg/330px-Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg","credit":"wikipedia"},
  "Luka Modric": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg/330px-Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg","credit":"wikipedia","display":"Luka Modrić"},
  "Virgil van Dijk": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg/330px-20160604_AUT_NED_8876_%28cropped%29.jpg","credit":"wikipedia"},
  "Son Heung-min": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg/330px-BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg","credit":"wikipedia"},
  "Florian Wirtz": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/70/Florian_Wirtz_Ecuador_v_Germany_25_June_2026-181_%28cropped%29.jpg/330px-Florian_Wirtz_Ecuador_v_Germany_25_June_2026-181_%28cropped%29.jpg","credit":"wikipedia"},
  "Phil Foden": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2613%2C_Phil_Foden.jpg/330px-2023-10-04_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League%2C_RB_Leipzig_-_Manchester_City_FC_1DX_2613%2C_Phil_Foden.jpg","credit":"wikipedia"},
  "Rodri": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Rodri_Argentina_v_Spain_19_July_2026-187_%28cropped%29.jpg/330px-Rodri_Argentina_v_Spain_19_July_2026-187_%28cropped%29.jpg","credit":"wikipedia"},
  "Jamal Musiala": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Jamal_Musiala_Ecuador_v_Germany_25_June_2026-174_%28cropped%29.jpg/330px-Jamal_Musiala_Ecuador_v_Germany_25_June_2026-174_%28cropped%29.jpg","credit":"wikipedia"},
  "Antoine Griezmann": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/FRA-ARG_%2810%29_%28cropped%29.jpg/330px-FRA-ARG_%2810%29_%28cropped%29.jpg","credit":"wikipedia"},
  "Thibaut Courtois": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Thibaut_Courtois_Belgium_v_USA_6_July_2026-076_%28cropped%29.jpg/330px-Thibaut_Courtois_Belgium_v_USA_6_July_2026-076_%28cropped%29.jpg","credit":"wikipedia"},
  "Manuel Neuer": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg/330px-Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg","credit":"wikipedia"},
  "Ousmane Dembele": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Ousmane_Dembele_France_v_Senegal_16_June_2026-341_%28cropped%29_2.jpg/330px-Ousmane_Dembele_France_v_Senegal_16_June_2026-341_%28cropped%29_2.jpg","credit":"wikipedia","display":"Ousmane Dembélé"},
  "Achraf Hakimi": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg/330px-Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg","credit":"wikipedia"},
  "Cole Palmer": {"image":"https://upload.wikimedia.org/wikipedia/commons/f/fb/Cole_Palmer_2025_FIFA_Club_World_Cup_Final.jpg","credit":"wikipedia"},
  "Pizza": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/330px-Pizza-3007395.jpg","credit":"wikipedia"},
  "Burger": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/RedDot_Burger.jpg/330px-RedDot_Burger.jpg","credit":"wikipedia","sv":"Hamburgare"},
  "Sushi": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Sushi_platter.jpg/330px-Sushi_platter.jpg","credit":"wikipedia"},
  "Pasta": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/330px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg","credit":"wikipedia"},
  "Tacos": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg/330px-001_Tacos_de_carnitas%2C_carne_asada_y_al_pastor.jpg","credit":"wikipedia"},
  "Ice cream": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg/330px-Ice_cream_with_whipped_cream%2C_chocolate_syrup%2C_and_a_wafer_%28cropped%29.jpg","credit":"wikipedia","sv":"Glass"},
  "Pancakes": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg/330px-Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg","credit":"wikipedia","sv":"Pannkakor"},
  "Ramen": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg/330px-Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg","credit":"wikipedia"},
  "Lasagna": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Lasagna_bolognese.jpg/330px-Lasagna_bolognese.jpg","credit":"wikipedia","sv":"Lasagne"},
  "Chocolate cake": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Chocolate_fudge_cake.jpg/330px-Chocolate_fudge_cake.jpg","credit":"wikipedia","sv":"Chokladkaka"},
  "French fries": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/French_Fries.JPG/330px-French_Fries.JPG","credit":"wikipedia","sv":"Pommes frites"},
  "Fried chicken": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/Fried-Chicken-Set.jpg/330px-Fried-Chicken-Set.jpg","credit":"wikipedia","sv":"Friterad kyckling"},
  "Hot dog": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Hot_dog_with_mustard.png/330px-Hot_dog_with_mustard.png","credit":"wikipedia","sv":"Varmkorv"},
  "Kebab": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Lula_kebab_2.jpg/330px-Lula_kebab_2.jpg","credit":"wikipedia"},
  "Burrito": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Burrito.JPG/330px-Burrito.JPG","credit":"wikipedia"},
  "Meatballs": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Koettbullar_stockholm2006.jpg/330px-Koettbullar_stockholm2006.jpg","credit":"wikipedia","sv":"Köttbullar"},
  "Waffles": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/Waffles_with_Strawberries.jpg/330px-Waffles_with_Strawberries.jpg","credit":"wikipedia","sv":"Våfflor"},
  "Cinnamon bun": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Cinnamon_roll_in_Stockholm.jpg/330px-Cinnamon_roll_in_Stockholm.jpg","credit":"wikipedia","sv":"Kanelbulle"},
  "Popcorn": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/Popcorn_-_Studio_-_2011.jpg/330px-Popcorn_-_Studio_-_2011.jpg","credit":"wikipedia"},
  "Donut": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Glazed-Donut.jpg/330px-Glazed-Donut.jpg","credit":"wikipedia","sv":"Munk"},
  "Croissant": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Croissant-Petr_Kratochvil.jpg/330px-Croissant-Petr_Kratochvil.jpg","credit":"wikipedia"},
  "Falafel": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Falafels_2.jpg/330px-Falafels_2.jpg","credit":"wikipedia"},
  "Nachos": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Nachos-cheese.jpg/330px-Nachos-cheese.jpg","credit":"wikipedia"},
  "Dumplings": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg/330px-HK_SYP_%E8%A5%BF%E7%87%9F%E7%9B%A4_Sai_Ying_Pun_Kwan_Yick_Building_%E5%90%8D%E6%98%9F%E6%B5%B7%E9%AE%AE%E9%85%92%E5%AE%B6_Star_Seafood_Restaurant_food_%E5%90%9E%E9%BA%B5_Wonton_dim_sum_October_2020_SS2_01.jpg","credit":"wikipedia"},
  "Pad thai": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Phat_Thai_kung_Chang_Khien_street_stall.jpg/330px-Phat_Thai_kung_Chang_Khien_street_stall.jpg","credit":"wikipedia"},
  "Omelette": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg/330px-Gorgonzola_%2B_Bacon_Omelette_%40_Omelegg_%40_Amsterdam_%2816600947041%29.jpg","credit":"wikipedia","sv":"Omelett"},
  "Sandwich": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Bacon%2C_lettuce%2C_tomato%2C_and_avocado.jpg/330px-Bacon%2C_lettuce%2C_tomato%2C_and_avocado.jpg","credit":"wikipedia","sv":"Smörgås"},
  "Paella": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/01_Paella_Valenciana_original.jpg/330px-01_Paella_Valenciana_original.jpg","credit":"wikipedia"},
  "Apple pie": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Apple_pie_14.jpg/330px-Apple_pie_14.jpg","credit":"wikipedia","sv":"Äppelpaj"},
  "Cotton candy": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG/330px-Cotton_candy_%CE%9C%CE%B1%CE%BB%CE%BB%CE%AF_%CF%84%CE%B7%CF%82_%CE%B3%CF%81%CE%B9%CE%AC%CF%82.JPG","credit":"wikipedia","sv":"Sockervadd"},
  "Titanic": {"image":"https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png","credit":"wikipedia"},
  "The Dark Knight": {"image":"https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg","credit":"wikipedia"},
  "Frozen": {"image":"https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg","credit":"wikipedia","sv":"Frost"},
  "Interstellar": {"image":"https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg","credit":"wikipedia"},
  "Barbie": {"image":"https://upload.wikimedia.org/wikipedia/en/0/0b/Barbie_2023_poster.jpg","credit":"wikipedia"},
  "Avatar": {"image":"https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg","credit":"wikipedia"},
  "Shrek": {"image":"https://upload.wikimedia.org/wikipedia/en/7/7b/Shrek_%282001_animated_feature_film%29.jpg","credit":"wikipedia"},
  "Toy Story": {"image":"https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg","credit":"wikipedia"},
  "The Lion King": {"image":"https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg","credit":"wikipedia","sv":"Lejonkungen"},
  "Harry Potter": {"image":"https://thumb.wikimedia.org/wikipedia/en/thumb/7/7a/Harry_Potter_and_the_Philosopher%27s_Stone_banner.jpg/330px-Harry_Potter_and_the_Philosopher%27s_Stone_banner.jpg","credit":"wikipedia"},
  "Gladiator": {"image":"https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png","credit":"wikipedia"},
  "Finding Nemo": {"image":"https://upload.wikimedia.org/wikipedia/en/2/29/Finding_Nemo.jpg","credit":"wikipedia","sv":"Hitta Nemo"},
  "Star Wars": {"image":"https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg","credit":"wikipedia"},
  "Jurassic Park": {"image":"https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg","credit":"wikipedia"},
  "Avengers: Endgame": {"image":"https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg","credit":"wikipedia"},
  "Spider-Man": {"image":"https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg","credit":"wikipedia"},
  "Home Alone": {"image":"https://upload.wikimedia.org/wikipedia/en/7/76/Home_alone_poster.jpg","credit":"wikipedia","sv":"Ensam hemma"},
  "The Matrix": {"image":"https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png","credit":"wikipedia"},
  "Pirates of the Caribbean": {"image":"https://upload.wikimedia.org/wikipedia/en/8/89/Pirates_of_the_Caribbean_-_The_Curse_of_the_Black_Pearl.png","credit":"wikipedia"},
  "Minions": {"image":"https://upload.wikimedia.org/wikipedia/en/1/19/Minions_%282015_film%29.jpg","credit":"wikipedia"},
  "Jaws": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Jaws_movie_poster.jpg/330px-Jaws_movie_poster.jpg","credit":"wikipedia","sv":"Hajen"},
  "E.T.": {"image":"https://upload.wikimedia.org/wikipedia/en/6/66/E_t_the_extra_terrestrial_ver3.jpg","credit":"wikipedia"},
  "Back to the Future": {"image":"https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg","credit":"wikipedia","sv":"Tillbaka till framtiden"},
  "Up": {"image":"https://upload.wikimedia.org/wikipedia/en/0/05/Up_%282009_film%29.jpg","credit":"wikipedia","sv":"Upp"},
  "Cars": {"image":"https://upload.wikimedia.org/wikipedia/en/3/34/Cars_2006.jpg","credit":"wikipedia","sv":"Bilar"},
  "Oppenheimer": {"image":"https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg","credit":"wikipedia"},
  "The Hunger Games": {"image":"https://upload.wikimedia.org/wikipedia/en/4/42/HungerGamesPoster.jpg","credit":"wikipedia"},
  "Inside Out": {"image":"https://upload.wikimedia.org/wikipedia/en/0/0a/Inside_Out_%282015_film%29_poster.jpg","credit":"wikipedia","sv":"Insidan ut"},
  "Mamma Mia!": {"image":"https://upload.wikimedia.org/wikipedia/en/9/95/Mamma_Mia_%282008%29_US_poster.jpg","credit":"wikipedia"},
  "Moana": {"image":"https://upload.wikimedia.org/wikipedia/en/2/26/Moana_Teaser_Poster.jpg","credit":"wikipedia","sv":"Vaiana"},
  "Brazil": {"image":"https://flagcdn.com/w320/br.png","sv":"Brasilien"},
  "Japan": {"image":"https://flagcdn.com/w320/jp.png"},
  "Italy": {"image":"https://flagcdn.com/w320/it.png","sv":"Italien"},
  "Spain": {"image":"https://flagcdn.com/w320/es.png","sv":"Spanien"},
  "Australia": {"image":"https://flagcdn.com/w320/au.png","sv":"Australien"},
  "Mexico": {"image":"https://flagcdn.com/w320/mx.png","sv":"Mexiko"},
  "France": {"image":"https://flagcdn.com/w320/fr.png","sv":"Frankrike"},
  "Norway": {"image":"https://flagcdn.com/w320/no.png","sv":"Norge"},
  "Egypt": {"image":"https://flagcdn.com/w320/eg.png","sv":"Egypten"},
  "Argentina": {"image":"https://flagcdn.com/w320/ar.png"},
  "Thailand": {"image":"https://flagcdn.com/w320/th.png"},
  "Canada": {"image":"https://flagcdn.com/w320/ca.png","sv":"Kanada"},
  "Sweden": {"image":"https://flagcdn.com/w320/se.png","sv":"Sverige"},
  "Germany": {"image":"https://flagcdn.com/w320/de.png","sv":"Tyskland"},
  "United States": {"image":"https://flagcdn.com/w320/us.png","sv":"USA"},
  "United Kingdom": {"image":"https://flagcdn.com/w320/gb.png","sv":"Storbritannien"},
  "China": {"image":"https://flagcdn.com/w320/cn.png","sv":"Kina"},
  "India": {"image":"https://flagcdn.com/w320/in.png","sv":"Indien"},
  "Greece": {"image":"https://flagcdn.com/w320/gr.png","sv":"Grekland"},
  "Turkey": {"image":"https://flagcdn.com/w320/tr.png","sv":"Turkiet"},
  "Netherlands": {"image":"https://flagcdn.com/w320/nl.png","sv":"Nederländerna"},
  "Portugal": {"image":"https://flagcdn.com/w320/pt.png"},
  "Iceland": {"image":"https://flagcdn.com/w320/is.png","sv":"Island"},
  "Finland": {"image":"https://flagcdn.com/w320/fi.png"},
  "Denmark": {"image":"https://flagcdn.com/w320/dk.png","sv":"Danmark"},
  "South Korea": {"image":"https://flagcdn.com/w320/kr.png","sv":"Sydkorea"},
  "Morocco": {"image":"https://flagcdn.com/w320/ma.png","sv":"Marocko"},
  "South Africa": {"image":"https://flagcdn.com/w320/za.png","sv":"Sydafrika"},
  "Jamaica": {"image":"https://flagcdn.com/w320/jm.png"},
  "Switzerland": {"image":"https://flagcdn.com/w320/ch.png","sv":"Schweiz"},
  "Dog": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Huskiesatrest.jpg/330px-Huskiesatrest.jpg","credit":"wikipedia","sv":"Hund"},
  "Cat": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Siam_lilacpoint.jpg/330px-Siam_lilacpoint.jpg","credit":"wikipedia","sv":"Katt"},
  "Horse": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Nokota_Horses_cropped.jpg/330px-Nokota_Horses_cropped.jpg","credit":"wikipedia","sv":"Häst"},
  "Lion": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg/330px-020_The_lion_king_Snyggve_in_the_Serengeti_National_Park_Photo_by_Giles_Laurent.jpg","credit":"wikipedia","sv":"Lejon"},
  "Tiger": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg/330px-Bengal_tiger_%28Panthera_tigris_tigris%29_female_3_crop.jpg","credit":"wikipedia"},
  "Elephant": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/African_Bush_Elephant.jpg/330px-African_Bush_Elephant.jpg","credit":"wikipedia","sv":"Elefant"},
  "Giraffe": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Giraffe_Mikumi_National_Park.jpg/330px-Giraffe_Mikumi_National_Park.jpg","credit":"wikipedia","sv":"Giraff"},
  "Zebra": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Plains_Zebra_Equus_quagga_cropped.jpg/330px-Plains_Zebra_Equus_quagga_cropped.jpg","credit":"wikipedia"},
  "Gorilla": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Gorille_des_plaines_de_l%27ouest_%C3%A0_l%27Espace_Zoologique.jpg/330px-Gorille_des_plaines_de_l%27ouest_%C3%A0_l%27Espace_Zoologique.jpg","credit":"wikipedia"},
  "Kangaroo": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg/330px-Forester_kangaroo_%28Macropus_giganteus_tasmaniensis%29_juvenile_hopping_Esk_Valley.jpg","credit":"wikipedia","sv":"Känguru"},
  "Panda": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Grosser_Panda.JPG/330px-Grosser_Panda.JPG","credit":"wikipedia"},
  "Polar bear": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Polar_Bear_-_Alaska_%28cropped%29.jpg/330px-Polar_Bear_-_Alaska_%28cropped%29.jpg","credit":"wikipedia","sv":"Isbjörn"},
  "Penguin": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/South_Shetland-2016-Deception_Island%E2%80%93Chinstrap_penguin_%28Pygoscelis_antarctica%29_04.jpg/330px-South_Shetland-2016-Deception_Island%E2%80%93Chinstrap_penguin_%28Pygoscelis_antarctica%29_04.jpg","credit":"wikipedia","sv":"Pingvin"},
  "Shark": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Corl0207_%2828225976491%29.jpg/330px-Corl0207_%2828225976491%29.jpg","credit":"wikipedia","sv":"Haj"},
  "Dolphin": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Tursiops_truncatus_01.jpg/330px-Tursiops_truncatus_01.jpg","credit":"wikipedia","sv":"Delfin"},
  "Octopus": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Octopus2.jpg/330px-Octopus2.jpg","credit":"wikipedia","sv":"Bläckfisk"},
  "Crocodile": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Nile_crocodile_head.jpg/330px-Nile_crocodile_head.jpg","credit":"wikipedia","sv":"Krokodil"},
  "Snake": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Trimeresurus_sabahi_fucatus%2C_Banded_pit_viper_-_Takua_Pa_District%2C_Phang-nga_Province_%2846710893582%29.jpg/330px-Trimeresurus_sabahi_fucatus%2C_Banded_pit_viper_-_Takua_Pa_District%2C_Phang-nga_Province_%2846710893582%29.jpg","credit":"wikipedia","sv":"Orm"},
  "Frog": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Red-eyed_Leaf_Frog_%2849661076226%29.jpg/330px-Red-eyed_Leaf_Frog_%2849661076226%29.jpg","credit":"wikipedia","sv":"Groda"},
  "Owl": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Bubo_bubo_sibiricus_-_01.JPG/330px-Bubo_bubo_sibiricus_-_01.JPG","credit":"wikipedia","sv":"Uggla"},
  "Flamingo": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Flamingos_Laguna_Colorada.jpg/330px-Flamingos_Laguna_Colorada.jpg","credit":"wikipedia"},
  "Moose": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Alaska_moose.jpg/330px-Alaska_moose.jpg","credit":"wikipedia","sv":"Älg"},
  "Hedgehog": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Igel.JPG/330px-Igel.JPG","credit":"wikipedia","sv":"Igelkott"},
  "Squirrel": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Squirrel_posing.jpg/330px-Squirrel_posing.jpg","credit":"wikipedia","sv":"Ekorre"},
  "Butterfly": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Fesoj_-_Papilio_machaon_%28by%29.jpg/330px-Fesoj_-_Papilio_machaon_%28by%29.jpg","credit":"wikipedia","sv":"Fjäril"},
  "Football": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Football_in_Bloomington%2C_Indiana%2C_1995.jpg/330px-Football_in_Bloomington%2C_Indiana%2C_1995.jpg","credit":"wikipedia","sv":"Fotboll"},
  "Ice hockey": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Pittsburgh_Penguins%2C_Washington_Capitals%2C_Bryan_Rust_%2833744033514%29.jpg/330px-Pittsburgh_Penguins%2C_Washington_Capitals%2C_Bryan_Rust_%2833744033514%29.jpg","credit":"wikipedia","sv":"Ishockey"},
  "Basketball": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/USA_vs._China_Mens_Basketball_-_Beijing_2008_Olympic_Games_%282751923597%29.jpg/330px-USA_vs._China_Mens_Basketball_-_Beijing_2008_Olympic_Games_%282751923597%29.jpg","credit":"wikipedia","sv":"Basket"},
  "Tennis": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/94/2013_Australian_Open_-_Guillaume_Rufin.jpg/330px-2013_Australian_Open_-_Guillaume_Rufin.jpg","credit":"wikipedia"},
  "Golf": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Golfer_swing.jpg/330px-Golfer_swing.jpg","credit":"wikipedia"},
  "Swimming": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Depart4x100.jpg/330px-Depart4x100.jpg","credit":"wikipedia","sv":"Simning"},
  "Skiing": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/20170213_HIRSCHER_MARCEL_C6864.jpg/330px-20170213_HIRSCHER_MARCEL_C6864.jpg","credit":"wikipedia","sv":"Skidåkning"},
  "Boxing": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Boxing_Tournament_in_Aid_of_King_George%27s_Fund_For_Sailors_at_the_Royal_Naval_Air_Station%2C_Henstridge%2C_Somerset%2C_July_1945_A29806.jpg/330px-Boxing_Tournament_in_Aid_of_King_George%27s_Fund_For_Sailors_at_the_Royal_Naval_Air_Station%2C_Henstridge%2C_Somerset%2C_July_1945_A29806.jpg","credit":"wikipedia","sv":"Boxning"},
  "Handball": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/SAP_Arena_Handball_ausverkauft.jpg/330px-SAP_Arena_Handball_ausverkauft.jpg","credit":"wikipedia","sv":"Handboll"},
  "Volleyball": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Brasil_vence_a_Fran%C3%A7a_no_v%C3%B4lei_masculino_1037987-15.08.2016_ffz-6369.jpg/330px-Brasil_vence_a_Fran%C3%A7a_no_v%C3%B4lei_masculino_1037987-15.08.2016_ffz-6369.jpg","credit":"wikipedia","sv":"Volleyboll"},
  "Floorball": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/WFC2018_Czech_Republic_vs_Finland_Adam_Delong_9.jpg/330px-WFC2018_Czech_Republic_vs_Finland_Adam_Delong_9.jpg","credit":"wikipedia","sv":"Innebandy"},
  "Padel": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Sanchez-Casal_Paddle_Tennis_Game.jpg/330px-Sanchez-Casal_Paddle_Tennis_Game.jpg","credit":"wikipedia"},
  "Table tennis": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Mondial_Ping_-_Men%27s_Singles_-_Round_4_-_Kenta_Matsudaira-Vladimir_Samsonov_-_57.jpg/330px-Mondial_Ping_-_Men%27s_Singles_-_Round_4_-_Kenta_Matsudaira-Vladimir_Samsonov_-_57.jpg","credit":"wikipedia","sv":"Bordtennis"},
  "Cycling": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Cycliste_%C3%A0_place_d%27Italie-Paris_crop.jpg/330px-Cycliste_%C3%A0_place_d%27Italie-Paris_crop.jpg","credit":"wikipedia","sv":"Cykling"},
  "Figure skating": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Team_Les_Supreme_Free_Skate_at_the_2026_ISU_Synchronized_Skating_World_Championships_01.jpg/330px-Team_Les_Supreme_Free_Skate_at_the_2026_ISU_Synchronized_Skating_World_Championships_01.jpg","credit":"wikipedia","sv":"Konståkning"},
  "Surfing": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Mavericks_Surf_Contest_2010b.jpg/330px-Mavericks_Surf_Contest_2010b.jpg","credit":"wikipedia"},
  "Skateboarding": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/BackSmithGrind.jpg/330px-BackSmithGrind.jpg","credit":"wikipedia"},
  "Horse riding": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Horse_riding_in_coca_cola_arena_-_melbourne_show_2005.jpg/330px-Horse_riding_in_coca_cola_arena_-_melbourne_show_2005.jpg","credit":"wikipedia","sv":"Ridning"},
  "Bowling": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/US_Navy_090819-N-2259V-119_A_Sailor_releases_the_ball_down_the_lane_at_a_bowling_competition_during_the_2009_San_Diego_Surface_Line_Week.jpg/330px-US_Navy_090819-N-2259V-119_A_Sailor_releases_the_ball_down_the_lane_at_a_bowling_competition_during_the_2009_San_Diego_Surface_Line_Week.jpg","credit":"wikipedia"},
  "Badminton": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Olympics_2012_Mixed_Doubles_Final.jpg/330px-Olympics_2012_Mixed_Doubles_Final.jpg","credit":"wikipedia"},
  "Baseball": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Tommy_Milone_gives_up_a_home_run_to_Mike_Trout_on_May_21%2C_2017.jpg/330px-Tommy_Milone_gives_up_a_home_run_to_Mike_Trout_on_May_21%2C_2017.jpg","credit":"wikipedia"},
  "American football": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Larry_Fitzgerald_catches_TD_at_2009_Pro_Bowl.jpg/330px-Larry_Fitzgerald_catches_TD_at_2009_Pro_Bowl.jpg","credit":"wikipedia","sv":"Amerikansk fotboll"},
  "Formula One": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/2010_Malaysian_GP_opening_lap.jpg/330px-2010_Malaysian_GP_opening_lap.jpg","credit":"wikipedia","sv":"Formel 1"},
  "Gymnastics": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/ESTADOS_UNIDOS_LEVAM_OURO_NA_GIN%C3%81STICA_FEMININA_POR_EQUIPES_DOS_JOGOS_OL%C3%8DMPICOS_RIO_2016_%2828849586476%29.jpg/330px-ESTADOS_UNIDOS_LEVAM_OURO_NA_GIN%C3%81STICA_FEMININA_POR_EQUIPES_DOS_JOGOS_OL%C3%8DMPICOS_RIO_2016_%2828849586476%29.jpg","credit":"wikipedia","sv":"Gymnastik"},
  "Darts": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Darts_in_a_dartboard.jpg/330px-Darts_in_a_dartboard.jpg","credit":"wikipedia","sv":"Dart"},
  "Firefighter": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/FiremenFightBurningBarn.jpg/330px-FiremenFightBurningBarn.jpg","credit":"wikipedia","sv":"Brandman"},
  "Police officer": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Very_friendly_MPS_officers_in_London.jpg/330px-Very_friendly_MPS_officers_in_London.jpg","credit":"wikipedia","sv":"Polis"},
  "Doctor": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Doctor_in_a_clinic_smiling_while_wearing_glasses_and_a_white_coat_with_a_stethoscope_around_her_neck.jpg/330px-Doctor_in_a_clinic_smiling_while_wearing_glasses_and_a_white_coat_with_a_stethoscope_around_her_neck.jpg","credit":"wikipedia","sv":"Läkare"},
  "Nurse": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Nurse_checks_blood_pressure.jpg/330px-Nurse_checks_blood_pressure.jpg","credit":"wikipedia","sv":"Sjuksköterska"},
  "Teacher": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/A_public_high_school_teacher_in_a_classroom_in_the_United_States_08.jpg/330px-A_public_high_school_teacher_in_a_classroom_in_the_United_States_08.jpg","credit":"wikipedia","sv":"Lärare"},
  "Chef": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/Chefs.jpg/330px-Chefs.jpg","credit":"wikipedia","sv":"Kock"},
  "Pilot": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Lt_Mike_Hunter_1.jpg/330px-Lt_Mike_Hunter_1.jpg","credit":"wikipedia"},
  "Astronaut": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Bruce_McCandless_II_during_EVA_in_1984.jpg/330px-Bruce_McCandless_II_during_EVA_in_1984.jpg","credit":"wikipedia"},
  "Farmer": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Woman_at_work%2C_Gujarat.jpg/330px-Woman_at_work%2C_Gujarat.jpg","credit":"wikipedia","sv":"Bonde"},
  "Dentist": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/US_Navy_030124-N-1328C-510_Navy_dentist_treats_patients_aboard_ship.jpg/330px-US_Navy_030124-N-1328C-510_Navy_dentist_treats_patients_aboard_ship.jpg","credit":"wikipedia","sv":"Tandläkare"},
  "Hairdresser": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Frisoerin_%28fcm%29.jpg/330px-Frisoerin_%28fcm%29.jpg","credit":"wikipedia","sv":"Frisör"},
  "Mechanic": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/An_african_lady_working_at_a_garage._She_is_a_mechanic.jpg/330px-An_african_lady_working_at_a_garage._She_is_a_mechanic.jpg","credit":"wikipedia","sv":"Mekaniker"},
  "Carpenter": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/PalmercarpenterA.jpg/330px-PalmercarpenterA.jpg","credit":"wikipedia","sv":"Snickare"},
  "Plumber": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Plumber_at_work.jpg/330px-Plumber_at_work.jpg","credit":"wikipedia","sv":"Rörmokare"},
  "Electrician": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/US_Navy_040902-N-7683J-003_Electrician%27s_Mate_3rd_Class_Tayo_Gbadebo_from_Lagos%2C_Nigeria%2C_rewires_the_motor_from_an_Aqueous_Film_Forming_Foam_%28AFFF%29_Sprinkler_System%27s_pump.jpg/330px-thumbnail.jpg","credit":"wikipedia","sv":"Elektriker"},
  "Veterinarian": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Surgery_performed_on_a_domestic_cat.jpg/330px-Surgery_performed_on_a_domestic_cat.jpg","credit":"wikipedia","sv":"Veterinär"},
  "Photographer": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e9/Photograph_of_a_Photographer.jpg/330px-Photograph_of_a_Photographer.jpg","credit":"wikipedia","sv":"Fotograf"},
  "Waiter": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Annie_O%27Black_1973.jpg/330px-Annie_O%27Black_1973.jpg","credit":"wikipedia","sv":"Servitör"},
  "Bus driver": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Driver_Dave_Marshall_The_Friendly_Bus_Driver.jpg/330px-Driver_Dave_Marshall_The_Friendly_Bus_Driver.jpg","credit":"wikipedia","sv":"Busschaufför"},
  "Mail carrier": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Postman_on_Wandle_Rd%2C_SW17_%285479444030%29.jpg/330px-Postman_on_Wandle_Rd%2C_SW17_%285479444030%29.jpg","credit":"wikipedia","sv":"Brevbärare"},
  "Soldier": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/2ID_Recon_Baghdad.jpg/330px-2ID_Recon_Baghdad.jpg","credit":"wikipedia","sv":"Soldat"},
  "Baker": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/USS_John_C._Stennis_baker.jpg/330px-USS_John_C._Stennis_baker.jpg","credit":"wikipedia","sv":"Bagare"},
  "Lifeguard": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Lifeguard_jumping_into_action%2C_Ocean_City%2C_June_27_%2C2007.jpg/330px-Lifeguard_jumping_into_action%2C_Ocean_City%2C_June_27_%2C2007.jpg","credit":"wikipedia","sv":"Livräddare"},
  "Garbage collector": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Garbage_truck_in_Tbilisi_2.jpg/330px-Garbage_truck_in_Tbilisi_2.jpg","credit":"wikipedia","sv":"Sophämtare"},
  "Architect": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Architect.png/330px-Architect.png","credit":"wikipedia","sv":"Arkitekt"},
  "Eiffel Tower": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/330px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg","credit":"wikipedia","sv":"Eiffeltornet"},
  "Statue of Liberty": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Front_view_of_Statue_of_Liberty_%28cropped%29.jpg/330px-Front_view_of_Statue_of_Liberty_%28cropped%29.jpg","credit":"wikipedia","sv":"Frihetsgudinnan"},
  "Great Wall of China": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/330px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg","credit":"wikipedia","sv":"Kinesiska muren"},
  "Pyramids of Giza": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Pyramids_of_the_Giza_Necropolis.jpg/330px-Pyramids_of_the_Giza_Necropolis.jpg","credit":"wikipedia","sv":"Pyramiderna i Giza"},
  "Colosseum": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/330px-Colosseo_2020.jpg","credit":"wikipedia"},
  "Big Ben": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster%2C_London.jpg/330px-Elizabeth_Tower_and_the_north_front_of_the_Palace_of_Westminster%2C_London.jpg","credit":"wikipedia"},
  "Taj Mahal": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/330px-Taj_Mahal_%28Edited%29.jpeg","credit":"wikipedia"},
  "Leaning Tower of Pisa": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Italy_-_Pisa_-_Leaning_Tower.jpg/330px-Italy_-_Pisa_-_Leaning_Tower.jpg","credit":"wikipedia","sv":"Lutande tornet i Pisa"},
  "Sydney Opera House": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Sydney_Australia._%2821339175489%29.jpg/330px-Sydney_Australia._%2821339175489%29.jpg","credit":"wikipedia","sv":"Operahuset i Sydney"},
  "Christ the Redeemer": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Christ_the_Redeemer_-_Cristo_Redentor.jpg/330px-Christ_the_Redeemer_-_Cristo_Redentor.jpg","credit":"wikipedia","sv":"Kristusstatyn i Rio"},
  "Machu Picchu": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Machu_Picchu%2C_2023_%28012%29.jpg/330px-Machu_Picchu%2C_2023_%28012%29.jpg","credit":"wikipedia"},
  "Stonehenge": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/330px-Stonehenge2007_07_30.jpg","credit":"wikipedia"},
  "Golden Gate Bridge": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Golden_Gate_Bridge_as_seen_from_Battery_East.jpg/330px-Golden_Gate_Bridge_as_seen_from_Battery_East.jpg","credit":"wikipedia","sv":"Golden Gate-bron"},
  "Mount Rushmore": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Mount_Rushmore_detail_view_%28100MP%29.jpg/330px-Mount_Rushmore_detail_view_%28100MP%29.jpg","credit":"wikipedia"},
  "Burj Khalifa": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Burj_Khalifa_%28worlds_tallest_building%29_and_the_Dubai_skyline_%2825781049892%29.jpg/330px-Burj_Khalifa_%28worlds_tallest_building%29_and_the_Dubai_skyline_%2825781049892%29.jpg","credit":"wikipedia"},
  "Sagrada Familia": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/SF_maig_2_cropped.jpg/330px-SF_maig_2_cropped.jpg","credit":"wikipedia","display":"Sagrada Família"},
  "Niagara Falls": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ab/3Falls_Niagara.jpg/330px-3Falls_Niagara.jpg","credit":"wikipedia","sv":"Niagarafallen"},
  "Mount Everest": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg/330px-Mt._Everest_from_Gokyo_Ri_November_5%2C_2012.jpg","credit":"wikipedia"},
  "Hollywood Sign": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Hollywood_sign_%288485145044%29.jpg/330px-Hollywood_sign_%288485145044%29.jpg","credit":"wikipedia","sv":"Hollywoodskylten"},
  "Acropolis": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg/330px-1029_Acropolis_of_Athens_in_Greece_at_night_Photo_by_Giles_Laurent.jpg","credit":"wikipedia","sv":"Akropolis"},
  "Brandenburg Gate": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Brandenburger_Tor_abends.jpg/330px-Brandenburger_Tor_abends.jpg","credit":"wikipedia","sv":"Brandenburger Tor"},
  "Empire State Building": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Empire_State_Building_%28aerial_view%29.jpg/330px-Empire_State_Building_%28aerial_view%29.jpg","credit":"wikipedia"},
  "Neuschwanstein Castle": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Schloss_Neuschwanstein_2013.jpg/330px-Schloss_Neuschwanstein_2013.jpg","credit":"wikipedia","sv":"Slottet Neuschwanstein"},
  "Mount Fuji": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg/330px-View_of_Mount_Fuji_from_%C5%8Cwakudani_20211202.jpg","credit":"wikipedia","sv":"Fuji"},
  "Turning Torso": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Turning_Torso2.jpg/330px-Turning_Torso2.jpg","credit":"wikipedia"},
  "Greta Thunberg": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Greta_Thunberg_in_May_2026_%28cropped_3x4%29.jpg/330px-Greta_Thunberg_in_May_2026_%28cropped_3x4%29.jpg","credit":"wikipedia"},
  "Avicii": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Avicii_2014_003cr.jpg/330px-Avicii_2014_003cr.jpg","credit":"wikipedia"},
  "Armand Duplantis": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Armand_Duplantis_wins_the_Pole_Vault_at_the_2026_Wanda_Diamond_League%E2%80%99s_Weltklasse_Z%C3%BCrich_athletics_competition.jpg/330px-Armand_Duplantis_wins_the_Pole_Vault_at_the_2026_Wanda_Diamond_League%E2%80%99s_Weltklasse_Z%C3%BCrich_athletics_competition.jpg","credit":"wikipedia"},
  "Loreen": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Loreen_-_Melodifestivalen_2023%2C_Malm%C3%B6_118_%28cropped%29.jpg/330px-Loreen_-_Melodifestivalen_2023%2C_Malm%C3%B6_118_%28cropped%29.jpg","credit":"wikipedia"},
  "Mans Zelmerlow": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Melodifestivalen_2025_delt%C3%A4vling_4_Malm%C3%B6_M%C3%A5ns_Zelmerl%C3%B6w_presentation_03.jpg/330px-Melodifestivalen_2025_delt%C3%A4vling_4_Malm%C3%B6_M%C3%A5ns_Zelmerl%C3%B6w_presentation_03.jpg","credit":"wikipedia","display":"Måns Zelmerlöw"},
  "Tove Lo": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Tove_Lo_%282%29_By_Daniel_%C3%85hs_Karlsson.jpeg/330px-Tove_Lo_%282%29_By_Daniel_%C3%85hs_Karlsson.jpeg","credit":"wikipedia"},
  "Robyn": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Robyn_face.jpg/330px-Robyn_face.jpg","credit":"wikipedia"},
  "Benjamin Ingrosso": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/25/Benjamin_Ingrosso_-_Rockbj%C3%B6rnen_2024_%28cropped%29.jpg/330px-Benjamin_Ingrosso_-_Rockbj%C3%B6rnen_2024_%28cropped%29.jpg","credit":"wikipedia"},
  "Molly Sanden": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Molly_Sand%C3%A9n_P%C3%A5_Sommarkrysset_2016.jpg/330px-Molly_Sand%C3%A9n_P%C3%A5_Sommarkrysset_2016.jpg","credit":"wikipedia","display":"Molly Sandén"},
  "Felix Sandman": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Felix_Sandman_Melodifestivalen_2020_Link%C3%B6ping_2_%28cropped%29.jpg/330px-Felix_Sandman_Melodifestivalen_2020_Link%C3%B6ping_2_%28cropped%29.jpg","credit":"wikipedia"},
  "Veronica Maggio": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Veronica_Maggio_-_Homecoming_Festival-4_%28cropped%29.jpg/330px-Veronica_Maggio_-_Homecoming_Festival-4_%28cropped%29.jpg","credit":"wikipedia"},
  "Yung Lean": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Yung_Lean%2C_Clout_Festival_2024_03_%28cropped%29.jpg/330px-Yung_Lean%2C_Clout_Festival_2024_03_%28cropped%29.jpg","credit":"wikipedia"},
  "Carola": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Carola_H%C3%A4ggkvist_in_June_2015-3.jpg/330px-Carola_H%C3%A4ggkvist_in_June_2015-3.jpg","credit":"wikipedia"},
  "Pernilla Wahlgren": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Pernilla_Wahlgren_2016-05-25_001.jpg/330px-Pernilla_Wahlgren_2016-05-25_001.jpg","credit":"wikipedia"},
  "Henrik Lundqvist": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/Henrik_Lundqvist_by_Gage_Skidmore.jpg/330px-Henrik_Lundqvist_by_Gage_Skidmore.jpg","credit":"wikipedia"},
  "Peter Forsberg": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Peter_Forsberg_2016-03-17_001_%28cropped%29.jpg/330px-Peter_Forsberg_2016-03-17_001_%28cropped%29.jpg","credit":"wikipedia"},
  "Sarah Sjostrom": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Sarah_Sj%C3%B6str%C3%B6m_2013_%28cropped%29.jpg/330px-Sarah_Sj%C3%B6str%C3%B6m_2013_%28cropped%29.jpg","credit":"wikipedia","display":"Sarah Sjöström"},
  "Bjorn Borg": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Bjorn_Borg_en_2014.jpg/330px-Bjorn_Borg_en_2014.jpg","credit":"wikipedia","display":"Björn Borg"},
  "Alicia Vikander": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Alicia_Vikander-7756.jpg/330px-Alicia_Vikander-7756.jpg","credit":"wikipedia"},
  "Alexander Skarsgard": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Alexander_Skarsg%C3%A5rd_at_NYFF_2025_04_%28cropped%29.jpg/330px-Alexander_Skarsg%C3%A5rd_at_NYFF_2025_04_%28cropped%29.jpg","credit":"wikipedia","display":"Alexander Skarsgård"},
  "Mikael Persbrandt": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Mikael_Persbrandt_in_2018.jpg/330px-Mikael_Persbrandt_in_2018.jpg","credit":"wikipedia"},
  "King Carl XVI Gustaf": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/06.11.2025_%E2%80%93_Recep%C3%A7%C3%A3o_Oficial_dos_Chefes_de_Delega%C3%A7%C3%A3o_da_C%C3%BApula_do_Clima_%2854906269035%29_%28Carlos_XVI_Gustavo%29.jpg/330px-06.11.2025_%E2%80%93_Recep%C3%A7%C3%A3o_Oficial_dos_Chefes_de_Delega%C3%A7%C3%A3o_da_C%C3%BApula_do_Clima_%2854906269035%29_%28Carlos_XVI_Gustavo%29.jpg","credit":"wikipedia","sv":"Kung Carl XVI Gustaf"},
  "Crown Princess Victoria": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/2025-11-18_Event%2C_Besuch_der_Kronprinzessin_Victoria_von_Schweden_beim_deutschen_Bundespr%C3%A4sidenten_Frank-Walter_Steinmeier_im_November_2025_STP_9817-2.jpg/330px-2025-11-18_Event%2C_Besuch_der_Kronprinzessin_Victoria_von_Schweden_beim_deutschen_Bundespr%C3%A4sidenten_Frank-Walter_Steinmeier_im_November_2025_STP_9817-2.jpg","credit":"wikipedia","sv":"Kronprinsessan Victoria"},
  "Astrid Lindgren": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Astrid_Lindgren_%28cropped%29.jpg/330px-Astrid_Lindgren_%28cropped%29.jpg","credit":"wikipedia"},
  "Ingvar Kamprad": {"image":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Ingvar_Kamprad_Haparanda_June_2010.jpg/330px-Ingvar_Kamprad_Haparanda_June_2010.jpg","credit":"wikipedia"},
};

export function imposterWordLabel(word: string | null | undefined, language: "en" | "sv") {
  if (!word) return "";
  const info = IMPOSTER_WORDS[word];
  return (language === "sv" ? info?.sv : undefined) ?? info?.display ?? word;
}

export function imposterCategoryLabel(category: ImposterCategory | null | undefined, language: "en" | "sv") {
  if (!category) return "";
  return language === "sv" ? category.titleSv : category.title;
}
