export type ImposterCategory = {
  id: string;
  title: string;
  accent: string;
  prompts: string[];
};

export const IMPOSTER_CATEGORIES: ImposterCategory[] = [
  {
    id: "celebrities",
    title: "Celebrities",
    accent: "#F59E0B",
    prompts: [
      "Taylor Swift",
      "Cristiano Ronaldo",
      "Beyonce",
      "Zendaya",
      "Drake",
      "Rihanna",
      "Leonardo DiCaprio",
      "Ariana Grande",
      "Dwayne Johnson",
      "Billie Eilish",
      "Kim Kardashian",
      "Tom Holland",
    ],
  },
  {
    id: "football",
    title: "Football Players",
    accent: "#22C55E",
    prompts: [
      "Lionel Messi",
      "Kylian Mbappe",
      "Erling Haaland",
      "Jude Bellingham",
      "Vinicius Junior",
      "Kevin De Bruyne",
      "Harry Kane",
      "Mohamed Salah",
      "Lamine Yamal",
      "Bukayo Saka",
      "Pedri",
      "Robert Lewandowski",
    ],
  },
  {
    id: "food",
    title: "Food",
    accent: "#F97316",
    prompts: [
      "Pizza",
      "Burger",
      "Sushi",
      "Pasta",
      "Tacos",
      "Ice cream",
      "Pancakes",
      "Ramen",
      "Lasagna",
      "Chocolate cake",
      "French fries",
      "Fried chicken",
    ],
  },
  {
    id: "movies",
    title: "Movies",
    accent: "#A855F7",
    prompts: [
      "Titanic",
      "The Dark Knight",
      "Frozen",
      "Interstellar",
      "Barbie",
      "Avatar",
      "Shrek",
      "Toy Story",
      "The Lion King",
      "Harry Potter",
      "Gladiator",
      "Finding Nemo",
    ],
  },
  {
    id: "countries",
    title: "Countries",
    accent: "#38BDF8",
    prompts: [
      "Brazil",
      "Japan",
      "Italy",
      "Spain",
      "Australia",
      "Mexico",
      "France",
      "Norway",
      "Egypt",
      "Argentina",
      "Thailand",
      "Canada",
    ],
  },
];
