-- Music Quiz: grow the song library (117 hits + 133 classics, 70 of them Swedish).
-- Every track id was checked against Spotify's public oEmbed endpoint and the returned
-- title matched the intended song. Re-running is safe thanks to "on conflict do nothing".

insert into public.music_quiz_library (spotify_url, spotify_track_id, song_title, artist_name, artist_spotify_url, category)
values
  ('https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr', '5IVuqXILoxVWvWEPm82Jxr', 'Crazy In Love', 'Beyoncé, JAŸ-Z', 'https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m', 'hits'),
  ('https://open.spotify.com/track/557un1HgwYMuqfWGSTmnxw', '557un1HgwYMuqfWGSTmnxw', 'Single Ladies (Put a Ring on It)', 'Beyoncé', 'https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m', 'hits'),
  ('https://open.spotify.com/track/2CvOqDpQIMw69cCzWqr5yr', '2CvOqDpQIMw69cCzWqr5yr', 'Halo', 'Beyoncé', 'https://open.spotify.com/artist/6vWDO969PvNqNYHIOW5v0m', 'hits'),
  ('https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM', '2PpruBYCo4H7WOBJ7Q2EwM', 'Hey Ya!', 'Outkast', 'https://open.spotify.com/artist/1G9G7WwrXka3Z1r7aIDjI7', 'hits'),
  ('https://open.spotify.com/track/49FYlytm3dAAraYgpoJZux', '49FYlytm3dAAraYgpoJZux', 'Umbrella', 'Rihanna, JAŸ-Z', 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H', 'hits'),
  ('https://open.spotify.com/track/6qn9YLKt13AGvpq9jfO8py', '6qn9YLKt13AGvpq9jfO8py', 'We Found Love', 'Rihanna, Calvin Harris', 'https://open.spotify.com/artist/5pKCCKE2ajJHZ9KAiaK11H', 'hits'),
  ('https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak', '6I9VzXrHxO9rA9A5euc8Ak', 'Toxic', 'Britney Spears', 'https://open.spotify.com/artist/26dSoYclwsYLMAKD3tpOr4', 'hits'),
  ('https://open.spotify.com/track/3dPQuX8Gs42Y7b454ybpMR', '3dPQuX8Gs42Y7b454ybpMR', 'Seven Nation Army', 'The White Stripes', 'https://open.spotify.com/artist/4F84IBURUo98rz4r61KF70', 'hits'),
  ('https://open.spotify.com/track/1QV6tiMFM6fSOKOGLMHYYg', '1QV6tiMFM6fSOKOGLMHYYg', 'Poker Face', 'Lady Gaga', 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms', 'hits'),
  ('https://open.spotify.com/track/0SiywuOBRcynK0uKGWdCnn', '0SiywuOBRcynK0uKGWdCnn', 'Bad Romance', 'Lady Gaga', 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms', 'hits'),
  ('https://open.spotify.com/track/2VxeLyX666F8uXCJ0dZF8B', '2VxeLyX666F8uXCJ0dZF8B', 'Shallow', 'Lady Gaga, Bradley Cooper', 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms', 'hits'),
  ('https://open.spotify.com/track/4kLLWz7srcuLKA7Et40PQR', '4kLLWz7srcuLKA7Et40PQR', 'I Gotta Feeling', 'Black Eyed Peas', 'https://open.spotify.com/artist/1yxSLGMDHlW21z4YXirZDS', 'hits'),
  ('https://open.spotify.com/track/1mea3bSkSGXuIRvnydlB5b', '1mea3bSkSGXuIRvnydlB5b', 'Viva La Vida', 'Coldplay', 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU', 'hits'),
  ('https://open.spotify.com/track/3AJwUDP919kvQ9QcozQPxg', '3AJwUDP919kvQ9QcozQPxg', 'Yellow', 'Coldplay', 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU', 'hits'),
  ('https://open.spotify.com/track/7LVHVU3tWfcxj5aiPFEW4Q', '7LVHVU3tWfcxj5aiPFEW4Q', 'Fix You', 'Coldplay', 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU', 'hits'),
  ('https://open.spotify.com/track/3d0WouFnFmr0K3kjeza3fF', '3d0WouFnFmr0K3kjeza3fF', 'Hips Don''t Lie', 'Shakira, Wyclef Jean', 'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp', 'hits'),
  ('https://open.spotify.com/track/4B0ScPwmG3oAOg9Ek7ODdm', '4B0ScPwmG3oAOg9Ek7ODdm', 'Waka Waka (This Time for Africa)', 'Shakira, Freshlyground', 'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp', 'hits'),
  ('https://open.spotify.com/track/7iL6o9tox1zgHpKUfh9vuC', '7iL6o9tox1zgHpKUfh9vuC', 'In Da Club', '50 Cent', 'https://open.spotify.com/artist/3q7HBObVc0L8jNeTe5Gofh', 'hits'),
  ('https://open.spotify.com/track/5rb9QrpfcKFHM1EUbSIurX', '5rb9QrpfcKFHM1EUbSIurX', 'Yeah!', 'USHER, Lil Jon, Ludacris', 'https://open.spotify.com/artist/23zg3TcAtWQy7J6upgbUnj', 'hits'),
  ('https://open.spotify.com/track/1v7L65Lzy0j0vdpRjJewt1', '1v7L65Lzy0j0vdpRjJewt1', 'Lose Yourself', 'Eminem', 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR', 'hits'),
  ('https://open.spotify.com/track/7lQ8MOhq6IN2w8EYcFNSUk', '7lQ8MOhq6IN2w8EYcFNSUk', 'Without Me', 'Eminem', 'https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR', 'hits'),
  ('https://open.spotify.com/track/3xrn9i8zhNZsTtcoWgQEAd', '3xrn9i8zhNZsTtcoWgQEAd', 'Since U Been Gone', 'Kelly Clarkson', 'https://open.spotify.com/artist/3BmGtnKgCSGYIUhmivXKWX', 'hits'),
  ('https://open.spotify.com/track/0O45fw2L5vsWpdsOdXwNAR', '0O45fw2L5vsWpdsOdXwNAR', 'SexyBack', 'Justin Timberlake, Timbaland', 'https://open.spotify.com/artist/31TPClRtHm23RisEBtV3X7', 'hits'),
  ('https://open.spotify.com/track/7Lf7oSEVdzZqTA0kEDSlS5', '7Lf7oSEVdzZqTA0kEDSlS5', 'Cry Me a River', 'Justin Timberlake', 'https://open.spotify.com/artist/31TPClRtHm23RisEBtV3X7', 'hits'),
  ('https://open.spotify.com/track/0iGckQFyv6svOfAbAY9aWJ', '0iGckQFyv6svOfAbAY9aWJ', 'Hot N Cold', 'Katy Perry', 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X', 'hits'),
  ('https://open.spotify.com/track/3lXbHd0EoryoQh3vpevNEP', '3lXbHd0EoryoQh3vpevNEP', 'Firework', 'Katy Perry', 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X', 'hits'),
  ('https://open.spotify.com/track/27tNWlhdAryQY04Gb2ZhUI', '27tNWlhdAryQY04Gb2ZhUI', 'Roar', 'Katy Perry', 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X', 'hits'),
  ('https://open.spotify.com/track/14iN3o8ptQ8cFVZTEmyQRV', '14iN3o8ptQ8cFVZTEmyQRV', 'I Kissed A Girl', 'Katy Perry', 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X', 'hits'),
  ('https://open.spotify.com/track/20I6sIOMTCkB6w7ryavxtO', '20I6sIOMTCkB6w7ryavxtO', 'Call Me Maybe', 'Carly Rae Jepsen', 'https://open.spotify.com/artist/6sFIWsNpZYqfjUpaCgueju', 'hits'),
  ('https://open.spotify.com/track/66xHyI6ITToQPm7PdOzIyn', '66xHyI6ITToQPm7PdOzIyn', 'Get Lucky', 'Daft Punk, Pharrell Williams, Nile Rodgers', 'https://open.spotify.com/artist/4tZwfgrHOc3mvqYlEYSvVi', 'hits'),
  ('https://open.spotify.com/track/0DiWol3AO6WpXZgp0goxAV', '0DiWol3AO6WpXZgp0goxAV', 'One More Time', 'Daft Punk', 'https://open.spotify.com/artist/4tZwfgrHOc3mvqYlEYSvVi', 'hits'),
  ('https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH', '60nZcImufyMA1MKQY3dcCH', 'Happy', 'Pharrell Williams', 'https://open.spotify.com/artist/2RdwBSPQiwcmiDo9kixcl8', 'hits'),
  ('https://open.spotify.com/track/7pYfyrMNPn3wtoCyqcTVoI', '7pYfyrMNPn3wtoCyqcTVoI', 'Moves Like Jagger', 'Maroon 5, Christina Aguilera', 'https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP', 'hits'),
  ('https://open.spotify.com/track/3bNv3VuUOKgrf5hu3YcuRo', '3bNv3VuUOKgrf5hu3YcuRo', 'Someone Like You', 'Adele', 'https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY', 'hits'),
  ('https://open.spotify.com/track/1Yk0cQdMLx5RzzFTYwmuld', '1Yk0cQdMLx5RzzFTYwmuld', 'Hello', 'Adele', 'https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY', 'hits'),
  ('https://open.spotify.com/track/3di5hcvxxciiqwMH1jarhY', '3di5hcvxxciiqwMH1jarhY', 'Set Fire to the Rain', 'Adele', 'https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY', 'hits'),
  ('https://open.spotify.com/track/34gCuhDGsG4bRPIf9bb02f', '34gCuhDGsG4bRPIf9bb02f', 'Thinking out Loud', 'Ed Sheeran', 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V', 'hits'),
  ('https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v', '0tgVpDi06FyKpA1z0VMD4v', 'Perfect', 'Ed Sheeran', 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V', 'hits'),
  ('https://open.spotify.com/track/3rmo8F54jFF8OgYsqTxm5d', '3rmo8F54jFF8OgYsqTxm5d', 'Bad Habits', 'Ed Sheeran', 'https://open.spotify.com/artist/6eUKZXaKkcviH0Ku9w2n3V', 'hits'),
  ('https://open.spotify.com/track/09CtPGIpYB4BrO8qb1RGsF', '09CtPGIpYB4BrO8qb1RGsF', 'Sorry', 'Justin Bieber', 'https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s', 'hits'),
  ('https://open.spotify.com/track/6epn3r7S14KUqlReYr77hA', '6epn3r7S14KUqlReYr77hA', 'Baby', 'Justin Bieber, Ludacris', 'https://open.spotify.com/artist/1uNFoZAHBGtllmzznpCI3s', 'hits'),
  ('https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m', '2Fxmhks0bxGSBdJ92vM42m', 'bad guy', 'Billie Eilish', 'https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH', 'hits'),
  ('https://open.spotify.com/track/2N8m6CYs74qQO4mjVcXO30', '2N8m6CYs74qQO4mjVcXO30', 'Dance Monkey', 'Tones And I', 'https://open.spotify.com/artist/2NjfBq1NflQcKSeiDooVjY', 'hits'),
  ('https://open.spotify.com/track/6UelLqGlWMcVH1E5c4H7lY', '6UelLqGlWMcVH1E5c4H7lY', 'Watermelon Sugar', 'Harry Styles', 'https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3', 'hits'),
  ('https://open.spotify.com/track/4Dvkj6JhhA12EX05fT7y2e', '4Dvkj6JhhA12EX05fT7y2e', 'As It Was', 'Harry Styles', 'https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3', 'hits'),
  ('https://open.spotify.com/track/7DSAEUvxU8FajXtRloy8M0', '7DSAEUvxU8FajXtRloy8M0', 'Flowers', 'Miley Cyrus', 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6', 'hits'),
  ('https://open.spotify.com/track/2vwlzO0Qp8kfEtzTsCXfyE', '2vwlzO0Qp8kfEtzTsCXfyE', 'Wrecking Ball', 'Miley Cyrus', 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6', 'hits'),
  ('https://open.spotify.com/track/3E7dfMvvCLUddWissuqMwr', '3E7dfMvvCLUddWissuqMwr', 'Party In The U.S.A.', 'Miley Cyrus', 'https://open.spotify.com/artist/5YGY8feqx7naU7z4HrwZM6', 'hits'),
  ('https://open.spotify.com/track/2HRqTpkrJO5ggZyyK6NPWz', '2HRqTpkrJO5ggZyyK6NPWz', 'Espresso', 'Sabrina Carpenter', 'https://open.spotify.com/artist/74KM79TiuVKeVCqs8QtB0B', 'hits'),
  ('https://open.spotify.com/track/1u8c2t2Cy7UBoG4ArRcF5g', '1u8c2t2Cy7UBoG4ArRcF5g', 'Blank Space', 'Taylor Swift', 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02', 'hits'),
  ('https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20', '5HCyWlXZPP0y6Gqq8TgA20', 'STAY', 'The Kid LAROI, Justin Bieber', 'https://open.spotify.com/artist/2tIP7SsRs7vjIcLrU85W8J', 'hits'),
  ('https://open.spotify.com/track/3PfIrDoz19wz7qK7tYeu62', '3PfIrDoz19wz7qK7tYeu62', 'Don''t Start Now', 'Dua Lipa', 'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we', 'hits'),
  ('https://open.spotify.com/track/5fVcK4ibJpRsjvG5aIYTb7', '5fVcK4ibJpRsjvG5aIYTb7', 'New Rules', 'Dua Lipa', 'https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we', 'hits'),
  ('https://open.spotify.com/track/7ef4DlsgrMEH11cDZd32M6', '7ef4DlsgrMEH11cDZd32M6', 'One Kiss', 'Calvin Harris, Dua Lipa', 'https://open.spotify.com/artist/7CajNmpbOovFoOoasH2HaY', 'hits'),
  ('https://open.spotify.com/track/0TDLuuLlV54CkRRUOahJb4', '0TDLuuLlV54CkRRUOahJb4', 'Titanium', 'David Guetta, Sia', 'https://open.spotify.com/artist/1Cs0zKBU1kc0i8ypK3B9ai', 'hits'),
  ('https://open.spotify.com/track/4VrWlk8IQxevMvERoX08iC', '4VrWlk8IQxevMvERoX08iC', 'Chandelier', 'Sia', 'https://open.spotify.com/artist/5WUlDfRSoLAfcVSX1WnrxN', 'hits'),
  ('https://open.spotify.com/track/378iszndTZAR4dH8kwsLC6', '378iszndTZAR4dH8kwsLC6', 'Cheap Thrills', 'Sia, Sean Paul', 'https://open.spotify.com/artist/5WUlDfRSoLAfcVSX1WnrxN', 'hits'),
  ('https://open.spotify.com/track/2tpWsVSb9UEmDRxAl1zhX1', '2tpWsVSb9UEmDRxAl1zhX1', 'Counting Stars', 'OneRepublic', 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ', 'hits'),
  ('https://open.spotify.com/track/1PzoM54jr13a5eUfCycMKc', '1PzoM54jr13a5eUfCycMKc', 'Radioactive', 'Imagine Dragons', 'https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q', 'hits'),
  ('https://open.spotify.com/track/0pqnGHJpmpxLKifKRmU6WP', '0pqnGHJpmpxLKifKRmU6WP', 'Believer', 'Imagine Dragons', 'https://open.spotify.com/artist/53XhwfbYqKCa1cC15pYq2q', 'hits'),
  ('https://open.spotify.com/track/5VGlqQANWDKJFl0MBG3sg2', '5VGlqQANWDKJFl0MBG3sg2', 'Use Somebody', 'Kings of Leon', 'https://open.spotify.com/artist/2qk9voo8llSGYcZ6xrBzKx', 'hits'),
  ('https://open.spotify.com/track/0ntQJM78wzOLVeCUAW7Y45', '0ntQJM78wzOLVeCUAW7Y45', 'Sex on Fire', 'Kings of Leon', 'https://open.spotify.com/artist/2qk9voo8llSGYcZ6xrBzKx', 'hits'),
  ('https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h', '2nLtzopw4rPReszdYBJU6h', 'Numb', 'Linkin Park', 'https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz', 'hits'),
  ('https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq', '60a0Rd6pjrkxjPbaKzXjfq', 'In the End', 'Linkin Park', 'https://open.spotify.com/artist/6XyY86QOPPrYVGvF9ch6wz', 'hits'),
  ('https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l', '0v1XpBHnsbkCn7iJ9Ucr1l', 'It''s My Life', 'Bon Jovi', 'https://open.spotify.com/artist/58lV9VcRSjABbAbfWS6skp', 'hits'),
  ('https://open.spotify.com/track/4RCWB3V8V0dignt99LZ8vH', '4RCWB3V8V0dignt99LZ8vH', 'Hey There Delilah', 'Plain White T''s', 'https://open.spotify.com/artist/1g1yxsNVPhMUl9GrMjEb2o', 'hits'),
  ('https://open.spotify.com/track/7wZUrN8oemZfsEd1CGkbXE', '7wZUrN8oemZfsEd1CGkbXE', 'Bleeding Love', 'Leona Lewis', 'https://open.spotify.com/artist/5lKZWd6HiSCLfnDGrq9RAm', 'hits'),
  ('https://open.spotify.com/track/3bidbhpOYeV4knp8AIu8Xn', '3bidbhpOYeV4knp8AIu8Xn', 'Can''t Hold Us', 'Macklemore & Ryan Lewis, Ray Dalton', 'https://open.spotify.com/artist/3JhNCzhSMTxs9WLGJJxWOY', 'hits'),
  ('https://open.spotify.com/track/6CjtS2JZH9RkDz5UVInsa9', '6CjtS2JZH9RkDz5UVInsa9', 'Thrift Shop', 'Macklemore & Ryan Lewis, Wanz', 'https://open.spotify.com/artist/5BcAKTbp20cv7tC5VqPFoC', 'hits'),
  ('https://open.spotify.com/track/61dCUoMCg28qEBzrW6htYM', '61dCUoMCg28qEBzrW6htYM', 'Rather Be', 'Clean Bandit, Jess Glynne', 'https://open.spotify.com/artist/6MDME20pz9RveH9rEXvrOM', 'hits'),
  ('https://open.spotify.com/track/4kbj5MwxO1bq9wjT5g9HaA', '4kbj5MwxO1bq9wjT5g9HaA', 'Shut Up and Dance', 'WALK THE MOON', 'https://open.spotify.com/artist/6DIS6PRrLS3wbnZsf7vYic', 'hits'),
  ('https://open.spotify.com/track/3dYD57lRAUcMHufyqn9GcI', '3dYD57lRAUcMHufyqn9GcI', 'Take Me To Church', 'Hozier', 'https://open.spotify.com/artist/2FXC3k01G6Gw61bmprjgqS', 'hits'),
  ('https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB', '7MXVkk9YMctZqd1Srtv4MB', 'Starboy', 'The Weeknd, Daft Punk', 'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ', 'hits'),
  ('https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g', '5QO79kh1waicV47BqGRL3g', 'Save Your Tears', 'The Weeknd', 'https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ', 'hits'),
  ('https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr', '1BxfuPKGuaTgP7aM0Bbdwr', 'Cruel Summer', 'Taylor Swift', 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02', 'hits'),
  ('https://open.spotify.com/track/2plbrEY59IikOBgBGLjaoe', '2plbrEY59IikOBgBGLjaoe', 'Die With A Smile', 'Lady Gaga, Bruno Mars', 'https://open.spotify.com/artist/1HY2Jd0NmPuamShAr6KMms', 'hits'),
  ('https://open.spotify.com/track/4wJ5Qq0jBN4ajy7ouZIV1c', '4wJ5Qq0jBN4ajy7ouZIV1c', 'APT.', 'ROSÉ, Bruno Mars', 'https://open.spotify.com/artist/3eVa5w3URK5duf6eyVDbu9', 'hits'),
  ('https://open.spotify.com/track/6tNQ70jh4OwmPGpYy6R2o9', '6tNQ70jh4OwmPGpYy6R2o9', 'Beautiful Things', 'Benson Boone', 'https://open.spotify.com/artist/22wbnEMDvgVIAGdFeek6ET', 'hits'),
  ('https://open.spotify.com/track/5masKPHeAOVNgxdLebIcK7', '5masKPHeAOVNgxdLebIcK7', 'Stole the Show', 'Kygo, Parson James', 'https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4', 'hits'),
  ('https://open.spotify.com/track/4HlFJV71xXKIGcU3kRyttv', '4HlFJV71xXKIGcU3kRyttv', 'Hey, Soul Sister', 'Train', 'https://open.spotify.com/artist/3FUY2gzHeIiaesXtOAdB7A', 'hits'),
  ('https://open.spotify.com/track/3cHyrEgdyYRjgJKSOiOtcS', '3cHyrEgdyYRjgJKSOiOtcS', 'Timber', 'Pitbull, Kesha', 'https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg', 'hits'),
  ('https://open.spotify.com/track/4QNpBfC0zvjKqPJcyqBy9W', '4QNpBfC0zvjKqPJcyqBy9W', 'Give Me Everything', 'Pitbull, AFROJACK, Ne-Yo, Nayer', 'https://open.spotify.com/artist/0TnOYISbd1XYRBk9myaseg', 'hits'),
  ('https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2', '0nrRP2bk19rLc0orkWPQk2', 'Wake Me Up', 'Avicii', 'https://open.spotify.com/artist/1vCWHaC5f2uS3yhpwWbIA6', 'hits'),
  ('https://open.spotify.com/track/5UqCQaDshqbIk3pkhy4Pjg', '5UqCQaDshqbIk3pkhy4Pjg', 'Levels', 'Avicii', 'https://open.spotify.com/artist/1vCWHaC5f2uS3yhpwWbIA6', 'hits'),
  ('https://open.spotify.com/track/4lhqb6JvbHId48OUJGwymk', '4lhqb6JvbHId48OUJGwymk', 'Hey Brother', 'Avicii', 'https://open.spotify.com/artist/1vCWHaC5f2uS3yhpwWbIA6', 'hits'),
  ('https://open.spotify.com/track/0ct6r3EGTcMLPtrXHDvVjc', '0ct6r3EGTcMLPtrXHDvVjc', 'The Nights', 'Avicii', 'https://open.spotify.com/artist/1vCWHaC5f2uS3yhpwWbIA6', 'hits'),
  ('https://open.spotify.com/track/6Pgkp4qUoTmJIPn7ReaGxL', '6Pgkp4qUoTmJIPn7ReaGxL', 'Without You', 'Avicii, Sandro Cavazza', 'https://open.spotify.com/artist/1vCWHaC5f2uS3yhpwWbIA6', 'hits'),
  ('https://open.spotify.com/track/5tALkmrC4bRfrSDLimAzuq', '5tALkmrC4bRfrSDLimAzuq', 'Don''t You Worry Child', 'Swedish House Mafia, John Martin', 'https://open.spotify.com/artist/1h6Cn3P4NGzXbaXidqURXs', 'hits'),
  ('https://open.spotify.com/track/0R42XHlMMu4hBgOvdICIsU', '0R42XHlMMu4hBgOvdICIsU', 'Save The World', 'Swedish House Mafia', 'https://open.spotify.com/artist/1h6Cn3P4NGzXbaXidqURXs', 'hits'),
  ('https://open.spotify.com/track/3Rc2ajBMInxeNGVkMPC92Y', '3Rc2ajBMInxeNGVkMPC92Y', 'Dancing On My Own', 'Robyn', 'https://open.spotify.com/artist/6UE7nl9mha6s8z0wFQFIZ2', 'hits'),
  ('https://open.spotify.com/track/5kxcj63GYiractdCBUUU1G', '5kxcj63GYiractdCBUUU1G', 'With Every Heartbeat', 'Kleerup, Robyn', 'https://open.spotify.com/artist/2YL0l5fnyHE9FEf1bwFGCc', 'hits'),
  ('https://open.spotify.com/track/1rIKgCH4H52lrvDcz50hS8', '1rIKgCH4H52lrvDcz50hS8', 'Lush Life', 'Zara Larsson', 'https://open.spotify.com/artist/1Xylc3o4UrD53lo9CvFvVg', 'hits'),
  ('https://open.spotify.com/track/6hmhG1b4LEyNuashVvuIAo', '6hmhG1b4LEyNuashVvuIAo', 'Never Forget You', 'Zara Larsson, MNEK', 'https://open.spotify.com/artist/1Xylc3o4UrD53lo9CvFvVg', 'hits'),
  ('https://open.spotify.com/track/1x5sYLZiu9r5E43kMlt9f8', '1x5sYLZiu9r5E43kMlt9f8', 'Symphony', 'Clean Bandit, Zara Larsson', 'https://open.spotify.com/artist/6MDME20pz9RveH9rEXvrOM', 'hits'),
  ('https://open.spotify.com/track/18AJRdgUoO9EYn11N7xzaT', '18AJRdgUoO9EYn11N7xzaT', 'Habits (Stay High)', 'Tove Lo', 'https://open.spotify.com/artist/4NHQUGzhtTLFvgF5SZesLK', 'hits'),
  ('https://open.spotify.com/track/3GBnGi8VktRx2Dr3Abn6m6', '3GBnGi8VktRx2Dr3Abn6m6', 'I Love It', 'Icona Pop, Charli xcx', 'https://open.spotify.com/artist/1VBflYyxBhnDc9uVib98rw', 'hits'),
  ('https://open.spotify.com/track/5M2y8QdDepGYMsWyxhoxQU', '5M2y8QdDepGYMsWyxhoxQU', 'Jag kommer', 'Veronica Maggio', 'https://open.spotify.com/artist/2OIWxN9xUhgUHkeUCWCaNs', 'hits'),
  ('https://open.spotify.com/track/3q8WojYJVZsGClFGFBYdTc', '3q8WojYJVZsGClFGFBYdTc', 'Satan i gatan', 'Veronica Maggio', 'https://open.spotify.com/artist/2OIWxN9xUhgUHkeUCWCaNs', 'hits'),
  ('https://open.spotify.com/track/4MXHBiKcdqHBJ4PeHQJBHO', '4MXHBiKcdqHBJ4PeHQJBHO', 'Måndagsbarn', 'Veronica Maggio', 'https://open.spotify.com/artist/2OIWxN9xUhgUHkeUCWCaNs', 'hits'),
  ('https://open.spotify.com/track/2yz5IaQLnO8WBCIWMXoRBS', '2yz5IaQLnO8WBCIWMXoRBS', 'Känn ingen sorg för mig Göteborg', 'Håkan Hellström', 'https://open.spotify.com/artist/3H7Ez7cwaYw4L3ELy4v3Lc', 'hits'),
  ('https://open.spotify.com/track/2bfRfAO1RNWcpNtWJv042o', '2bfRfAO1RNWcpNtWJv042o', 'Some Die Young', 'Laleh', 'https://open.spotify.com/artist/62QZPjYQMoo5g56FP9Webq', 'hits'),
  ('https://open.spotify.com/track/7qA8S7mbV9uPy9rFprdN3C', '7qA8S7mbV9uPy9rFprdN3C', 'Goliat', 'Laleh', 'https://open.spotify.com/artist/62QZPjYQMoo5g56FP9Webq', 'hits'),
  ('https://open.spotify.com/track/2knr7ikPt4l7bk92qS4ZXW', '2knr7ikPt4l7bk92qS4ZXW', 'Euphoria', 'Loreen', 'https://open.spotify.com/artist/49aaHxvAJ0tCh0F15OnwIl', 'hits'),
  ('https://open.spotify.com/track/7tostJTMXhaRiVLTTXcvhe', '7tostJTMXhaRiVLTTXcvhe', 'Tattoo', 'Loreen', 'https://open.spotify.com/artist/49aaHxvAJ0tCh0F15OnwIl', 'hits'),
  ('https://open.spotify.com/track/21BYhl07wWqGRQaj7sUxdV', '21BYhl07wWqGRQaj7sUxdV', 'Heroes', 'Måns Zelmerlöw', 'https://open.spotify.com/artist/1IxP1g9VrPzJqXFCsuyHKe', 'hits'),
  ('https://open.spotify.com/track/28qkNp9shSV8AQrBwxZf48', '28qkNp9shSV8AQrBwxZf48', 'Dance with Somebody', 'Mando Diao', 'https://open.spotify.com/artist/5I4eibDkC7gg0hmczTZuND', 'hits'),
  ('https://open.spotify.com/track/6290KDuxx4MvPCT5dR8h86', '6290KDuxx4MvPCT5dR8h86', 'Gloria', 'Mando Diao', 'https://open.spotify.com/artist/5I4eibDkC7gg0hmczTZuND', 'hits'),
  ('https://open.spotify.com/track/3zNNXjjjeLrzIXSJZKalDi', '3zNNXjjjeLrzIXSJZKalDi', 'I Follow Rivers', 'Lykke Li, The Magician', 'https://open.spotify.com/artist/6oBm8HB0yfrIc9IHbxs6in', 'hits'),
  ('https://open.spotify.com/track/6sjGsKuInpaK3uoaWGe22W', '6sjGsKuInpaK3uoaWGe22W', 'Från och med Du', 'Oskar Linnros', 'https://open.spotify.com/artist/3E8Mx37sikkaFoX5DRecLi', 'hits'),
  ('https://open.spotify.com/track/3hNpnx2AXhIVBhNOoiBUmI', '3hNpnx2AXhIVBhNOoiBUmI', 'Resten av ditt liv', 'Timbuktu', 'https://open.spotify.com/artist/4bOG1sx3QHFbOUVLNmMpPe', 'hits'),
  ('https://open.spotify.com/track/4rino0wsmUcK36Ro4CCrke', '4rino0wsmUcK36Ro4CCrke', 'Boten Anna', 'Basshunter', 'https://open.spotify.com/artist/37DdwREpvvQHmGLFEZ4h0Q', 'hits'),
  ('https://open.spotify.com/track/5Nr1ZcH9PGTiQdGl9HCCS1', '5Nr1ZcH9PGTiQdGl9HCCS1', 'Now You''re Gone', 'Basshunter, DJ Mental Theos Bazzheadz', 'https://open.spotify.com/artist/37DdwREpvvQHmGLFEZ4h0Q', 'hits'),
  ('https://open.spotify.com/track/1mvZErZBp7WZT3HfGBykao', '1mvZErZBp7WZT3HfGBykao', 'Cry for You', 'September', 'https://open.spotify.com/artist/6VX2R9L0O0d6qPvqGuIH7b', 'hits'),
  ('https://open.spotify.com/track/2aeVGqdsF7WbKZkwhcCeqm', '2aeVGqdsF7WbKZkwhcCeqm', 'Det gör ont', 'Lena Philipsson', 'https://open.spotify.com/artist/7rZYHhxGKbe1XepzlpDlKm', 'hits'),
  ('https://open.spotify.com/track/14AJI1RloVWTh8bJe9gBPM', '14AJI1RloVWTh8bJe9gBPM', 'Händerna mot himlen', 'Petra Marklund', 'https://open.spotify.com/artist/2ZX1rncu0C7WOuSFC1aEbh', 'hits'),
  ('https://open.spotify.com/track/6XGIQNU8VmOBRIdL5OBYKp', '6XGIQNU8VmOBRIdL5OBYKp', 'Evighet', 'Carola', 'https://open.spotify.com/artist/3uFum0NCM1PtmCO0MwsOAt', 'hits'),
  ('https://open.spotify.com/track/33qw98yPnShEQMoF72ORUa', '33qw98yPnShEQMoF72ORUa', 'Amazing', 'Danny Saucedo', 'https://open.spotify.com/artist/5tVyieWwN9j09jXUovK2zN', 'hits'),
  ('https://open.spotify.com/track/1AhDOtG9vPSOmsWgNW0BEY', '1AhDOtG9vPSOmsWgNW0BEY', 'Bohemian Rhapsody', 'Queen', 'https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d', 'classics'),
  ('https://open.spotify.com/track/57JVGBtBLCfHw2muk5416J', '57JVGBtBLCfHw2muk5416J', 'Another One Bites The Dust', 'Queen', 'https://open.spotify.com/artist/1dfeR4HaWDbWqFHLkxsg1d', 'classics'),
  ('https://open.spotify.com/track/40riOy7x9W7GXjyGp4pjAv', '40riOy7x9W7GXjyGp4pjAv', 'Hotel California', 'Eagles', 'https://open.spotify.com/artist/0ECwFtbIWEVNwjlrfc6xoL', 'classics'),
  ('https://open.spotify.com/track/4UDmDIqJIbrW0hMBQMFOsM', '4UDmDIqJIbrW0hMBQMFOsM', 'Stayin'' Alive', 'Bee Gees', 'https://open.spotify.com/artist/1LZEQNv7sE11VDY3SdxQeN', 'classics'),
  ('https://open.spotify.com/track/1h2xVEoJORqrg71HocgqXd', '1h2xVEoJORqrg71HocgqXd', 'Superstition', 'Stevie Wonder', 'https://open.spotify.com/artist/7guDJrEfX3qb6FEbdPA5qi', 'classics'),
  ('https://open.spotify.com/track/7s25THrKz86DM225dOYwnr', '7s25THrKz86DM225dOYwnr', 'Respect', 'Aretha Franklin', 'https://open.spotify.com/artist/7nwUJBm0HE4ZxD3f5cy5ok', 'classics'),
  ('https://open.spotify.com/track/3m7V717IKZqZLW5qUIOxdD', '3m7V717IKZqZLW5qUIOxdD', 'Hey Jude', 'The Beatles', 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2', 'classics'),
  ('https://open.spotify.com/track/7iN1s7xHE4ifF5povM6A48', '7iN1s7xHE4ifF5povM6A48', 'Let It Be', 'The Beatles', 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2', 'classics'),
  ('https://open.spotify.com/track/5ZBeML7Lf3FMEVviTyvi8l', '5ZBeML7Lf3FMEVviTyvi8l', 'Twist And Shout', 'The Beatles', 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2', 'classics'),
  ('https://open.spotify.com/track/6dGnYIeXmHdcikdzNNDMm2', '6dGnYIeXmHdcikdzNNDMm2', 'Here Comes The Sun', 'The Beatles', 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2', 'classics'),
  ('https://open.spotify.com/track/2PzU4IB8Dr6mxV3lHuaG34', '2PzU4IB8Dr6mxV3lHuaG34', '(I Can''t Get No) Satisfaction', 'The Rolling Stones', 'https://open.spotify.com/artist/22bE4uQ6baNwSHPVcDxLCe', 'classics'),
  ('https://open.spotify.com/track/63T7DJ1AFDD6Bn8VzG6JE8', '63T7DJ1AFDD6Bn8VzG6JE8', 'Paint It, Black', 'The Rolling Stones', 'https://open.spotify.com/artist/22bE4uQ6baNwSHPVcDxLCe', 'classics'),
  ('https://open.spotify.com/track/7snQQk1zcKl8gZ92AnueZW', '7snQQk1zcKl8gZ92AnueZW', 'Sweet Child O'' Mine', 'Guns N'' Roses', 'https://open.spotify.com/artist/3qm84nBOXUEQ2vnTfUTTFC', 'classics'),
  ('https://open.spotify.com/track/0eFvoRSTTaR2q8bSWVjwfp', '0eFvoRSTTaR2q8bSWVjwfp', 'Welcome To The Jungle', 'Guns N'' Roses', 'https://open.spotify.com/artist/3qm84nBOXUEQ2vnTfUTTFC', 'classics'),
  ('https://open.spotify.com/track/08mG3Y1vljYA6bvDt4Wqkj', '08mG3Y1vljYA6bvDt4Wqkj', 'Back In Black', 'AC/DC', 'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un', 'classics'),
  ('https://open.spotify.com/track/2zYzyRzz6pRmhPzyfMEC8s', '2zYzyRzz6pRmhPzyfMEC8s', 'Highway to Hell', 'AC/DC', 'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un', 'classics'),
  ('https://open.spotify.com/track/57bgtoPSgt236HzfBOd8kj', '57bgtoPSgt236HzfBOd8kj', 'Thunderstruck', 'AC/DC', 'https://open.spotify.com/artist/711MCceyCBcFnzjGY4Q7Un', 'classics'),
  ('https://open.spotify.com/track/77NNZQSqzLNqh2A9JhLRkg', '77NNZQSqzLNqh2A9JhLRkg', 'Don''t Stop Believin''', 'Journey', 'https://open.spotify.com/artist/0rvjqX7ttXeg3mTy8Xscbt', 'classics'),
  ('https://open.spotify.com/track/2KH16WveTQWT6KOG9Rg6e2', '2KH16WveTQWT6KOG9Rg6e2', 'Eye of the Tiger', 'Survivor', 'https://open.spotify.com/artist/26bcq2nyj5GB7uRr558iQg', 'classics'),
  ('https://open.spotify.com/track/2374M0fQpWi3dLnB54qaLX', '2374M0fQpWi3dLnB54qaLX', 'Africa', 'TOTO', 'https://open.spotify.com/artist/0PFtn5NtBbbUNbU9EAmIWF', 'classics'),
  ('https://open.spotify.com/track/4y1LsJpmMti1PfRQV9AWWe', '4y1LsJpmMti1PfRQV9AWWe', 'Girls Just Want to Have Fun', 'Cyndi Lauper', 'https://open.spotify.com/artist/2BTZIqw0ntH9MvilQ3ewNY', 'classics'),
  ('https://open.spotify.com/track/7o9uu2GDtVDr9nsR7ZRN73', '7o9uu2GDtVDr9nsR7ZRN73', 'Time After Time', 'Cyndi Lauper', 'https://open.spotify.com/artist/2BTZIqw0ntH9MvilQ3ewNY', 'classics'),
  ('https://open.spotify.com/track/2v7ywbUzCgcVohHaKUcacV', '2v7ywbUzCgcVohHaKUcacV', 'Like a Prayer', 'Madonna', 'https://open.spotify.com/artist/6tbjWDEIzxoDsBA1FuhfPW', 'classics'),
  ('https://open.spotify.com/track/4tcauy2xyIv1q0ckvQmc4H', '4tcauy2xyIv1q0ckvQmc4H', 'Material Girl', 'Madonna', 'https://open.spotify.com/artist/6tbjWDEIzxoDsBA1FuhfPW', 'classics'),
  ('https://open.spotify.com/track/6r8k1vznHrzlEKYxL4dZEe', '6r8k1vznHrzlEKYxL4dZEe', 'La Isla Bonita', 'Madonna', 'https://open.spotify.com/artist/6tbjWDEIzxoDsBA1FuhfPW', 'classics'),
  ('https://open.spotify.com/track/27QvYgBk0CHOVHthWnkuWt', '27QvYgBk0CHOVHthWnkuWt', 'Vogue', 'Madonna', 'https://open.spotify.com/artist/6tbjWDEIzxoDsBA1FuhfPW', 'classics'),
  ('https://open.spotify.com/track/1OOtq8tRnDM8kG2gqUPjAj', '1OOtq8tRnDM8kG2gqUPjAj', 'Beat It', 'Michael Jackson', 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm', 'classics'),
  ('https://open.spotify.com/track/2LlQb7Uoj1kKyGhlkBf9aC', '2LlQb7Uoj1kKyGhlkBf9aC', 'Thriller', 'Michael Jackson', 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm', 'classics'),
  ('https://open.spotify.com/track/5T7ywazdGIydr6JCW6t02j', '5T7ywazdGIydr6JCW6t02j', 'Smooth Criminal', 'Michael Jackson', 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm', 'classics'),
  ('https://open.spotify.com/track/7ygpwy2qP3NbrxVkHvUhXY', '7ygpwy2qP3NbrxVkHvUhXY', 'Wonderwall', 'Oasis', 'https://open.spotify.com/artist/2DaxqgrOhkeH0fpeiQq2f4', 'classics'),
  ('https://open.spotify.com/track/12dU3vAh6AFoJkisorfoUl', '12dU3vAh6AFoJkisorfoUl', 'Don''t Look Back In Anger', 'Oasis', 'https://open.spotify.com/artist/2DaxqgrOhkeH0fpeiQq2f4', 'classics'),
  ('https://open.spotify.com/track/57iDDD9N9tTWe75x6qhStw', '57iDDD9N9tTWe75x6qhStw', 'Bitter Sweet Symphony', 'The Verve', 'https://open.spotify.com/artist/2cGwlqi3k18jFpUyTrsR84', 'classics'),
  ('https://open.spotify.com/track/1Je1IMUlBXcx1Fz0WE7oPT', '1Je1IMUlBXcx1Fz0WE7oPT', 'Wannabe', 'Spice Girls', 'https://open.spotify.com/artist/0uq5PttqEjj3IH1bzwcrXF', 'classics'),
  ('https://open.spotify.com/track/3MjUtNVVq3C8Fn0MP3zhXa', '3MjUtNVVq3C8Fn0MP3zhXa', '...Baby One More Time', 'Britney Spears', 'https://open.spotify.com/artist/26dSoYclwsYLMAKD3tpOr4', 'classics'),
  ('https://open.spotify.com/track/2goLsvvODILDzeeiT4dAoR', '2goLsvvODILDzeeiT4dAoR', 'Believe', 'Cher', 'https://open.spotify.com/artist/72OaDtakiy6yFqkt4TsiFt', 'classics'),
  ('https://open.spotify.com/track/47BBI51FKFwOMlIiX6m8ya', '47BBI51FKFwOMlIiX6m8ya', 'I Want It That Way', 'Backstreet Boys', 'https://open.spotify.com/artist/5rSXSAkZ67PYJSvpUpkOr7', 'classics'),
  ('https://open.spotify.com/track/1di1BEgJYzPvXUuinsYJGP', '1di1BEgJYzPvXUuinsYJGP', 'Everybody (Backstreet''s Back)', 'Backstreet Boys', 'https://open.spotify.com/artist/5rSXSAkZ67PYJSvpUpkOr7', 'classics'),
  ('https://open.spotify.com/track/5ZrDlcxIDZyjOzHdYW1ydr', '5ZrDlcxIDZyjOzHdYW1ydr', 'Barbie Girl', 'Aqua', 'https://open.spotify.com/artist/6kBjAFKyd0he7LiA5GQ3Gz', 'classics'),
  ('https://open.spotify.com/track/6x4tKaOzfNJpEJHySoiJcs', '6x4tKaOzfNJpEJHySoiJcs', 'Mambo No. 5 (a Little Bit of...)', 'Lou Bega', 'https://open.spotify.com/artist/46lnlnlU0dXTDpoAUmH6Qx', 'classics'),
  ('https://open.spotify.com/track/0Ph6L4l8dYUuXFmb71Ajnd', '0Ph6L4l8dYUuXFmb71Ajnd', 'Livin'' la Vida Loca', 'Ricky Martin', 'https://open.spotify.com/artist/7slfeZO9LsJbWgpkIoXBUJ', 'classics'),
  ('https://open.spotify.com/track/1KGi9sZVMeszgZOWivFpxs', '1KGi9sZVMeszgZOWivFpxs', 'No Scrubs', 'TLC', 'https://open.spotify.com/artist/0TImkz4nPqjegtVSMZnMRq', 'classics'),
  ('https://open.spotify.com/track/6qspW4YKycviDFjHBOaqUY', '6qspW4YKycviDFjHBOaqUY', 'Waterfalls', 'TLC', 'https://open.spotify.com/artist/0TImkz4nPqjegtVSMZnMRq', 'classics'),
  ('https://open.spotify.com/track/5BIMPccDwShpXq784RJlJp', '5BIMPccDwShpXq784RJlJp', 'Enter Sandman', 'Metallica', 'https://open.spotify.com/artist/2ye2Wgw4gimLv2eAKyk1NB', 'classics'),
  ('https://open.spotify.com/track/31AOj9sFz2gM0O3hMARRBx', '31AOj9sFz2gM0O3hMARRBx', 'Losing My Religion', 'R.E.M.', 'https://open.spotify.com/artist/4KWTAlx2RvbpseOGMEmROg', 'classics'),
  ('https://open.spotify.com/track/2IZZqH4K02UIYg5EohpNHF', '2IZZqH4K02UIYg5EohpNHF', 'Zombie', 'The Cranberries', 'https://open.spotify.com/artist/7t0rwkOPGlDPEhaOcVtOt9', 'classics'),
  ('https://open.spotify.com/track/70LcF31zb1H0PyJoS1Sx1r', '70LcF31zb1H0PyJoS1Sx1r', 'Creep', 'Radiohead', 'https://open.spotify.com/artist/4Z8W4fKeB5YxbusRsdQVPb', 'classics'),
  ('https://open.spotify.com/track/3d9DChrdc6BOeFsbrZ3Is0', '3d9DChrdc6BOeFsbrZ3Is0', 'Under the Bridge', 'Red Hot Chili Peppers', 'https://open.spotify.com/artist/0L8ExT028jH3ddEcZwqJJ5', 'classics'),
  ('https://open.spotify.com/track/7EsjkelQuoUlJXEw7SeVV4', '7EsjkelQuoUlJXEw7SeVV4', 'Black or White', 'Michael Jackson', 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm', 'classics'),
  ('https://open.spotify.com/track/4eHbdreAnSOrDDsFfc4Fpm', '4eHbdreAnSOrDDsFfc4Fpm', 'I Will Always Love You', 'Whitney Houston', 'https://open.spotify.com/artist/6XpaIBNiVzIetEPCWDvAFP', 'classics'),
  ('https://open.spotify.com/track/0GONea6G2XdnHWjNZd6zt3', '0GONea6G2XdnHWjNZd6zt3', 'Summer Of ''69', 'Bryan Adams', 'https://open.spotify.com/artist/3Z02hBLubJxuFJfhacLSDc', 'classics'),
  ('https://open.spotify.com/track/5Hk4Mpex0s2ndUpDQ5v2rU', '5Hk4Mpex0s2ndUpDQ5v2rU', 'Walk Of Life', 'Dire Straits', 'https://open.spotify.com/artist/0WwSkZ7LtFUFjGjMZBMt6T', 'classics'),
  ('https://open.spotify.com/track/4nFNJmjfgBF7jwv2oBC45b', '4nFNJmjfgBF7jwv2oBC45b', 'Money For Nothing', 'Dire Straits', 'https://open.spotify.com/artist/0WwSkZ7LtFUFjGjMZBMt6T', 'classics'),
  ('https://open.spotify.com/track/2sXp9Qmvc7mRaDBjBgcGGi', '2sXp9Qmvc7mRaDBjBgcGGi', 'Every Breath You Take', 'The Police', 'https://open.spotify.com/artist/5NGO30tJxFlKixkPSgXcFE', 'classics'),
  ('https://open.spotify.com/track/3EYOJ48Et32uATr9ZmLnAo', '3EYOJ48Et32uATr9ZmLnAo', 'Roxanne', 'The Police', 'https://open.spotify.com/artist/5NGO30tJxFlKixkPSgXcFE', 'classics'),
  ('https://open.spotify.com/track/0qi4b1l0eT3jpzeNHeFXDT', '0qi4b1l0eT3jpzeNHeFXDT', 'Just Can''t Get Enough', 'Depeche Mode', 'https://open.spotify.com/artist/762310PdDnwsDxAQxzQkfX', 'classics'),
  ('https://open.spotify.com/track/6W2VbtvMrDXm5vYeB7amkO', '6W2VbtvMrDXm5vYeB7amkO', 'Footloose', 'Kenny Loggins', 'https://open.spotify.com/artist/3Y3xIwWyq5wnNHPp5gPjOW', 'classics'),
  ('https://open.spotify.com/track/7N3PAbqfTjSEU1edb2tY8j', '7N3PAbqfTjSEU1edb2tY8j', 'Jump', 'Van Halen', 'https://open.spotify.com/artist/2cnMpRsOVqtPMfq7YiFE6K', 'classics'),
  ('https://open.spotify.com/track/0PdM2a6oIjqepoEfcJo0RO', '0PdM2a6oIjqepoEfcJo0RO', 'Pour Some Sugar On Me', 'Def Leppard', 'https://open.spotify.com/artist/6H1RjVyNruCmrBEWRbD0VZ', 'classics'),
  ('https://open.spotify.com/track/1qOU8KzFifXE9YrgjVwYvc', '1qOU8KzFifXE9YrgjVwYvc', 'Here I Go Again', 'Whitesnake', 'https://open.spotify.com/artist/3UbyYnvNIT5DFXU4WgiGpP', 'classics'),
  ('https://open.spotify.com/track/39shmbIHICJ2Wxnk1fPSdz', '39shmbIHICJ2Wxnk1fPSdz', 'Should I Stay or Should I Go', 'The Clash', 'https://open.spotify.com/artist/3RGLhK1IP9jnYFH4BRFJBS', 'classics'),
  ('https://open.spotify.com/track/7Jh1bpe76CNTCgdgAdBw4Z', '7Jh1bpe76CNTCgdgAdBw4Z', '"Heroes"', 'David Bowie', 'https://open.spotify.com/artist/0oSGxfWSnnOXhD2fKuz2Gy', 'classics'),
  ('https://open.spotify.com/track/3ix6K4wZY29bCujrSznwFZ', '3ix6K4wZY29bCujrSznwFZ', 'Let''s Dance', 'David Bowie', 'https://open.spotify.com/artist/0oSGxfWSnnOXhD2fKuz2Gy', 'classics'),
  ('https://open.spotify.com/track/3gdewACMIVMEWVbyb8O9sY', '3gdewACMIVMEWVbyb8O9sY', 'Rocket Man (I Think It''s Going To Be A Long, Long Time)', 'Elton John', 'https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b', 'classics'),
  ('https://open.spotify.com/track/38zsOOcu31XbbYj9BIPUF1', '38zsOOcu31XbbYj9BIPUF1', 'Your Song', 'Elton John', 'https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b', 'classics'),
  ('https://open.spotify.com/track/2TVxnKdb3tqe1nhQWwwZCO', '2TVxnKdb3tqe1nhQWwwZCO', 'Tiny Dancer', 'Elton John', 'https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b', 'classics'),
  ('https://open.spotify.com/track/1jDJFeK9x3OZboIAHsY9k2', '1jDJFeK9x3OZboIAHsY9k2', 'I''m Still Standing', 'Elton John', 'https://open.spotify.com/artist/3PhoLpVuITZKcymswpck5b', 'classics'),
  ('https://open.spotify.com/track/70C4NyhjD5OZUMzvWZ3njJ', '70C4NyhjD5OZUMzvWZ3njJ', 'Piano Man', 'Billy Joel', 'https://open.spotify.com/artist/6zFYqv1mOsgBRQbae3JJ9e', 'classics'),
  ('https://open.spotify.com/track/6hTcuIQa0sxrrByu9wTD7s', '6hTcuIQa0sxrrByu9wTD7s', 'Born to Run', 'Bruce Springsteen', 'https://open.spotify.com/artist/3eqjTLE0HfPfh78zjh6TqT', 'classics'),
  ('https://open.spotify.com/track/7FwBtcecmlpc1sLySPXeGE', '7FwBtcecmlpc1sLySPXeGE', 'Dancing In the Dark', 'Bruce Springsteen', 'https://open.spotify.com/artist/3eqjTLE0HfPfh78zjh6TqT', 'classics'),
  ('https://open.spotify.com/track/7e89621JPkKaeDSTQ3avtg', '7e89621JPkKaeDSTQ3avtg', 'Sweet Home Alabama', 'Lynyrd Skynyrd', 'https://open.spotify.com/artist/4MVyzYMgTwdP7Z49wAZHx0', 'classics'),
  ('https://open.spotify.com/track/07GvNcU1WdyZJq3XxP0kZa', '07GvNcU1WdyZJq3XxP0kZa', 'Go Your Own Way', 'Fleetwood Mac', 'https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X', 'classics'),
  ('https://open.spotify.com/track/0ofHAoxe9vBkTCp2UQIavz', '0ofHAoxe9vBkTCp2UQIavz', 'Dreams', 'Fleetwood Mac', 'https://open.spotify.com/artist/08GQAI4eElDnROBrJRGE0X', 'classics'),
  ('https://open.spotify.com/track/4v2rkl1mC3zVAz0nXMx9r4', '4v2rkl1mC3zVAz0nXMx9r4', 'Heart Of Glass', 'Blondie', 'https://open.spotify.com/artist/4tpUmLEVLCGFr93o8hFFIB', 'classics'),
  ('https://open.spotify.com/track/0vLwL4xuJ3s7SeaCdvMqkY', '0vLwL4xuJ3s7SeaCdvMqkY', 'Call Me', 'Blondie', 'https://open.spotify.com/artist/4tpUmLEVLCGFr93o8hFFIB', 'classics'),
  ('https://open.spotify.com/track/7pKfPomDEeI4TPT6EOYjn9', '7pKfPomDEeI4TPT6EOYjn9', 'Imagine', 'John Lennon', 'https://open.spotify.com/artist/4x1nvY2FN8jxqAFA0DA02H', 'classics'),
  ('https://open.spotify.com/track/5SAUIWdZ04OxYfJFDchC7S', '5SAUIWdZ04OxYfJFDchC7S', 'Smoke on the Water', 'Deep Purple', 'https://open.spotify.com/artist/568ZhdwyaiCyOGJRtNYhWf', 'classics'),
  ('https://open.spotify.com/track/62AuGbAkt8Ox2IrFFb8GKV', '62AuGbAkt8Ox2IrFFb8GKV', 'Sweet Caroline', 'Neil Diamond', 'https://open.spotify.com/artist/7mEIug7XUlQHikrFxjTWes', 'classics'),
  ('https://open.spotify.com/track/7jmHyHMEqm9MJWiMAneF05', '7jmHyHMEqm9MJWiMAneF05', 'Stand By Me', 'Ben E. King', 'https://open.spotify.com/artist/3plJVWt88EqjvtuB4ZDRV3', 'classics'),
  ('https://open.spotify.com/track/4gphxUgq0JSFv2BCLhNDiE', '4gphxUgq0JSFv2BCLhNDiE', 'Jailhouse Rock', 'Elvis Presley', 'https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE', 'classics'),
  ('https://open.spotify.com/track/44AyOl4qVkzS48vBsbNXaC', '44AyOl4qVkzS48vBsbNXaC', 'Can''t Help Falling in Love', 'Elvis Presley', 'https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE', 'classics'),
  ('https://open.spotify.com/track/1H5IfYyIIAlgDX8zguUzns', '1H5IfYyIIAlgDX8zguUzns', 'Suspicious Minds', 'Elvis Presley', 'https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE', 'classics'),
  ('https://open.spotify.com/track/745H5CctFr12Mo7cqa1BMH', '745H5CctFr12Mo7cqa1BMH', 'My Girl', 'The Temptations', 'https://open.spotify.com/artist/3RwQ26hR2tJtA8F9p2n7jG', 'classics'),
  ('https://open.spotify.com/track/7tqhbajSfrz2F7E1Z75ASX', '7tqhbajSfrz2F7E1Z75ASX', 'Ain''t No Mountain High Enough', 'Marvin Gaye, Tammi Terrell', 'https://open.spotify.com/artist/3koiLjNrgRTNbOwViDipeA', 'classics'),
  ('https://open.spotify.com/track/1tqT6DhmsrtQgyCKUwotiw', '1tqT6DhmsrtQgyCKUwotiw', 'I Heard It Through The Grapevine', 'Marvin Gaye', 'https://open.spotify.com/artist/3koiLjNrgRTNbOwViDipeA', 'classics'),
  ('https://open.spotify.com/track/6pxWv6GV35VGmcPf5dh6CH', '6pxWv6GV35VGmcPf5dh6CH', 'Proud Mary', 'Creedence Clearwater Revival', 'https://open.spotify.com/artist/3IYUhFvPQItj6xySrBmZkd', 'classics'),
  ('https://open.spotify.com/track/5t9KYe0Fhd5cW6UYT4qP8f', '5t9KYe0Fhd5cW6UYT4qP8f', 'Good Vibrations', 'The Beach Boys', 'https://open.spotify.com/artist/3oDbviiivRWhXwIE8hxkVV', 'classics'),
  ('https://open.spotify.com/track/4IHc6SzGPnzSPuHVEPzpJc', '4IHc6SzGPnzSPuHVEPzpJc', 'Wouldn''t It Be Nice', 'The Beach Boys', 'https://open.spotify.com/artist/3oDbviiivRWhXwIE8hxkVV', 'classics'),
  ('https://open.spotify.com/track/7BY005dacJkbO6EPiOh2wb', '7BY005dacJkbO6EPiOh2wb', 'House Of The Rising Sun', 'The Animals', 'https://open.spotify.com/artist/3ICflSq6ZgYAIrm2CTkfVP', 'classics'),
  ('https://open.spotify.com/track/0iOZM63lendWRTTeKhZBSC', '0iOZM63lendWRTTeKhZBSC', 'Mrs. Robinson', 'Simon & Garfunkel', 'https://open.spotify.com/artist/70cRZdQywnSFp9pnc2WTCE', 'classics'),
  ('https://open.spotify.com/track/48i055G1OT5KxGGftwFxWy', '48i055G1OT5KxGGftwFxWy', 'Oh, Pretty Woman', 'Roy Orbison', 'https://open.spotify.com/artist/0JDkhL4rjiPNEp92jAgJnS', 'classics'),
  ('https://open.spotify.com/track/46eu3SBuFCXWsPT39Yg3tJ', '46eu3SBuFCXWsPT39Yg3tJ', 'Don''t Stop ''Til You Get Enough', 'Michael Jackson', 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm', 'classics'),
  ('https://open.spotify.com/track/7wuJGgpTNzbUyn26IOY6rj', '7wuJGgpTNzbUyn26IOY6rj', 'Total Eclipse of the Heart', 'Bonnie Tyler', 'https://open.spotify.com/artist/0SD4eZCN4Kr0wQk56hCdh2', 'classics'),
  ('https://open.spotify.com/track/62LJFaYihsdVrrkgUOJC05', '62LJFaYihsdVrrkgUOJC05', 'Kiss', 'Prince', 'https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j', 'classics'),
  ('https://open.spotify.com/track/54X78diSLoUDI3joC2bjMz', '54X78diSLoUDI3joC2bjMz', 'Purple Rain', 'Prince', 'https://open.spotify.com/artist/5a2EaR3hamoenG9rDuVn8j', 'classics'),
  ('https://open.spotify.com/track/3ovjw5HZZv43SxTwApooCM', '3ovjw5HZZv43SxTwApooCM', 'Wind Of Change', 'Scorpions', 'https://open.spotify.com/artist/27T030eWyCQRmDyuvr1kxY', 'classics'),
  ('https://open.spotify.com/track/6QAsrXPnMSXIbV0yEJHlEX', '6QAsrXPnMSXIbV0yEJHlEX', 'Nothing Else Matters', 'Metallica', 'https://open.spotify.com/artist/2ye2Wgw4gimLv2eAKyk1NB', 'classics'),
  ('https://open.spotify.com/track/3YRCqOhFifThpSRFJ1VWFM', '3YRCqOhFifThpSRFJ1VWFM', 'November Rain', 'Guns N'' Roses', 'https://open.spotify.com/artist/3qm84nBOXUEQ2vnTfUTTFC', 'classics'),
  ('https://open.spotify.com/track/39lSeqnyjZJejRuaREfyLL', '39lSeqnyjZJejRuaREfyLL', 'Hungry Like the Wolf', 'Duran Duran', 'https://open.spotify.com/artist/0lZoBs4Pzo7R89JM9lxwoT', 'classics'),
  ('https://open.spotify.com/track/3Dy4REq8O09IlgiwuHQ3sk', '3Dy4REq8O09IlgiwuHQ3sk', 'Waterloo', 'ABBA', 'https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV', 'classics'),
  ('https://open.spotify.com/track/2TxCwUlqaOH3TIyJqGgR91', '2TxCwUlqaOH3TIyJqGgR91', 'Mamma Mia', 'ABBA', 'https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV', 'classics'),
  ('https://open.spotify.com/track/3vkQ5DAB1qQMYO4Mr9zJN6', '3vkQ5DAB1qQMYO4Mr9zJN6', 'Gimme! Gimme! Gimme! (A Man After Midnight)', 'ABBA', 'https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV', 'classics'),
  ('https://open.spotify.com/track/5BckPAYcKEJuYs1eV1BHHe', '5BckPAYcKEJuYs1eV1BHHe', 'Take A Chance On Me', 'ABBA', 'https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV', 'classics'),
  ('https://open.spotify.com/track/0J2p4KYdr6Mg4ET6JPlbe1', '0J2p4KYdr6Mg4ET6JPlbe1', 'Super Trouper', 'ABBA', 'https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV', 'classics'),
  ('https://open.spotify.com/track/3oEkrIfXfSh9zGnE7eBzSV', '3oEkrIfXfSh9zGnE7eBzSV', 'The Winner Takes It All', 'ABBA', 'https://open.spotify.com/artist/0LcJLqbBmaGUft1e9Mm8HV', 'classics'),
  ('https://open.spotify.com/track/1aYkkrAbPmMuorVz5HWIqE', '1aYkkrAbPmMuorVz5HWIqE', 'The Look', 'Roxette', 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY', 'classics'),
  ('https://open.spotify.com/track/6kvoHl80mfCVTv7XnZkjQn', '6kvoHl80mfCVTv7XnZkjQn', 'It Must Have Been Love', 'Roxette', 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY', 'classics'),
  ('https://open.spotify.com/track/2MaBAGBIttgv86bYytdx1f', '2MaBAGBIttgv86bYytdx1f', 'Listen To Your Heart', 'Roxette', 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY', 'classics'),
  ('https://open.spotify.com/track/0RaEqkxeaUFwNhvcD9pAit', '0RaEqkxeaUFwNhvcD9pAit', 'Joyride', 'Roxette', 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY', 'classics'),
  ('https://open.spotify.com/track/09dB7Wv84s7uY40YbbeqG0', '09dB7Wv84s7uY40YbbeqG0', 'Dressed For Success', 'Roxette', 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY', 'classics'),
  ('https://open.spotify.com/track/6ddWHN54KXzPbZxn4avx7l', '6ddWHN54KXzPbZxn4avx7l', 'Fading Like A Flower (Every Time You Leave)', 'Roxette', 'https://open.spotify.com/artist/2SHhfs4BiDxGQ3oxqf0UHY', 'classics'),
  ('https://open.spotify.com/track/3MrRksHupTVEQ7YbA0FsZK', '3MrRksHupTVEQ7YbA0FsZK', 'The Final Countdown', 'Europe', 'https://open.spotify.com/artist/7Js6Lde8thlIHXggv2SCBz', 'classics'),
  ('https://open.spotify.com/track/29wJiSQcze8HEmxkUQykyp', '29wJiSQcze8HEmxkUQykyp', 'Carrie', 'Europe', 'https://open.spotify.com/artist/7Js6Lde8thlIHXggv2SCBz', 'classics'),
  ('https://open.spotify.com/track/6kWJvPfC4DgUpRsXKNa9z9', '6kWJvPfC4DgUpRsXKNa9z9', 'All That She Wants', 'Ace of Base', 'https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm', 'classics'),
  ('https://open.spotify.com/track/0hrBpAOgrt8RXigk83LLNE', '0hrBpAOgrt8RXigk83LLNE', 'The Sign', 'Ace of Base', 'https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm', 'classics'),
  ('https://open.spotify.com/track/7yCF65vpc7sUwPjftI0iFb', '7yCF65vpc7sUwPjftI0iFb', 'Happy Nation', 'Ace of Base', 'https://open.spotify.com/artist/5ksRONqssB7BR161NTtJAm', 'classics'),
  ('https://open.spotify.com/track/1BBIW3lDfwK9PXOFOedZmo', '1BBIW3lDfwK9PXOFOedZmo', 'This Is The Way', 'E-Type', 'https://open.spotify.com/artist/53I4RAzuXWvaO1vzrCBJbD', 'classics'),
  ('https://open.spotify.com/track/67rBycpa8FTFJkQwP5FzP1', '67rBycpa8FTFJkQwP5FzP1', 'Set The World On Fire', 'E-Type', 'https://open.spotify.com/artist/53I4RAzuXWvaO1vzrCBJbD', 'classics'),
  ('https://open.spotify.com/track/7aQjPecQdIuNd1sz3KCDhD', '7aQjPecQdIuNd1sz3KCDhD', 'Lovefool', 'The Cardigans', 'https://open.spotify.com/artist/1tqZaCwM57UFKjWoYwMLrw', 'classics'),
  ('https://open.spotify.com/track/0Ui05Ov0s4PnRc4JI3Pilg', '0Ui05Ov0s4PnRc4JI3Pilg', 'My Favourite Game', 'The Cardigans', 'https://open.spotify.com/artist/1tqZaCwM57UFKjWoYwMLrw', 'classics'),
  ('https://open.spotify.com/track/6SluaPiV04KOaRTOIScoff', '6SluaPiV04KOaRTOIScoff', 'Show Me Love', 'Robyn', 'https://open.spotify.com/artist/6UE7nl9mha6s8z0wFQFIZ2', 'classics'),
  ('https://open.spotify.com/track/6mwzXxkU8SLbIcOCqCVuOg', '6mwzXxkU8SLbIcOCqCVuOg', 'Kräm (så nära får ingen gå)', 'kent', 'https://open.spotify.com/artist/4KXp3xtaz1wWXnu5u34eVX', 'classics'),
  ('https://open.spotify.com/track/1d1BeKPNgaQ36wcxGqnfU3', '1d1BeKPNgaQ36wcxGqnfU3', 'Sommartider', 'Gyllene Tider', 'https://open.spotify.com/artist/0FINyNBXqnTlRC4dvpSeSb', 'classics'),
  ('https://open.spotify.com/track/2EKzS2s2VKnbQ7jxyk2WHi', '2EKzS2s2VKnbQ7jxyk2WHi', 'När vi två blir en', 'Gyllene Tider', 'https://open.spotify.com/artist/0FINyNBXqnTlRC4dvpSeSb', 'classics'),
  ('https://open.spotify.com/track/0lwJH1BDr8Z4wfXvi6yC9y', '0lwJH1BDr8Z4wfXvi6yC9y', 'Sol, vind och vatten', 'Ted Gärdestad', 'https://open.spotify.com/artist/6zpub6jbY6CdrcqQsDq8P4', 'classics'),
  ('https://open.spotify.com/track/2S8BQdQgN3sCA0uI0A3gXw', '2S8BQdQgN3sCA0uI0A3gXw', 'Främling', 'Carola', 'https://open.spotify.com/artist/3uFum0NCM1PtmCO0MwsOAt', 'classics'),
  ('https://open.spotify.com/track/4NzirQ4BrNkVaPEla2ipG4', '4NzirQ4BrNkVaPEla2ipG4', 'Diggiloo Diggiley', 'Herreys', 'https://open.spotify.com/artist/2uS8ryCr9KuXzh7Y4xowle', 'classics'),
  ('https://open.spotify.com/track/2W7tzqjAPXG97RthXx6pNR', '2W7tzqjAPXG97RthXx6pNR', 'Sommaren är kort', 'Tomas Ledin', 'https://open.spotify.com/artist/518rTAIFPwQjLUSi4Pdzzn', 'classics'),
  ('https://open.spotify.com/track/4dIgnM4reWYpeJlU5Z0cej', '4dIgnM4reWYpeJlU5Z0cej', 'Himlen runt hörnet', 'Lisa Nilsson', 'https://open.spotify.com/artist/68QvqbdqwqqjW39YpUJHdG', 'classics'),
  ('https://open.spotify.com/track/1ecJdAizaDklfgCVtEUQsG', '1ecJdAizaDklfgCVtEUQsG', 'Vill ha dig', 'Freestyle', 'https://open.spotify.com/artist/7fGejcqwbdfn47UP7NcdUt', 'classics'),
  ('https://open.spotify.com/track/4uBbgoKiRzcjgjVH6FqgTS', '4uBbgoKiRzcjgjVH6FqgTS', 'Sarah', 'Mauro Scocco', 'https://open.spotify.com/artist/0qC4DawW3xCirhuq5cvaKV', 'classics'),
  ('https://open.spotify.com/track/7E9rcVjE66zO7p4IwyhjBC', '7E9rcVjE66zO7p4IwyhjBC', 'Under ytan', 'Uno Svenningsson', 'https://open.spotify.com/artist/65OPXmm2nfPvaX1fjHo8kR', 'classics'),
  ('https://open.spotify.com/track/0Z6y9qCkkfESLiEOuBWhAZ', '0Z6y9qCkkfESLiEOuBWhAZ', 'Take Me to Your Heaven', 'Charlotte Perrelli', 'https://open.spotify.com/artist/39Waq6UmqYCBEuyv8M8kjl', 'classics'),
  ('https://open.spotify.com/track/7bVwUOySQGO2afJ0LArAMi', '7bVwUOySQGO2afJ0LArAMi', 'Stad i ljus', 'Tommy Körberg', 'https://open.spotify.com/artist/6R21HSNyo7HVac8pyqY3T2', 'classics')
on conflict (spotify_url) do nothing;
