export type TriviaCategory =
  | "Mat"
  | "Film"
  | "Geografi"
  | "Historia"
  | "Sport"
  | "Vetenskap"
  | "Musik"
  | "Natur";

export type TriviaQuestion = {
  id: string;
  category: TriviaCategory;
  /** Swedish prompt. Also stored in `trivia_turns.question_text`, so never change existing values. */
  prompt: string;
  /** Swedish answer. Also stored in `trivia_turns.answer_text`. */
  answer: string;
  promptEn: string;
  answerEn: string;
};

export type TriviaLanguage = "en" | "sv";

const TRIVIA_CATEGORY_LABELS_EN: Record<TriviaCategory, string> = {
  Mat: "Food",
  Film: "Movies",
  Geografi: "Geography",
  Historia: "History",
  Sport: "Sport",
  Vetenskap: "Science",
  Musik: "Music",
  Natur: "Nature",
};

/** Display label for a stored category value (the stored value itself is the Swedish label). */
export function triviaCategoryLabel(category: string, language: TriviaLanguage): string {
  if (language === "en") {
    return TRIVIA_CATEGORY_LABELS_EN[category as TriviaCategory] ?? category;
  }
  return category;
}

export const TRIVIA_CATEGORIES: TriviaCategory[] = [
  "Mat",
  "Film",
  "Geografi",
  "Historia",
  "Sport",
  "Vetenskap",
  "Musik",
  "Natur",
];

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { id: "mat-1", category: "Mat", prompt: "Vilket land är ursprunget till pizza margherita?", answer: "Italien", promptEn: "Which country is pizza margherita originally from?", answerEn: "Italy" },
  { id: "mat-2", category: "Mat", prompt: "Vad heter den japanska rätten med vinägerat ris och ofta fisk?", answer: "Sushi", promptEn: "What is the Japanese dish of vinegared rice, often served with fish, called?", answerEn: "Sushi" },
  { id: "mat-3", category: "Mat", prompt: "Vilken frukt är huvudingrediensen i guacamole?", answer: "Avokado", promptEn: "Which fruit is the main ingredient in guacamole?", answerEn: "Avocado" },
  { id: "mat-4", category: "Mat", prompt: "Vad kallas en fransk tunn pannkaka?", answer: "Crêpe", promptEn: "What is a thin French pancake called?", answerEn: "Crêpe" },
  { id: "mat-5", category: "Mat", prompt: "Vilken ost används ofta på grekisk sallad?", answer: "Fetaost", promptEn: "Which cheese is often used in a Greek salad?", answerEn: "Feta" },
  { id: "mat-6", category: "Mat", prompt: "Vilken dryck gör man oftast av malt, humle, jäst och vatten?", answer: "Öl", promptEn: "Which drink is usually made from malt, hops, yeast and water?", answerEn: "Beer" },
  { id: "mat-7", category: "Mat", prompt: "Vad heter den italienska efterrätten med kaffe och mascarpone?", answer: "Tiramisu", promptEn: "What is the Italian dessert made with coffee and mascarpone called?", answerEn: "Tiramisu" },
  { id: "mat-8", category: "Mat", prompt: "Vilken krydda ger gul färg till mycket curry och risrätter?", answer: "Gurkmeja", promptEn: "Which spice gives a yellow colour to many curries and rice dishes?", answerEn: "Turmeric" },
  { id: "mat-9", category: "Mat", prompt: "Vilken sås är huvudingrediens i klassisk eggs benedict tillsammans med pocherat ägg?", answer: "Hollandaisesås", promptEn: "Which sauce is a key ingredient in classic eggs Benedict, together with poached eggs?", answerEn: "Hollandaise sauce" },
  { id: "mat-10", category: "Mat", prompt: "Vad heter den spanska risrätten som ofta innehåller saffran och skaldjur?", answer: "Paella", promptEn: "What is the Spanish rice dish that often contains saffron and seafood called?", answerEn: "Paella" },
  { id: "mat-11", category: "Mat", prompt: "Vilken nöt används traditionellt för att göra pesto alla genovese?", answer: "Pinjenöt", promptEn: "Which nut is traditionally used to make pesto alla genovese?", answerEn: "Pine nut" },
  { id: "mat-12", category: "Mat", prompt: "Vilket land förknippas starkast med rätten gulasch?", answer: "Ungern", promptEn: "Which country is most strongly associated with the dish goulash?", answerEn: "Hungary" },
  { id: "mat-13", category: "Mat", prompt: "Vad heter den koreanska fermenterade kål-rätten som ofta serveras som tillbehör?", answer: "Kimchi", promptEn: "What is the Korean fermented cabbage dish, often served as a side, called?", answerEn: "Kimchi" },
  { id: "mat-14", category: "Mat", prompt: "Vilken fiskrom används traditionellt i rysk kaviar från stör?", answer: "Störrom", promptEn: "Traditional Russian caviar is the roe of which fish?", answerEn: "Sturgeon roe" },
  { id: "mat-15", category: "Mat", prompt: "Vad kallas den franska matlagningstermen när man tillagar i vakuum vid låg temperatur?", answer: "Sous vide", promptEn: "What is the French cooking term for cooking food vacuum-sealed at a low temperature?", answerEn: "Sous vide" },
  { id: "mat-16", category: "Mat", prompt: "Vilken typ av deg används traditionellt till italiensk focaccia?", answer: "Jästdeg", promptEn: "What type of dough is traditionally used for Italian focaccia?", answerEn: "Yeast dough" },
  { id: "mat-17", category: "Mat", prompt: "Vilket mjöl används oftast till polenta?", answer: "Majsmjöl", promptEn: "Which flour is most often used to make polenta?", answerEn: "Cornmeal" },
  { id: "mat-18", category: "Mat", prompt: "Vad heter den japanska nudelsoppan med misobuljong som ofta serveras med fläsk?", answer: "Ramen", promptEn: "What is the Japanese noodle soup, often with miso broth and served with pork, called?", answerEn: "Ramen" },
  { id: "mat-19", category: "Mat", prompt: "Vilken fransk moder-sås bygger på mjölk, smör och vetemjöl?", answer: "Béchamelsås", promptEn: "Which French mother sauce is based on milk, butter and wheat flour?", answerEn: "Béchamel sauce" },
  { id: "mat-20", category: "Mat", prompt: "Vad heter den indiska ugnen som används för naan och tandoorirätter?", answer: "Tandoor", promptEn: "What is the Indian oven used for naan and tandoori dishes called?", answerEn: "Tandoor" },
  { id: "mat-21", category: "Mat", prompt: "Vilken citrusfrukt används ofta i key lime pie?", answer: "Lime", promptEn: "Which citrus fruit is used in key lime pie?", answerEn: "Lime" },
  { id: "mat-22", category: "Mat", prompt: "Vad heter den mexikanska rätten där tortilla ofta fylls och rullas ihop?", answer: "Burrito", promptEn: "What is the Mexican dish where a tortilla is filled and rolled up called?", answerEn: "Burrito" },
  { id: "mat-23", category: "Mat", prompt: "Vilken ost används traditionellt i italiensk risotto alla milanese tillsammans med saffran?", answer: "Parmesan", promptEn: "Which cheese is traditionally used in Italian risotto alla milanese, together with saffron?", answerEn: "Parmesan" },
  { id: "mat-24", category: "Mat", prompt: "Vad kallas det när man snabbt kokar grönsaker och sedan kyler dem i isvatten?", answer: "Blanchera", promptEn: "What is it called when you briefly boil vegetables and then cool them in ice water?", answerEn: "Blanching" },
  { id: "mat-25", category: "Mat", prompt: "Vilket bär används i en klassisk svensk drottningsylt tillsammans med blåbär?", answer: "Hallon", promptEn: "Which berry is combined with blueberries in the classic Swedish \"queen's jam\" (drottningsylt)?", answerEn: "Raspberry" },
  { id: "mat-26", category: "Mat", prompt: "Vad heter den italienska lufttorkade skinkan från Parma?", answer: "Prosciutto", promptEn: "What is the Italian air-dried ham from Parma called?", answerEn: "Prosciutto" },
  { id: "mat-27", category: "Mat", prompt: "Vilken baljväxt är huvudingrediens i hummus?", answer: "Kikärta", promptEn: "Which legume is the main ingredient in hummus?", answerEn: "Chickpea" },
  { id: "mat-28", category: "Mat", prompt: "Vilken delikatess framställs av gås- eller anklever?", answer: "Foie gras", promptEn: "Which delicacy is made from goose or duck liver?", answerEn: "Foie gras" },
  { id: "mat-29", category: "Mat", prompt: "Vad heter den tunna japanska nudeln gjord på bovete?", answer: "Soba", promptEn: "What are the thin Japanese noodles made from buckwheat called?", answerEn: "Soba" },
  { id: "mat-30", category: "Mat", prompt: "Vilken dessert består av maräng, grädde och ofta bär eller frukt?", answer: "Pavlova", promptEn: "Which dessert consists of meringue, cream and often berries or fruit?", answerEn: "Pavlova" },
  { id: "mat-31", category: "Mat", prompt: "Vilken rotfrukt används för att göra chips med smaken salt and vinegar om de är gjorda på grönsak i stället för potatis?", answer: "Palsternacka", promptEn: "Which root vegetable can be used instead of potato to make salt and vinegar crisps?", answerEn: "Parsnip" },
  { id: "mat-32", category: "Mat", prompt: "Vad heter den marockanska grytan som också gett namn åt kokkärlet?", answer: "Tagine", promptEn: "What is the Moroccan stew that also gave its name to the pot it is cooked in?", answerEn: "Tagine" },
  { id: "mat-33", category: "Mat", prompt: "Vilken typ av vin används oftast i rätten coq au vin?", answer: "Rödvin", promptEn: "What type of wine is most often used in the dish coq au vin?", answerEn: "Red wine" },
  { id: "mat-34", category: "Mat", prompt: "Vad heter den spanska kallserverade tomatsoppan?", answer: "Gazpacho", promptEn: "What is the Spanish tomato soup served cold called?", answerEn: "Gazpacho" },
  { id: "mat-35", category: "Mat", prompt: "Vilken nöt dominerar i nougat enligt medelhavstradition?", answer: "Hasselnöt", promptEn: "Which nut dominates in nougat according to Mediterranean tradition?", answerEn: "Hazelnut" },
  { id: "mat-36", category: "Mat", prompt: "Vad heter den franska potatisgratängen som tillagas med grädde och vitlök?", answer: "Gratin dauphinois", promptEn: "What is the French potato gratin cooked with cream and garlic called?", answerEn: "Gratin dauphinois" },
  { id: "mat-37", category: "Mat", prompt: "Vilken fransk kaka görs traditionellt upp och ned med karamelliserade äpplen?", answer: "Tarte tatin", promptEn: "Which French tart is traditionally made upside down with caramelised apples?", answerEn: "Tarte Tatin" },
  { id: "mat-38", category: "Mat", prompt: "Vad heter den kinesiska kryddblandningen som ofta innehåller stjärnanis, kanel och nejlika?", answer: "Five spice", promptEn: "What is the Chinese spice blend that often contains star anise, cinnamon and cloves called?", answerEn: "Five spice" },
  { id: "mat-39", category: "Mat", prompt: "Vilken ostmassa används som bas i indisk paneer?", answer: "Färskost", promptEn: "What kind of cheese is Indian paneer?", answerEn: "Fresh cheese" },
  { id: "mat-40", category: "Mat", prompt: "Vilken svamp anses särskilt exklusiv och växer ofta under jord nära trädens rötter?", answer: "Tryffel", promptEn: "Which fungus is considered especially exclusive and often grows underground near tree roots?", answerEn: "Truffle" },
  { id: "mat-41", category: "Mat", prompt: "Vad heter den tunna italienska efterrättskakan som betyder ungefär 'dubbelt kokt'?", answer: "Biscotti", promptEn: "What are the crunchy Italian biscuits whose name roughly means \"twice cooked\" called?", answerEn: "Biscotti" },
  { id: "mat-42", category: "Mat", prompt: "Vilket asiatiskt land är ursprunget till rätten pho?", answer: "Vietnam", promptEn: "Which Asian country does the dish pho come from?", answerEn: "Vietnam" },
  { id: "mat-43", category: "Mat", prompt: "Vilken ört ger bearnaisesås sin tydliga klassiska smak?", answer: "Dragon", promptEn: "Which herb gives béarnaise sauce its distinctive classic flavour?", answerEn: "Tarragon" },
  { id: "mat-44", category: "Mat", prompt: "Vad heter den spanska lufttorkade skinkan från svartfotssvin som räknas som extra exklusiv?", answer: "Jamón ibérico", promptEn: "What is the Spanish air-dried ham from black-footed pigs, considered extra exclusive, called?", answerEn: "Jamón ibérico" },
  { id: "mat-45", category: "Mat", prompt: "Vilken ost används oftast i en klassisk caprese tillsammans med tomat och basilika?", answer: "Mozzarella", promptEn: "Which cheese is most often used in a classic caprese with tomato and basil?", answerEn: "Mozzarella" },
  { id: "mat-46", category: "Mat", prompt: "Vad kallas de små italienska potatisdumplingarna?", answer: "Gnocchi", promptEn: "What are the small Italian potato dumplings called?", answerEn: "Gnocchi" },
  { id: "mat-47", category: "Mat", prompt: "Vilken ingrediens ger ceviche dess tillagade känsla utan värme?", answer: "Citrusjuice", promptEn: "Which ingredient \"cooks\" ceviche without any heat?", answerEn: "Citrus juice" },
  { id: "mat-48", category: "Mat", prompt: "Vad heter den japanska friteringsmetoden med lätt, frasigt frityrsmet?", answer: "Tempura", promptEn: "What is the Japanese deep-frying method with a light, crispy batter called?", answerEn: "Tempura" },
  { id: "mat-49", category: "Mat", prompt: "Vilken del av vaniljväxten används som krydda i matlagning och bakning?", answer: "Vaniljstång", promptEn: "Which part of the vanilla plant is used as a spice in cooking and baking?", answerEn: "Vanilla pod" },
  { id: "mat-50", category: "Mat", prompt: "Vad kallas den franska matlagningstermer för 'allt på plats' innan tillagning?", answer: "Mise en place", promptEn: "What is the French cooking term for \"everything in its place\" before you start cooking?", answerEn: "Mise en place" },

  { id: "film-1", category: "Film", prompt: "Vilken filmserie handlar om trollkarlen Harry Potter?", answer: "Harry Potter", promptEn: "Which film series is about the wizard Harry Potter?", answerEn: "Harry Potter" },
  { id: "film-2", category: "Film", prompt: "Vad heter lejonungen i Disneys The Lion King?", answer: "Simba", promptEn: "What is the lion cub called in Disney's The Lion King?", answerEn: "Simba" },
  { id: "film-3", category: "Film", prompt: "Vilken film har repliken 'I'll be back'?", answer: "The Terminator", promptEn: "Which film has the line \"I'll be back\"?", answerEn: "The Terminator" },
  { id: "film-4", category: "Film", prompt: "Vilken film vann Oscar för bästa film 1998 och handlar om ett stort skepp?", answer: "Titanic", promptEn: "Which film about a huge ship won the Oscar for Best Picture in 1998?", answerEn: "Titanic" },
  { id: "film-5", category: "Film", prompt: "Vad heter clownfisken i Hitta Nemo?", answer: "Nemo", promptEn: "What is the clownfish called in Finding Nemo?", answerEn: "Nemo" },
  { id: "film-6", category: "Film", prompt: "Vilken superhjälte är alter egot till Bruce Wayne?", answer: "Batman", promptEn: "Which superhero is the alter ego of Bruce Wayne?", answerEn: "Batman" },
  { id: "film-7", category: "Film", prompt: "I vilken science fiction-film är Darth Vader en central figur?", answer: "Star Wars", promptEn: "In which science fiction film is Darth Vader a central character?", answerEn: "Star Wars" },
  { id: "film-8", category: "Film", prompt: "Vad heter ogret i DreamWorks filmserie med samma namn?", answer: "Shrek", promptEn: "What is the ogre called in the DreamWorks film series of the same name?", answerEn: "Shrek" },
  { id: "film-9", category: "Film", prompt: "Vem regisserade filmen Inception?", answer: "Christopher Nolan", promptEn: "Who directed the film Inception?", answerEn: "Christopher Nolan" },
  { id: "film-10", category: "Film", prompt: "Vilken film från 1999 handlar om Neo, Morpheus och en simulerad verklighet?", answer: "The Matrix", promptEn: "Which 1999 film is about Neo, Morpheus and a simulated reality?", answerEn: "The Matrix" },
  { id: "film-11", category: "Film", prompt: "Vad heter ringenas skapare i Sagan om ringen-universumet?", answer: "Sauron", promptEn: "Who forged the One Ring in The Lord of the Rings universe?", answerEn: "Sauron" },
  { id: "film-12", category: "Film", prompt: "Vilken skådespelare spelade Jokern i The Dark Knight?", answer: "Heath Ledger", promptEn: "Which actor played the Joker in The Dark Knight?", answerEn: "Heath Ledger" },
  { id: "film-13", category: "Film", prompt: "Vilken film av Bong Joon-ho vann Oscar för bästa film 2020?", answer: "Parasite", promptEn: "Which Bong Joon-ho film won the Oscar for Best Picture in 2020?", answerEn: "Parasite" },
  { id: "film-14", category: "Film", prompt: "Vad heter hotellet i Stanley Kubricks The Shining?", answer: "Overlook Hotel", promptEn: "What is the hotel called in Stanley Kubrick's The Shining?", answerEn: "Overlook Hotel" },
  { id: "film-15", category: "Film", prompt: "Vilken regissör ligger bakom Pulp Fiction?", answer: "Quentin Tarantino", promptEn: "Which director is behind Pulp Fiction?", answerEn: "Quentin Tarantino" },
  { id: "film-16", category: "Film", prompt: "Vad heter huvudpersonen som spelas av Russell Crowe i Gladiator?", answer: "Maximus", promptEn: "What is the name of the main character played by Russell Crowe in Gladiator?", answerEn: "Maximus" },
  { id: "film-17", category: "Film", prompt: "Vilken film har figurerna Woody och Buzz Lightyear?", answer: "Toy Story", promptEn: "Which film features the characters Woody and Buzz Lightyear?", answerEn: "Toy Story" },
  { id: "film-18", category: "Film", prompt: "Vilken svensk skådespelare spelade It i filmerna baserade på Stephen Kings bok?", answer: "Bill Skarsgård", promptEn: "Which Swedish actor played It in the films based on Stephen King's novel?", answerEn: "Bill Skarsgård" },
  { id: "film-19", category: "Film", prompt: "Vilken film vann första Oscarsstatyetten för bästa animerade långfilm 2002?", answer: "Shrek", promptEn: "Which film won the first ever Oscar for Best Animated Feature in 2002?", answerEn: "Shrek" },
  { id: "film-20", category: "Film", prompt: "Vad heter månen där mycket av handlingen i Avatar utspelar sig?", answer: "Pandora", promptEn: "What is the name of the moon where much of Avatar takes place?", answerEn: "Pandora" },
  { id: "film-21", category: "Film", prompt: "Vilken film av Steven Spielberg handlar om en haj som terroriserar en badort?", answer: "Hajen", promptEn: "Which Steven Spielberg film is about a shark terrorising a beach town?", answerEn: "Jaws" },
  { id: "film-22", category: "Film", prompt: "Vad heter den kvinnliga huvudrollen i Pretty Woman?", answer: "Vivian", promptEn: "What is the name of the female lead in Pretty Woman?", answerEn: "Vivian" },
  { id: "film-23", category: "Film", prompt: "Vilken filmserie innehåller figuren Ethan Hunt?", answer: "Mission: Impossible", promptEn: "Which film series features the character Ethan Hunt?", answerEn: "Mission: Impossible" },
  { id: "film-24", category: "Film", prompt: "Vem regisserade E.T. the Extra-Terrestrial?", answer: "Steven Spielberg", promptEn: "Who directed E.T. the Extra-Terrestrial?", answerEn: "Steven Spielberg" },
  { id: "film-25", category: "Film", prompt: "Vad heter den fiktiva afrikanska nationen i Black Panther?", answer: "Wakanda", promptEn: "What is the fictional African nation in Black Panther called?", answerEn: "Wakanda" },
  { id: "film-26", category: "Film", prompt: "Vilken film från 1994 handlar om Andy Dufresne i ett fängelse?", answer: "Nyckeln till frihet", promptEn: "Which 1994 film is about Andy Dufresne in a prison?", answerEn: "The Shawshank Redemption" },
  { id: "film-27", category: "Film", prompt: "Vad heter regissören bakom Pans labyrint och The Shape of Water?", answer: "Guillermo del Toro", promptEn: "Who is the director behind Pan's Labyrinth and The Shape of Water?", answerEn: "Guillermo del Toro" },
  { id: "film-28", category: "Film", prompt: "Vilken film har figuren Jack Sparrow?", answer: "Pirates of the Caribbean", promptEn: "Which film features the character Jack Sparrow?", answerEn: "Pirates of the Caribbean" },
  { id: "film-29", category: "Film", prompt: "Vilken skådespelare spelade huvudrollen i filmen Forrest Gump?", answer: "Tom Hanks", promptEn: "Which actor played the lead role in Forrest Gump?", answerEn: "Tom Hanks" },
  { id: "film-30", category: "Film", prompt: "Vad heter den koreanska filmen från 2003 där huvudpersonen söker hämnd efter lång fångenskap?", answer: "Oldboy", promptEn: "What is the 2003 Korean film in which the main character seeks revenge after a long imprisonment?", answerEn: "Oldboy" },
  { id: "film-31", category: "Film", prompt: "Vilken Disneyfilm utspelar sig i kungariket Arendal?", answer: "Frost", promptEn: "Which Disney film is set in the kingdom of Arendelle?", answerEn: "Frozen" },
  { id: "film-32", category: "Film", prompt: "Vad heter den imaginära vännen i filmen Fight Club enligt huvudpersonens senare insikt?", answer: "Tyler Durden", promptEn: "Who turns out to be the narrator's imaginary alter ego in the film Fight Club?", answerEn: "Tyler Durden" },
  { id: "film-33", category: "Film", prompt: "Vilken regissör gjorde filmerna Spirited Away och Min granne Totoro?", answer: "Hayao Miyazaki", promptEn: "Which director made the films Spirited Away and My Neighbor Totoro?", answerEn: "Hayao Miyazaki" },
  { id: "film-34", category: "Film", prompt: "Vad heter boxaren som Sylvester Stallone spelar i en klassisk filmserie?", answer: "Rocky Balboa", promptEn: "What is the name of the boxer Sylvester Stallone plays in a classic film series?", answerEn: "Rocky Balboa" },
  { id: "film-35", category: "Film", prompt: "Vilken film från 2016 följer en lingvist som försöker kommunicera med utomjordingar?", answer: "Arrival", promptEn: "Which 2016 film follows a linguist trying to communicate with aliens?", answerEn: "Arrival" },
  { id: "film-36", category: "Film", prompt: "Vad heter karaktären som Keanu Reeves spelar i actionserien med samma namn?", answer: "John Wick", promptEn: "What is the name of the character Keanu Reeves plays in the action series of the same name?", answerEn: "John Wick" },
  { id: "film-37", category: "Film", prompt: "Vilken film av Francis Ford Coppola utspelar sig kring familjen Corleone?", answer: "Gudfadern", promptEn: "Which Francis Ford Coppola film revolves around the Corleone family?", answerEn: "The Godfather" },
  { id: "film-38", category: "Film", prompt: "Vilken film vann Oscar för bästa film 2024?", answer: "Oppenheimer", promptEn: "Which film won the Oscar for Best Picture in 2024?", answerEn: "Oppenheimer" },
  { id: "film-39", category: "Film", prompt: "Vad heter huvudroboten i Pixars film WALL-E?", answer: "WALL-E", promptEn: "What is the name of the main robot in Pixar's film WALL-E?", answerEn: "WALL-E" },
  { id: "film-40", category: "Film", prompt: "Vilken film från 2014 följer en trummis och hans hänsynslöse lärare Fletcher?", answer: "Whiplash", promptEn: "Which 2014 film follows a drummer and his ruthless teacher Fletcher?", answerEn: "Whiplash" },
  { id: "film-41", category: "Film", prompt: "Vad heter den klassiska stumfilmskomikern med plommonstop, käpp och mustasch?", answer: "Charlie Chaplin", promptEn: "Who is the classic silent film comedian with a bowler hat, cane and moustache?", answerEn: "Charlie Chaplin" },
  { id: "film-42", category: "Film", prompt: "Vilken film handlar om en nöjespark där dinosaurier återskapas genom DNA?", answer: "Jurassic Park", promptEn: "Which film is about a theme park where dinosaurs are recreated from DNA?", answerEn: "Jurassic Park" },
  { id: "film-43", category: "Film", prompt: "Vilken skådespelerska spelar huvudrollen i La La Land tillsammans med Ryan Gosling?", answer: "Emma Stone", promptEn: "Which actress plays the lead in La La Land alongside Ryan Gosling?", answerEn: "Emma Stone" },
  { id: "film-44", category: "Film", prompt: "Vad heter den första filmen i Marvel Cinematic Universe?", answer: "Iron Man", promptEn: "What is the first film in the Marvel Cinematic Universe?", answerEn: "Iron Man" },
  { id: "film-45", category: "Film", prompt: "Vilken film regisserades av Greta Gerwig och blev en stor biosuccé 2023?", answer: "Barbie", promptEn: "Which film was directed by Greta Gerwig and became a huge box office hit in 2023?", answerEn: "Barbie" },
  { id: "film-46", category: "Film", prompt: "Vad heter de små gula figurerna i Dumma mej?", answer: "Minions", promptEn: "What are the little yellow creatures in Despicable Me called?", answerEn: "Minions" },
  { id: "film-47", category: "Film", prompt: "Vilken film från 1991 vann fem stora Oscar, inklusive bästa film och bästa regi, och handlar om Hannibal Lecter?", answer: "När lammen tystnar", promptEn: "Which 1991 film won the five major Oscars, including Best Picture and Best Director, and is about Hannibal Lecter?", answerEn: "The Silence of the Lambs" },
  { id: "film-48", category: "Film", prompt: "Vad heter den brittiske agenten med kodnummer 007?", answer: "James Bond", promptEn: "What is the name of the British agent with the code number 007?", answerEn: "James Bond" },
  { id: "film-49", category: "Film", prompt: "Vilken film av Denis Villeneuve är baserad på Frank Herberts science fiction-roman?", answer: "Dune", promptEn: "Which Denis Villeneuve film is based on Frank Herbert's science fiction novel?", answerEn: "Dune" },
  { id: "film-50", category: "Film", prompt: "Vad heter filmen där Robin Williams spelar en inspirerande internatskolelärare?", answer: "Dead Poets Society", promptEn: "What is the film in which Robin Williams plays an inspiring boarding school teacher?", answerEn: "Dead Poets Society" },

  { id: "geo-1", category: "Geografi", prompt: "Vad är Sveriges huvudstad?", answer: "Stockholm", promptEn: "What is the capital of Sweden?", answerEn: "Stockholm" },
  { id: "geo-2", category: "Geografi", prompt: "Vilken världsdel ligger Brasilien i?", answer: "Sydamerika", promptEn: "Which continent is Brazil in?", answerEn: "South America" },
  { id: "geo-3", category: "Geografi", prompt: "Vilken stad är huvudstad i Frankrike?", answer: "Paris", promptEn: "Which city is the capital of France?", answerEn: "Paris" },
  { id: "geo-4", category: "Geografi", prompt: "Vilket hav ligger mellan Sverige och Finland?", answer: "Östersjön", promptEn: "Which sea lies between Sweden and Finland?", answerEn: "The Baltic Sea" },
  { id: "geo-5", category: "Geografi", prompt: "Vilket land har formen av en stövel på kartan?", answer: "Italien", promptEn: "Which country is shaped like a boot on the map?", answerEn: "Italy" },
  { id: "geo-6", category: "Geografi", prompt: "Vilken är världens största ocean?", answer: "Stilla havet", promptEn: "What is the largest ocean in the world?", answerEn: "The Pacific Ocean" },
  { id: "geo-7", category: "Geografi", prompt: "Vad heter Egyptens längsta flod?", answer: "Nilen", promptEn: "What is the longest river in Egypt?", answerEn: "The Nile" },
  { id: "geo-8", category: "Geografi", prompt: "Vilket land ligger direkt väst om Sverige?", answer: "Norge", promptEn: "Which country lies directly west of Sweden?", answerEn: "Norway" },
  { id: "geo-9", category: "Geografi", prompt: "Vilken är Kanadas huvudstad?", answer: "Ottawa", promptEn: "What is the capital of Canada?", answerEn: "Ottawa" },
  { id: "geo-10", category: "Geografi", prompt: "Vad heter världens högsta berg över havet?", answer: "Mount Everest", promptEn: "What is the world's highest mountain above sea level?", answerEn: "Mount Everest" },
  { id: "geo-11", category: "Geografi", prompt: "Vilket land har flest invånare i Afrika?", answer: "Nigeria", promptEn: "Which country has the largest population in Africa?", answerEn: "Nigeria" },
  { id: "geo-12", category: "Geografi", prompt: "Vilken ö är den största i Medelhavet?", answer: "Sicilien", promptEn: "Which island is the largest in the Mediterranean?", answerEn: "Sicily" },
  { id: "geo-13", category: "Geografi", prompt: "Vad heter havet mellan Afrika och Arabiska halvön?", answer: "Röda havet", promptEn: "What is the sea between Africa and the Arabian Peninsula called?", answerEn: "The Red Sea" },
  { id: "geo-14", category: "Geografi", prompt: "Vilken stad är huvudstad i Australien?", answer: "Canberra", promptEn: "Which city is the capital of Australia?", answerEn: "Canberra" },
  { id: "geo-15", category: "Geografi", prompt: "Vad heter bergskedjan som sträcker sig längs västra Sydamerika?", answer: "Anderna", promptEn: "What is the mountain range that runs along western South America called?", answerEn: "The Andes" },
  { id: "geo-16", category: "Geografi", prompt: "Vilket land omger Lesotho helt och hållet?", answer: "Sydafrika", promptEn: "Which country completely surrounds Lesotho?", answerEn: "South Africa" },
  { id: "geo-17", category: "Geografi", prompt: "Vilket sund skiljer Asien från Nordamerika?", answer: "Berings sund", promptEn: "Which strait separates Asia from North America?", answerEn: "The Bering Strait" },
  { id: "geo-18", category: "Geografi", prompt: "Vad heter Grönlands huvudstad?", answer: "Nuuk", promptEn: "What is the capital of Greenland?", answerEn: "Nuuk" },
  { id: "geo-19", category: "Geografi", prompt: "Vilken europeisk flod rinner genom Wien, Bratislava, Budapest och Belgrad?", answer: "Donau", promptEn: "Which European river flows through Vienna, Bratislava, Budapest and Belgrade?", answerEn: "The Danube" },
  { id: "geo-20", category: "Geografi", prompt: "Vilket land har huvudstaden Ulaanbaatar?", answer: "Mongoliet", promptEn: "Which country has Ulaanbaatar as its capital?", answerEn: "Mongolia" },
  { id: "geo-21", category: "Geografi", prompt: "Vilken stad är huvudstad i Portugal?", answer: "Lissabon", promptEn: "Which city is the capital of Portugal?", answerEn: "Lisbon" },
  { id: "geo-22", category: "Geografi", prompt: "Vilket land är världens största till ytan?", answer: "Ryssland", promptEn: "Which country is the largest in the world by area?", answerEn: "Russia" },
  { id: "geo-23", category: "Geografi", prompt: "Vad heter öknen som täcker stora delar av norra Afrika?", answer: "Sahara", promptEn: "What is the desert that covers large parts of northern Africa called?", answerEn: "The Sahara" },
  { id: "geo-24", category: "Geografi", prompt: "Vilket land har huvudstaden Reykjavik?", answer: "Island", promptEn: "Which country has Reykjavik as its capital?", answerEn: "Iceland" },
  { id: "geo-25", category: "Geografi", prompt: "Vilken amerikansk delstat kallas The Sunshine State?", answer: "Florida", promptEn: "Which US state is called The Sunshine State?", answerEn: "Florida" },
  { id: "geo-26", category: "Geografi", prompt: "Vad heter Japans högsta berg?", answer: "Fuji", promptEn: "What is the highest mountain in Japan?", answerEn: "Mount Fuji" },
  { id: "geo-27", category: "Geografi", prompt: "Vilket land delas i en nordlig och en sydlig del av den demilitariserade zonen?", answer: "Korea", promptEn: "Which country is divided into a northern and a southern part by the Demilitarized Zone?", answerEn: "Korea" },
  { id: "geo-28", category: "Geografi", prompt: "Vilken stad är huvudstad i Argentina?", answer: "Buenos Aires", promptEn: "Which city is the capital of Argentina?", answerEn: "Buenos Aires" },
  { id: "geo-29", category: "Geografi", prompt: "Vilket land har flest öar i världen enligt vanliga uppskattningar?", answer: "Sverige", promptEn: "Which country has the most islands in the world according to common estimates?", answerEn: "Sweden" },
  { id: "geo-30", category: "Geografi", prompt: "Vad heter sundet mellan Spanien och Marocko?", answer: "Gibraltarsundet", promptEn: "What is the strait between Spain and Morocco called?", answerEn: "The Strait of Gibraltar" },
  { id: "geo-31", category: "Geografi", prompt: "Vilken stad är huvudstad i Kenya?", answer: "Nairobi", promptEn: "Which city is the capital of Kenya?", answerEn: "Nairobi" },
  { id: "geo-32", category: "Geografi", prompt: "Vilket land har huvudstaden Ljubljana?", answer: "Slovenien", promptEn: "Which country has Ljubljana as its capital?", answerEn: "Slovenia" },
  { id: "geo-33", category: "Geografi", prompt: "Vad heter den största öknen i Asien?", answer: "Gobiöknen", promptEn: "What is the largest desert in Asia called?", answerEn: "The Gobi Desert" },
  { id: "geo-34", category: "Geografi", prompt: "Vilken flod rinner genom Paris?", answer: "Seine", promptEn: "Which river flows through Paris?", answerEn: "The Seine" },
  { id: "geo-35", category: "Geografi", prompt: "Vilken stad är huvudstad i Nya Zeeland?", answer: "Wellington", promptEn: "Which city is the capital of New Zealand?", answerEn: "Wellington" },
  { id: "geo-36", category: "Geografi", prompt: "Vilket land ligger mellan Frankrike och Spanien på Iberiska halvön?", answer: "Andorra", promptEn: "Which small country lies between France and Spain on the Iberian Peninsula?", answerEn: "Andorra" },
  { id: "geo-37", category: "Geografi", prompt: "Vad heter Afrikas högsta berg?", answer: "Kilimanjaro", promptEn: "What is the highest mountain in Africa?", answerEn: "Kilimanjaro" },
  { id: "geo-38", category: "Geografi", prompt: "Vilket land har huvudstaden Bogotá?", answer: "Colombia", promptEn: "Which country has Bogotá as its capital?", answerEn: "Colombia" },
  { id: "geo-39", category: "Geografi", prompt: "Vilken sjö är världens största till ytan?", answer: "Kaspiska havet", promptEn: "Which lake is the largest in the world by area?", answerEn: "The Caspian Sea" },
  { id: "geo-40", category: "Geografi", prompt: "Vilken stad är huvudstad i Thailand?", answer: "Bangkok", promptEn: "Which city is the capital of Thailand?", answerEn: "Bangkok" },
  { id: "geo-41", category: "Geografi", prompt: "Vilket hav gränsar både till Jordanien och Israel men är egentligen en salt sjö?", answer: "Döda havet", promptEn: "Which \"sea\" borders both Jordan and Israel but is actually a salt lake?", answerEn: "The Dead Sea" },
  { id: "geo-42", category: "Geografi", prompt: "Vilket land har huvudstaden Tallinn?", answer: "Estland", promptEn: "Which country has Tallinn as its capital?", answerEn: "Estonia" },
  { id: "geo-43", category: "Geografi", prompt: "Vad heter halvön där Norge och Sverige ligger?", answer: "Skandinaviska halvön", promptEn: "What is the peninsula where Norway and Sweden are located called?", answerEn: "The Scandinavian Peninsula" },
  { id: "geo-44", category: "Geografi", prompt: "Vilken stad är huvudstad i Peru?", answer: "Lima", promptEn: "Which city is the capital of Peru?", answerEn: "Lima" },
  { id: "geo-45", category: "Geografi", prompt: "Vilket land, förutom Vatikanstaten, är helt omgivet av Italien?", answer: "San Marino", promptEn: "Apart from Vatican City, which country is completely surrounded by Italy?", answerEn: "San Marino" },
  { id: "geo-46", category: "Geografi", prompt: "Vad heter den största ön i Karibien?", answer: "Kuba", promptEn: "What is the largest island in the Caribbean?", answerEn: "Cuba" },
  { id: "geo-47", category: "Geografi", prompt: "Vilken flod är längst i Sydamerika?", answer: "Amazonas", promptEn: "Which river is the longest in South America?", answerEn: "The Amazon" },
  { id: "geo-48", category: "Geografi", prompt: "Vilket land har huvudstaden Hanoi?", answer: "Vietnam", promptEn: "Which country has Hanoi as its capital?", answerEn: "Vietnam" },
  { id: "geo-49", category: "Geografi", prompt: "Vad heter världens djupaste kända havsgrav?", answer: "Marianergraven", promptEn: "What is the deepest known ocean trench in the world called?", answerEn: "The Mariana Trench" },
  { id: "geo-50", category: "Geografi", prompt: "Vilken stad är huvudstad i Marocko?", answer: "Rabat", promptEn: "Which city is the capital of Morocco?", answerEn: "Rabat" },

  { id: "hist-1", category: "Historia", prompt: "Vilket århundrade började år 1701?", answer: "1700-talet", promptEn: "Which century began in the year 1701?", answerEn: "The 18th century (the 1700s)" },
  { id: "hist-2", category: "Historia", prompt: "Vilket fartyg sjönk på sin jungfruresa 1912?", answer: "Titanic", promptEn: "Which ship sank on its maiden voyage in 1912?", answerEn: "Titanic" },
  { id: "hist-3", category: "Historia", prompt: "Vilket land styrdes av faraoner i forntiden?", answer: "Egypten", promptEn: "Which country was ruled by pharaohs in ancient times?", answerEn: "Egypt" },
  { id: "hist-4", category: "Historia", prompt: "Vilken mur föll 1989 och blev en symbol för kalla krigets slut?", answer: "Berlinmuren", promptEn: "Which wall fell in 1989 and became a symbol of the end of the Cold War?", answerEn: "The Berlin Wall" },
  { id: "hist-5", category: "Historia", prompt: "Vem var Sveriges drottning som abdikerade 1654?", answer: "Drottning Kristina", promptEn: "Which Swedish queen abdicated in 1654?", answerEn: "Queen Christina" },
  { id: "hist-6", category: "Historia", prompt: "Vad kallades perioden då människan använde stenredskap?", answer: "Stenåldern", promptEn: "What is the period when humans used stone tools called?", answerEn: "The Stone Age" },
  { id: "hist-7", category: "Historia", prompt: "Vilket imperium styrdes av Julius Caesar som general och ledare?", answer: "Romarriket", promptEn: "Which empire was Julius Caesar a general and leader of?", answerEn: "The Roman Empire" },
  { id: "hist-8", category: "Historia", prompt: "Vilket krig pågick mellan 1939 och 1945?", answer: "Andra världskriget", promptEn: "Which war lasted from 1939 to 1945?", answerEn: "World War II" },
  { id: "hist-9", category: "Historia", prompt: "Vilken fransk ledare besegrades slutgiltigt vid Waterloo 1815?", answer: "Napoleon Bonaparte", promptEn: "Which French leader was finally defeated at Waterloo in 1815?", answerEn: "Napoleon Bonaparte" },
  { id: "hist-10", category: "Historia", prompt: "Vad hette skeppet som förde pilgrimerna till Nordamerika 1620?", answer: "Mayflower", promptEn: "What was the name of the ship that carried the Pilgrims to North America in 1620?", answerEn: "Mayflower" },
  { id: "hist-11", category: "Historia", prompt: "Vilken svensk kung stupade vid Lützen 1632?", answer: "Gustav II Adolf", promptEn: "Which Swedish king fell at the Battle of Lützen in 1632?", answerEn: "Gustavus Adolphus (Gustav II Adolf)" },
  { id: "hist-12", category: "Historia", prompt: "Vad kallades återuppväckandet av konst och vetenskap i Europa mellan medeltiden och modern tid?", answer: "Renässansen", promptEn: "What is the revival of art and science in Europe between the Middle Ages and the modern era called?", answerEn: "The Renaissance" },
  { id: "hist-13", category: "Historia", prompt: "Vilken stad förstördes av vulkanutbrottet från Vesuvius år 79?", answer: "Pompeji", promptEn: "Which city was destroyed by the eruption of Vesuvius in AD 79?", answerEn: "Pompeii" },
  { id: "hist-14", category: "Historia", prompt: "Vilket år inleddes den franska revolutionen med stormningen av Bastiljen?", answer: "1789", promptEn: "In which year did the French Revolution begin with the storming of the Bastille?", answerEn: "1789" },
  { id: "hist-15", category: "Historia", prompt: "Vad hette dokumentet som begränsade den engelske kungens makt 1215?", answer: "Magna Carta", promptEn: "What was the name of the document that limited the English king's power in 1215?", answerEn: "Magna Carta" },
  { id: "hist-16", category: "Historia", prompt: "Vilken civilisation byggde Machu Picchu?", answer: "Inkariket", promptEn: "Which civilisation built Machu Picchu?", answerEn: "The Inca Empire" },
  { id: "hist-17", category: "Historia", prompt: "Vilken amerikansk president avskaffade slavarna genom Emancipation Proclamation?", answer: "Abraham Lincoln", promptEn: "Which US president issued the Emancipation Proclamation to free enslaved people?", answerEn: "Abraham Lincoln" },
  { id: "hist-18", category: "Historia", prompt: "Vad hette Sovjetunionens siste ledare?", answer: "Michail Gorbatjov", promptEn: "Who was the last leader of the Soviet Union?", answerEn: "Mikhail Gorbachev" },
  { id: "hist-19", category: "Historia", prompt: "Vilken kinesisk dynasti räknas som den första kejsardynastin?", answer: "Qin-dynastin", promptEn: "Which Chinese dynasty is considered the first imperial dynasty?", answerEn: "The Qin dynasty" },
  { id: "hist-20", category: "Historia", prompt: "Vilket fredsavtal avslutade första världskriget formellt 1919?", answer: "Versaillesfreden", promptEn: "Which peace treaty formally ended World War I in 1919?", answerEn: "The Treaty of Versailles" },
  { id: "hist-21", category: "Historia", prompt: "Vilken upptäcktsresande förknippas med att ha nått Amerika 1492?", answer: "Christofer Columbus", promptEn: "Which explorer is associated with reaching the Americas in 1492?", answerEn: "Christopher Columbus" },
  { id: "hist-22", category: "Historia", prompt: "Vad hette den engelska drottning som regerade under stora delar av 1800-talet?", answer: "Drottning Victoria", promptEn: "What was the name of the British queen who reigned for much of the 19th century?", answerEn: "Queen Victoria" },
  { id: "hist-23", category: "Historia", prompt: "Vilken stad var centrum för det antika grekiska stadsstaten med Akropolis?", answer: "Aten", promptEn: "Which city was the centre of the ancient Greek city-state with the Acropolis?", answerEn: "Athens" },
  { id: "hist-24", category: "Historia", prompt: "Vad kallades handelsvägen mellan Kina och Europa under antiken och medeltiden?", answer: "Sidenvägen", promptEn: "What was the trade route between China and Europe in antiquity and the Middle Ages called?", answerEn: "The Silk Road" },
  { id: "hist-25", category: "Historia", prompt: "Vilken svensk kung kallades Karl den tolfte?", answer: "Karl XII", promptEn: "Which Swedish warrior king was killed at the siege of Fredriksten in Norway in 1718?", answerEn: "Charles XII (Karl XII)" },
  { id: "hist-26", category: "Historia", prompt: "Vilket år föll Västromerska riket enligt traditionell historieskrivning?", answer: "476", promptEn: "In which year did the Western Roman Empire fall, according to traditional historiography?", answerEn: "476" },
  { id: "hist-27", category: "Historia", prompt: "Vad hette skeppet som exploderade i Havanna 1898 och bidrog till spansk-amerikanska kriget?", answer: "USS Maine", promptEn: "What was the name of the ship that exploded in Havana in 1898 and helped trigger the Spanish–American War?", answerEn: "USS Maine" },
  { id: "hist-28", category: "Historia", prompt: "Vilken stad var delad i öst och väst under kalla kriget?", answer: "Berlin", promptEn: "Which city was divided into East and West during the Cold War?", answerEn: "Berlin" },
  { id: "hist-29", category: "Historia", prompt: "Vad hette reformatorn som spikade upp sina teser i Wittenberg 1517?", answer: "Martin Luther", promptEn: "What was the name of the reformer who nailed his theses to a door in Wittenberg in 1517?", answerEn: "Martin Luther" },
  { id: "hist-30", category: "Historia", prompt: "Vilket nordiskt land blev först med kvinnlig rösträtt i nationella val?", answer: "Finland", promptEn: "Which Nordic country was the first to give women the vote in national elections?", answerEn: "Finland" },
  { id: "hist-31", category: "Historia", prompt: "Vilket slag år 1066 gav Vilhelm Erövraren makten över England?", answer: "Slaget vid Hastings", promptEn: "Which battle in 1066 gave William the Conqueror control of England?", answerEn: "The Battle of Hastings" },
  { id: "hist-32", category: "Historia", prompt: "Vad hette den österrikiske tronföljare vars mord utlöste första världskriget?", answer: "Franz Ferdinand", promptEn: "What was the name of the Austrian heir to the throne whose assassination triggered World War I?", answerEn: "Franz Ferdinand" },
  { id: "hist-33", category: "Historia", prompt: "Vilken organisation grundades 1945 för att främja internationell fred och säkerhet?", answer: "FN", promptEn: "Which organisation was founded in 1945 to promote international peace and security?", answerEn: "The United Nations (UN)" },
  { id: "hist-34", category: "Historia", prompt: "Vilket år landade människan på månen för första gången?", answer: "1969", promptEn: "In which year did humans first land on the Moon?", answerEn: "1969" },
  { id: "hist-35", category: "Historia", prompt: "Vilken egyptisk drottning hade relationer med både Julius Caesar och Marcus Antonius?", answer: "Kleopatra", promptEn: "Which Egyptian queen had relationships with both Julius Caesar and Mark Antony?", answerEn: "Cleopatra" },
  { id: "hist-36", category: "Historia", prompt: "Vad kallades den period i USA då alkohol var förbjudet genom lag?", answer: "Förbudstiden", promptEn: "What was the period in the USA when alcohol was banned by law called?", answerEn: "Prohibition" },
  { id: "hist-37", category: "Historia", prompt: "Vilken stad förstördes av atombomben den 6 augusti 1945?", answer: "Hiroshima", promptEn: "Which city was destroyed by the atomic bomb on 6 August 1945?", answerEn: "Hiroshima" },
  { id: "hist-38", category: "Historia", prompt: "Vilken civilisation är känd för städer som Tikal och Chichén Itzá?", answer: "Mayariket", promptEn: "Which civilisation is known for cities such as Tikal and Chichén Itzá?", answerEn: "The Maya civilisation" },
  { id: "hist-39", category: "Historia", prompt: "Vad hette den sydafrikanske ledaren som satt fängslad länge och senare blev president?", answer: "Nelson Mandela", promptEn: "What was the name of the South African leader who was imprisoned for many years and later became president?", answerEn: "Nelson Mandela" },
  { id: "hist-40", category: "Historia", prompt: "Vilken kung lät bygga slottet Versailles som symbol för fransk absolutism?", answer: "Ludvig XIV", promptEn: "Which king had the Palace of Versailles built as a symbol of French absolutism?", answerEn: "Louis XIV" },
  { id: "hist-41", category: "Historia", prompt: "Vilket imperium styrdes från Konstantinopel efter Västroms fall?", answer: "Bysantinska riket", promptEn: "Which empire was ruled from Constantinople after the fall of the Western Roman Empire?", answerEn: "The Byzantine Empire" },
  { id: "hist-42", category: "Historia", prompt: "Vad kallades rymdkapplöpningen mellan USA och Sovjetunionen under kalla kriget?", answer: "Rymdkapplöpningen", promptEn: "What was the competition between the USA and the Soviet Union to conquer space during the Cold War called?", answerEn: "The Space Race" },
  { id: "hist-43", category: "Historia", prompt: "Vilken svensk statsminister mördades 1986?", answer: "Olof Palme", promptEn: "Which Swedish prime minister was assassinated in 1986?", answerEn: "Olof Palme" },
  { id: "hist-44", category: "Historia", prompt: "Vilket havskrig 1571 stoppade i stor utsträckning Osmanska rikets expansion i Medelhavet?", answer: "Slaget vid Lepanto", promptEn: "Which naval battle in 1571 largely halted the Ottoman Empire's expansion in the Mediterranean?", answerEn: "The Battle of Lepanto" },
  { id: "hist-45", category: "Historia", prompt: "Vad hette den stora pestepidemi som drabbade Europa på 1300-talet?", answer: "Digerdöden", promptEn: "What was the great plague epidemic that struck Europe in the 14th century called?", answerEn: "The Black Death" },
  { id: "hist-46", category: "Historia", prompt: "Vilken stad var huvudstad i Östromerska riket och heter i dag Istanbul?", answer: "Konstantinopel", promptEn: "Which city was the capital of the Eastern Roman Empire and is called Istanbul today?", answerEn: "Constantinople" },
  { id: "hist-47", category: "Historia", prompt: "Vilket land koloniserade Brasilien?", answer: "Portugal", promptEn: "Which country colonised Brazil?", answerEn: "Portugal" },
  { id: "hist-48", category: "Historia", prompt: "Vad hette freden 1648 som ofta markerar slutet på trettioåriga kriget?", answer: "Westfaliska freden", promptEn: "What was the 1648 peace that is often seen as marking the end of the Thirty Years' War called?", answerEn: "The Peace of Westphalia" },
  { id: "hist-49", category: "Historia", prompt: "Vilken ideologisk konflikt dominerade relationen mellan USA och Sovjetunionen efter andra världskriget?", answer: "Kalla kriget", promptEn: "Which ideological conflict dominated relations between the USA and the Soviet Union after World War II?", answerEn: "The Cold War" },
  { id: "hist-50", category: "Historia", prompt: "Vad hette den franska hjältinnan som ledde trupper under hundraårskriget och senare helgonförklarades?", answer: "Jeanne d'Arc", promptEn: "What was the name of the French heroine who led troops during the Hundred Years' War and was later made a saint?", answerEn: "Joan of Arc" },

  { id: "sport-1", category: "Sport", prompt: "Hur många spelare har ett fotbollslag på planen samtidigt?", answer: "11", promptEn: "How many players does a football (soccer) team have on the pitch at the same time?", answerEn: "11" },
  { id: "sport-2", category: "Sport", prompt: "I vilken sport används racket och fjäderboll?", answer: "Badminton", promptEn: "In which sport do you use a racket and a shuttlecock?", answerEn: "Badminton" },
  { id: "sport-3", category: "Sport", prompt: "Vad heter sporten där man gör strike och spare?", answer: "Bowling", promptEn: "What is the sport where you score strikes and spares called?", answerEn: "Bowling" },
  { id: "sport-4", category: "Sport", prompt: "Vilken sport förknippas starkast med Wimbledon?", answer: "Tennis", promptEn: "Which sport is most strongly associated with Wimbledon?", answerEn: "Tennis" },
  { id: "sport-5", category: "Sport", prompt: "Hur många poäng är en vanlig korg värd i basket?", answer: "2", promptEn: "How many points is a regular basket worth in basketball?", answerEn: "2" },
  { id: "sport-6", category: "Sport", prompt: "Vilken sport utövar man i Vasaloppet?", answer: "Längdskidor", promptEn: "Which sport is done in Sweden's famous Vasaloppet race?", answerEn: "Cross-country skiing" },
  { id: "sport-7", category: "Sport", prompt: "Vad heter sporten där man surfar på snö?", answer: "Snowboard", promptEn: "What is the sport where you \"surf\" on snow called?", answerEn: "Snowboarding" },
  { id: "sport-8", category: "Sport", prompt: "Vilket land kommer fotbollsklubben FC Barcelona ifrån?", answer: "Spanien", promptEn: "Which country does the football club FC Barcelona come from?", answerEn: "Spain" },
  { id: "sport-9", category: "Sport", prompt: "Vilket land vann fotbolls-VM 2014 för herrar?", answer: "Tyskland", promptEn: "Which country won the 2014 men's FIFA World Cup?", answerEn: "Germany" },
  { id: "sport-10", category: "Sport", prompt: "Vad heter den svenska stavhopparen som satt flera världsrekord under 2020-talet?", answer: "Armand Duplantis", promptEn: "What is the name of the Swedish pole vaulter who set several world records in the 2020s?", answerEn: "Armand Duplantis" },
  { id: "sport-11", category: "Sport", prompt: "Hur lång är en maratondistans i kilometer?", answer: "42,195 kilometer", promptEn: "How long is a marathon in kilometres?", answerEn: "42.195 kilometres" },
  { id: "sport-12", category: "Sport", prompt: "Vilken sport utövas i turneringen Ryder Cup?", answer: "Golf", promptEn: "Which sport is played in the Ryder Cup?", answerEn: "Golf" },
  { id: "sport-13", category: "Sport", prompt: "Vad kallas den högsta poängen i gymnastikens gamla tiopoängssystem?", answer: "Perfect 10", promptEn: "What was the top score called in gymnastics' old ten-point system?", answerEn: "Perfect 10" },
  { id: "sport-14", category: "Sport", prompt: "I vilken sport spelar man på arenor som kallas velodromer?", answer: "Bancykling", promptEn: "In which sport do you compete in arenas called velodromes?", answerEn: "Track cycling" },
  { id: "sport-15", category: "Sport", prompt: "Vilken nation har vunnit flest herr-VM i ishockey genom tiderna om Sovjetunionen räknas separat?", answer: "Kanada", promptEn: "Which nation has won the most men's Ice Hockey World Championships of all time if the Soviet Union is counted separately?", answerEn: "Canada" },
  { id: "sport-16", category: "Sport", prompt: "Vilket simtag är oftast snabbast i tävlingssimning?", answer: "Frisim", promptEn: "Which swimming stroke is usually the fastest in competitive swimming?", answerEn: "Freestyle" },
  { id: "sport-17", category: "Sport", prompt: "Vad heter pokalen som vinnaren av NHL-slutspelet får?", answer: "Stanley Cup", promptEn: "What is the trophy awarded to the winner of the NHL playoffs called?", answerEn: "Stanley Cup" },
  { id: "sport-18", category: "Sport", prompt: "Vilken sport utövar man i tävlingen Tour de France?", answer: "Landsvägscykling", promptEn: "Which sport is the Tour de France?", answerEn: "Road cycling" },
  { id: "sport-19", category: "Sport", prompt: "Hur många set måste man normalt vinna i en herrsingelfinal i Grand Slam-tennis?", answer: "Tre set", promptEn: "How many sets must you normally win in a men's singles final at a Grand Slam tennis tournament?", answerEn: "Three sets" },
  { id: "sport-20", category: "Sport", prompt: "Vilken boxare var känd som The Greatest och hette Cassius Clay som ung?", answer: "Muhammad Ali", promptEn: "Which boxer was known as The Greatest and was called Cassius Clay as a young man?", answerEn: "Muhammad Ali" },
  { id: "sport-21", category: "Sport", prompt: "Vilken sport utövas i Allsvenskan?", answer: "Fotboll", promptEn: "Which sport is played in Sweden's Allsvenskan league?", answerEn: "Football (soccer)" },
  { id: "sport-22", category: "Sport", prompt: "Hur många hål spelas normalt i en golfrunda?", answer: "18", promptEn: "How many holes are normally played in a round of golf?", answerEn: "18" },
  { id: "sport-23", category: "Sport", prompt: "Vilken sport har positionerna pitcher, catcher och shortstop?", answer: "Baseball", promptEn: "Which sport has the positions pitcher, catcher and shortstop?", answerEn: "Baseball" },
  { id: "sport-24", category: "Sport", prompt: "Vad kallas det när man gör tre mål i samma match i fotboll eller ishockey?", answer: "Hat trick", promptEn: "What is it called when a player scores three goals in the same football or ice hockey game?", answerEn: "Hat trick" },
  { id: "sport-25", category: "Sport", prompt: "Vilket land är känt för rugbylaget All Blacks?", answer: "Nya Zeeland", promptEn: "Which country is known for the rugby team the All Blacks?", answerEn: "New Zealand" },
  { id: "sport-26", category: "Sport", prompt: "Vilken friidrottsgren innebär hopp över en horisontell ribba med hjälp av stav?", answer: "Stavhopp", promptEn: "Which athletics event involves jumping over a horizontal bar with the help of a pole?", answerEn: "Pole vault" },
  { id: "sport-27", category: "Sport", prompt: "I vilken sport tävlar man om att vinna gula tröjan i en tre veckor lång tävling i Frankrike?", answer: "Cykling", promptEn: "In which sport do you compete to win the yellow jersey in a three-week race in France?", answerEn: "Cycling" },
  { id: "sport-28", category: "Sport", prompt: "Vad kallas den serie i USA där lag som Lakers och Celtics spelar?", answer: "NBA", promptEn: "What is the US league where teams like the Lakers and the Celtics play called?", answerEn: "NBA" },
  { id: "sport-29", category: "Sport", prompt: "Vilken sport förknippas med tävlingen Davis Cup?", answer: "Tennis", promptEn: "Which sport is associated with the Davis Cup?", answerEn: "Tennis" },
  { id: "sport-30", category: "Sport", prompt: "Vad heter den stora internationella multisporttävlingen för vinteridrotter?", answer: "Vinter-OS", promptEn: "What is the big international multi-sport event for winter sports called?", answerEn: "The Winter Olympics" },
  { id: "sport-31", category: "Sport", prompt: "Hur många spelare per lag är på planen samtidigt i volleyboll?", answer: "6", promptEn: "How many players per team are on the court at the same time in volleyball?", answerEn: "6" },
  { id: "sport-32", category: "Sport", prompt: "Vilken svensk fotbollsspelare har spelat i klubbar som Ajax, Juventus, Inter, Barcelona, Milan och PSG?", answer: "Zlatan Ibrahimović", promptEn: "Which Swedish footballer has played for clubs such as Ajax, Juventus, Inter, Barcelona, Milan and PSG?", answerEn: "Zlatan Ibrahimović" },
  { id: "sport-33", category: "Sport", prompt: "Vad heter den årliga amerikanska finalen i amerikansk fotboll?", answer: "Super Bowl", promptEn: "What is the annual championship game in American football called?", answerEn: "Super Bowl" },
  { id: "sport-34", category: "Sport", prompt: "Vilken idrott utövas i rinken med sopande lagkamrater och en sten som glider på is?", answer: "Curling", promptEn: "Which sport is played on a sheet of ice with teammates sweeping in front of a sliding stone?", answerEn: "Curling" },
  { id: "sport-35", category: "Sport", prompt: "Vad heter den snabbaste grenen i alpint där fart snarare än tekniska svängar står i centrum?", answer: "Störtlopp", promptEn: "What is the fastest alpine skiing discipline, where speed matters more than technical turns?", answerEn: "Downhill" },
  { id: "sport-36", category: "Sport", prompt: "I vilken sport används begreppet birdie?", answer: "Golf", promptEn: "In which sport is the term \"birdie\" used?", answerEn: "Golf" },
  { id: "sport-37", category: "Sport", prompt: "Vilken nation förknippas starkast med sporten sumobrottning?", answer: "Japan", promptEn: "Which nation is most strongly associated with sumo wrestling?", answerEn: "Japan" },
  { id: "sport-38", category: "Sport", prompt: "Hur många ringar finns i den olympiska symbolen?", answer: "5", promptEn: "How many rings are there in the Olympic symbol?", answerEn: "5" },
  { id: "sport-39", category: "Sport", prompt: "Vad heter världens mest kända långlopp inom hundspann i Alaska?", answer: "Iditarod", promptEn: "What is the world's most famous long-distance sled dog race in Alaska called?", answerEn: "Iditarod" },
  { id: "sport-40", category: "Sport", prompt: "Vilken sport utövar man i UFC?", answer: "MMA", promptEn: "Which sport is competed in the UFC?", answerEn: "MMA (mixed martial arts)" },
  { id: "sport-41", category: "Sport", prompt: "Vilket land arrangerade sommar-OS 2016?", answer: "Brasilien", promptEn: "Which country hosted the 2016 Summer Olympics?", answerEn: "Brazil" },
  { id: "sport-42", category: "Sport", prompt: "Vad heter den svenska skidorten där många alpina världscuptävlingar arrangeras?", answer: "Åre", promptEn: "What is the Swedish ski resort where many alpine World Cup races are held called?", answerEn: "Åre" },
  { id: "sport-43", category: "Sport", prompt: "I vilken sport finns termerna scrum och try?", answer: "Rugby", promptEn: "In which sport do you find the terms scrum and try?", answerEn: "Rugby" },
  { id: "sport-44", category: "Sport", prompt: "Hur många poäng är en touchdown värd i amerikansk fotboll innan extrapoäng?", answer: "6", promptEn: "How many points is a touchdown worth in American football, before the extra point?", answerEn: "6" },
  { id: "sport-45", category: "Sport", prompt: "Vad heter turneringen där Europas bästa fotbollsklubbar möts varje säsong?", answer: "Champions League", promptEn: "What is the tournament where Europe's best football clubs face each other every season called?", answerEn: "Champions League" },
  { id: "sport-46", category: "Sport", prompt: "Vilken motorsport körs på banor som Monza, Silverstone och Suzuka?", answer: "Formel 1", promptEn: "Which motorsport is raced on circuits such as Monza, Silverstone and Suzuka?", answerEn: "Formula 1" },
  { id: "sport-47", category: "Sport", prompt: "Vad heter den jamaicanske sprintstjärnan som dominerade OS på 100 och 200 meter?", answer: "Usain Bolt", promptEn: "What is the name of the Jamaican sprint star who dominated the Olympic 100 and 200 metres?", answerEn: "Usain Bolt" },
  { id: "sport-48", category: "Sport", prompt: "Vilken sport utövas i tävlingen America's Cup?", answer: "Segling", promptEn: "Which sport is the America's Cup contested in?", answerEn: "Sailing" },
  { id: "sport-49", category: "Sport", prompt: "Hur många minuter är ordinarie speltid i en handbollsmatch för seniorer?", answer: "60 minuter", promptEn: "How many minutes of regular playing time are there in a senior handball match?", answerEn: "60 minutes" },
  { id: "sport-50", category: "Sport", prompt: "Vilken sport utövar man om man tävlar i decathlon?", answer: "Friidrott", promptEn: "Which sport do you compete in if you take part in the decathlon?", answerEn: "Athletics (track and field)" },

  { id: "science-1", category: "Vetenskap", prompt: "Vilken planet är närmast solen i vårt solsystem?", answer: "Merkurius", promptEn: "Which planet is closest to the Sun in our solar system?", answerEn: "Mercury" },
  { id: "science-2", category: "Vetenskap", prompt: "Vad kallas H2O i vardagligt tal?", answer: "Vatten", promptEn: "What is H2O called in everyday language?", answerEn: "Water" },
  { id: "science-3", category: "Vetenskap", prompt: "Vilket organ pumpar runt blodet i kroppen?", answer: "Hjärtat", promptEn: "Which organ pumps blood around the body?", answerEn: "The heart" },
  { id: "science-4", category: "Vetenskap", prompt: "Vilken gas andas människan in för att överleva?", answer: "Syre", promptEn: "Which gas do humans breathe in to survive?", answerEn: "Oxygen" },
  { id: "science-5", category: "Vetenskap", prompt: "Vad heter kraften som drar saker mot jorden?", answer: "Gravitation", promptEn: "What is the force that pulls things towards the Earth called?", answerEn: "Gravity" },
  { id: "science-6", category: "Vetenskap", prompt: "Vilket djur är det största landlevande djuret i dag?", answer: "Elefant", promptEn: "Which animal is the largest land animal alive today?", answerEn: "Elephant" },
  { id: "science-7", category: "Vetenskap", prompt: "Vilken metall har den kemiska beteckningen Fe?", answer: "Järn", promptEn: "Which metal has the chemical symbol Fe?", answerEn: "Iron" },
  { id: "science-8", category: "Vetenskap", prompt: "Vilken planet kallas den röda planeten?", answer: "Mars", promptEn: "Which planet is called the Red Planet?", answerEn: "Mars" },
  { id: "science-9", category: "Vetenskap", prompt: "Vad heter den minsta enheten i ett grundämne som fortfarande behåller ämnets egenskaper?", answer: "Atom", promptEn: "What is the smallest unit of an element that still keeps the element's properties called?", answerEn: "Atom" },
  { id: "science-10", category: "Vetenskap", prompt: "Vilken forskare formulerade rörelselagarna och gravitationslagen?", answer: "Isaac Newton", promptEn: "Which scientist formulated the laws of motion and the law of gravitation?", answerEn: "Isaac Newton" },
  { id: "science-11", category: "Vetenskap", prompt: "Vad heter processen när en vätska övergår till gas vid sin yta?", answer: "Avdunstning", promptEn: "What is the process called when a liquid turns into gas at its surface?", answerEn: "Evaporation" },
  { id: "science-12", category: "Vetenskap", prompt: "Vilken del av cellen innehåller vanligtvis arvsmassan i eukaryota organismer?", answer: "Cellkärnan", promptEn: "Which part of the cell usually contains the genetic material in eukaryotic organisms?", answerEn: "The nucleus" },
  { id: "science-13", category: "Vetenskap", prompt: "Vad står DNA för?", answer: "Deoxiribonukleinsyra", promptEn: "What does DNA stand for?", answerEn: "Deoxyribonucleic acid" },
  { id: "science-14", category: "Vetenskap", prompt: "Vilken partikel har negativ elektrisk laddning?", answer: "Elektron", promptEn: "Which particle has a negative electric charge?", answerEn: "Electron" },
  { id: "science-15", category: "Vetenskap", prompt: "Vad heter måttenheten för elektrisk resistans?", answer: "Ohm", promptEn: "What is the unit of electrical resistance called?", answerEn: "Ohm" },
  { id: "science-16", category: "Vetenskap", prompt: "Vilket grundämne har atomnummer 79?", answer: "Guld", promptEn: "Which element has atomic number 79?", answerEn: "Gold" },
  { id: "science-17", category: "Vetenskap", prompt: "Vad kallas teorin om universums uppkomst genom en snabb expansion från ett extremt tätt tillstånd?", answer: "Big Bang", promptEn: "What is the theory that the universe began with a rapid expansion from an extremely dense state called?", answerEn: "Big Bang" },
  { id: "science-18", category: "Vetenskap", prompt: "Vilken organell kallas ofta cellens kraftverk?", answer: "Mitokondrie", promptEn: "Which organelle is often called the powerhouse of the cell?", answerEn: "Mitochondrion" },
  { id: "science-19", category: "Vetenskap", prompt: "Vad heter skalan som används för att mäta hårdheten hos mineral?", answer: "Mohs skala", promptEn: "What is the scale used to measure the hardness of minerals called?", answerEn: "Mohs scale" },
  { id: "science-20", category: "Vetenskap", prompt: "Vilken forskare är mest förknippad med relativitetsteorin?", answer: "Albert Einstein", promptEn: "Which scientist is most associated with the theory of relativity?", answerEn: "Albert Einstein" },
  { id: "science-21", category: "Vetenskap", prompt: "Vilket grundämne är vanligast i jordskorpan?", answer: "Syre", promptEn: "Which element is the most abundant in the Earth's crust?", answerEn: "Oxygen" },
  { id: "science-22", category: "Vetenskap", prompt: "Vad heter den process där växter tar upp koldioxid och avger syre?", answer: "Fotosyntes", promptEn: "What is the process in which plants take in carbon dioxide and release oxygen called?", answerEn: "Photosynthesis" },
  { id: "science-23", category: "Vetenskap", prompt: "Vilket blodkärl leder blod från hjärtat ut i kroppen?", answer: "Artär", promptEn: "Which type of blood vessel carries blood from the heart out to the body?", answerEn: "Artery" },
  { id: "science-24", category: "Vetenskap", prompt: "Vad heter den vetenskapliga ordningen av organismer: art, släkte, familj och så vidare?", answer: "Taxonomi", promptEn: "What is the scientific classification of organisms, into species, genus, family and so on, called?", answerEn: "Taxonomy" },
  { id: "science-25", category: "Vetenskap", prompt: "Vilken planet har de mest framträdande ringarna i solsystemet?", answer: "Saturnus", promptEn: "Which planet has the most prominent rings in the solar system?", answerEn: "Saturn" },
  { id: "science-26", category: "Vetenskap", prompt: "Vad kallas övergången från fast form direkt till gas?", answer: "Sublimering", promptEn: "What is the transition from solid directly to gas called?", answerEn: "Sublimation" },
  { id: "science-27", category: "Vetenskap", prompt: "Vilken del av örat ansvarar bland annat för balanssinnet?", answer: "Innerörat", promptEn: "Which part of the ear is responsible for, among other things, the sense of balance?", answerEn: "The inner ear" },
  { id: "science-28", category: "Vetenskap", prompt: "Vilket ämne har den kemiska symbolen Na?", answer: "Natrium", promptEn: "Which element has the chemical symbol Na?", answerEn: "Sodium" },
  { id: "science-29", category: "Vetenskap", prompt: "Vad kallas ett djur som reglerar kroppstemperaturen med hjälp av omgivningen?", answer: "Växelvarmt djur", promptEn: "What is an animal that regulates its body temperature using its surroundings called?", answerEn: "Cold-blooded animal (ectotherm)" },
  { id: "science-30", category: "Vetenskap", prompt: "Vilken fysikalisk storhet mäts i newton?", answer: "Kraft", promptEn: "Which physical quantity is measured in newtons?", answerEn: "Force" },
  { id: "science-31", category: "Vetenskap", prompt: "Vad heter galaxen som vårt solsystem befinner sig i?", answer: "Vintergatan", promptEn: "What is the name of the galaxy our solar system is in?", answerEn: "The Milky Way" },
  { id: "science-32", category: "Vetenskap", prompt: "Vilket vitamin bildas i huden vid exponering för solljus?", answer: "D-vitamin", promptEn: "Which vitamin is produced in the skin when exposed to sunlight?", answerEn: "Vitamin D" },
  { id: "science-33", category: "Vetenskap", prompt: "Vad heter den geologiska tidsperiod då dinosaurierna dominerade?", answer: "Mesozoikum", promptEn: "What is the geological era when the dinosaurs dominated called?", answerEn: "The Mesozoic" },
  { id: "science-34", category: "Vetenskap", prompt: "Vilken gas är vanligast i jordens atmosfär?", answer: "Kväve", promptEn: "Which gas is the most common in the Earth's atmosphere?", answerEn: "Nitrogen" },
  { id: "science-35", category: "Vetenskap", prompt: "Vilken svensk vetenskapsman skapade temperaturskalan med samma namn?", answer: "Anders Celsius", promptEn: "Which Swedish scientist created the temperature scale that bears his name?", answerEn: "Anders Celsius" },
  { id: "science-36", category: "Vetenskap", prompt: "Vad kallas den process där två atomkärnor slås samman?", answer: "Kärnfusion", promptEn: "What is the process in which two atomic nuclei merge called?", answerEn: "Nuclear fusion" },
  { id: "science-37", category: "Vetenskap", prompt: "Vilken del av hjärnan förknippas starkt med koordination och balans?", answer: "Lillhjärnan", promptEn: "Which part of the brain is strongly associated with coordination and balance?", answerEn: "The cerebellum" },
  { id: "science-38", category: "Vetenskap", prompt: "Vad heter världens hårdaste naturliga material?", answer: "Diamant", promptEn: "What is the hardest natural material in the world?", answerEn: "Diamond" },
  { id: "science-39", category: "Vetenskap", prompt: "Vilket instrument används för att se mycket små strukturer, till exempel celler?", answer: "Mikroskop", promptEn: "Which instrument is used to see very small structures, such as cells?", answerEn: "Microscope" },
  { id: "science-40", category: "Vetenskap", prompt: "Vad kallas den bana jorden rör sig i runt solen?", answer: "Omloppsbana", promptEn: "What is the path the Earth travels around the Sun called?", answerEn: "Orbit" },
  { id: "science-41", category: "Vetenskap", prompt: "Vilken planet är störst i vårt solsystem?", answer: "Jupiter", promptEn: "Which planet is the largest in our solar system?", answerEn: "Jupiter" },
  { id: "science-42", category: "Vetenskap", prompt: "Vad heter den molekyl som lagrar energi kortsiktigt i kroppens celler?", answer: "ATP", promptEn: "What is the molecule that stores energy short-term in the body's cells called?", answerEn: "ATP" },
  { id: "science-43", category: "Vetenskap", prompt: "Vilken gren av fysiken behandlar ljus?", answer: "Optik", promptEn: "Which branch of physics deals with light?", answerEn: "Optics" },
  { id: "science-44", category: "Vetenskap", prompt: "Vad kallas den punkt där ett ämne inte längre kan skiljas mellan vätska och gas?", answer: "Kritisk punkt", promptEn: "What is the point at which a substance can no longer be distinguished as liquid or gas called?", answerEn: "Critical point" },
  { id: "science-45", category: "Vetenskap", prompt: "Vilken naturvetenskap studerar jordens bergarter, inre och processer?", answer: "Geologi", promptEn: "Which natural science studies the Earth's rocks, interior and processes?", answerEn: "Geology" },
  { id: "science-46", category: "Vetenskap", prompt: "Vad heter den minsta benämnda enheten i genetisk information?", answer: "Gen", promptEn: "What is the smallest named unit of genetic information called?", answerEn: "Gene" },
  { id: "science-47", category: "Vetenskap", prompt: "Vilken forskare upptäckte penicillin av en slump?", answer: "Alexander Fleming", promptEn: "Which scientist discovered penicillin by accident?", answerEn: "Alexander Fleming" },
  { id: "science-48", category: "Vetenskap", prompt: "Vilket djur användes av Darwin som viktigt exempel under studierna på Galápagos?", answer: "Finkar", promptEn: "Which animals did Darwin use as an important example during his studies on the Galápagos Islands?", answerEn: "Finches" },
  { id: "science-49", category: "Vetenskap", prompt: "Vad kallas vetenskapen om väder och atmosfär?", answer: "Meteorologi", promptEn: "What is the science of weather and the atmosphere called?", answerEn: "Meteorology" },
  { id: "science-50", category: "Vetenskap", prompt: "Vilken partikel i atomkärnan saknar elektrisk laddning?", answer: "Neutron", promptEn: "Which particle in the atomic nucleus has no electric charge?", answerEn: "Neutron" },

  { id: "music-1", category: "Musik", prompt: "Vilken svensk grupp sjöng 'Dancing Queen'?", answer: "ABBA", promptEn: "Which Swedish group sang \"Dancing Queen\"?", answerEn: "ABBA" },
  { id: "music-2", category: "Musik", prompt: "Hur många strängar har en vanlig gitarr oftast?", answer: "6", promptEn: "How many strings does a standard guitar usually have?", answerEn: "6" },
  { id: "music-3", category: "Musik", prompt: "Vilken artist är känd för låten 'Shake It Off'?", answer: "Taylor Swift", promptEn: "Which artist is known for the song \"Shake It Off\"?", answerEn: "Taylor Swift" },
  { id: "music-4", category: "Musik", prompt: "Vad kallas personen som leder en orkester?", answer: "Dirigent", promptEn: "What is the person who leads an orchestra called?", answerEn: "Conductor" },
  { id: "music-5", category: "Musik", prompt: "Vilket instrument har svarta och vita tangenter?", answer: "Piano", promptEn: "Which instrument has black and white keys?", answerEn: "Piano" },
  { id: "music-6", category: "Musik", prompt: "Vilken artist kallas ofta The King of Pop?", answer: "Michael Jackson", promptEn: "Which artist is often called The King of Pop?", answerEn: "Michael Jackson" },
  { id: "music-7", category: "Musik", prompt: "Vad heter tävlingen där länder tävlar med egna låtar i Europa?", answer: "Eurovision Song Contest", promptEn: "What is the competition where European countries compete with their own songs called?", answerEn: "Eurovision Song Contest" },
  { id: "music-8", category: "Musik", prompt: "Vilken artist sjunger 'Hello' och 'Someone Like You'?", answer: "Adele", promptEn: "Which artist sings \"Hello\" and \"Someone Like You\"?", answerEn: "Adele" },
  { id: "music-9", category: "Musik", prompt: "Vilken kompositör skrev de fyra årstiderna?", answer: "Antonio Vivaldi", promptEn: "Which composer wrote The Four Seasons?", answerEn: "Antonio Vivaldi" },
  { id: "music-10", category: "Musik", prompt: "Vilken artist var frontfigur i Queen?", answer: "Freddie Mercury", promptEn: "Who was the frontman of Queen?", answerEn: "Freddie Mercury" },
  { id: "music-11", category: "Musik", prompt: "Vad kallas tempobeteckningen som betyder långsamt på italienska?", answer: "Adagio", promptEn: "What is the Italian tempo marking meaning slowly called?", answerEn: "Adagio" },
  { id: "music-12", category: "Musik", prompt: "Vilket instrument spelar Yo-Yo Ma?", answer: "Cello", promptEn: "Which instrument does Yo-Yo Ma play?", answerEn: "Cello" },
  { id: "music-13", category: "Musik", prompt: "Vilken tonsättare blev döv senare i livet men fortsatte komponera?", answer: "Ludwig van Beethoven", promptEn: "Which composer went deaf later in life but kept composing?", answerEn: "Ludwig van Beethoven" },
  { id: "music-14", category: "Musik", prompt: "Vad heter bandet som gav ut albumet The Dark Side of the Moon?", answer: "Pink Floyd", promptEn: "What is the band that released the album The Dark Side of the Moon called?", answerEn: "Pink Floyd" },
  { id: "music-15", category: "Musik", prompt: "Vilken svensk producent har arbetat med artister som Britney Spears, Backstreet Boys och Taylor Swift?", answer: "Max Martin", promptEn: "Which Swedish producer has worked with artists such as Britney Spears, the Backstreet Boys and Taylor Swift?", answerEn: "Max Martin" },
  { id: "music-16", category: "Musik", prompt: "Vilken jazzmusiker är känd för albumet Kind of Blue?", answer: "Miles Davis", promptEn: "Which jazz musician is known for the album Kind of Blue?", answerEn: "Miles Davis" },
  { id: "music-17", category: "Musik", prompt: "Vilken artist släppte albumet Lemonade 2016?", answer: "Beyoncé", promptEn: "Which artist released the album Lemonade in 2016?", answerEn: "Beyoncé" },
  { id: "music-18", category: "Musik", prompt: "Vad kallas en grupp om fyra musiker eller sångare?", answer: "Kvartett", promptEn: "What is a group of four musicians or singers called?", answerEn: "Quartet" },
  { id: "music-19", category: "Musik", prompt: "Vilken opera av Mozart handlar om en förförare från Sevilla?", answer: "Don Giovanni", promptEn: "Which Mozart opera is about a seducer from Seville?", answerEn: "Don Giovanni" },
  { id: "music-20", category: "Musik", prompt: "Vilken musikgenre förknippas med artister som Avicii, Swedish House Mafia och Alesso?", answer: "EDM", promptEn: "Which music genre is associated with artists such as Avicii, Swedish House Mafia and Alesso?", answerEn: "EDM" },
  { id: "music-21", category: "Musik", prompt: "Vilket instrument spelade Jimi Hendrix framför allt?", answer: "Gitarr", promptEn: "Which instrument did Jimi Hendrix mainly play?", answerEn: "Guitar" },
  { id: "music-22", category: "Musik", prompt: "Vad heter musikfestivalen i Kalifornien som ofta nämns tillsammans med stora internationella artister?", answer: "Coachella", promptEn: "What is the music festival in California that is often mentioned alongside big international artists called?", answerEn: "Coachella" },
  { id: "music-23", category: "Musik", prompt: "Vilken artist låg bakom albumet 21?", answer: "Adele", promptEn: "Which artist was behind the album 21?", answerEn: "Adele" },
  { id: "music-24", category: "Musik", prompt: "Vad kallas den kvinnliga sångrösten mellan mezzosopran och alt i körsammanhang?", answer: "Alt", promptEn: "In a choir, what is the lowest female voice part, below mezzo-soprano, called?", answerEn: "Alto" },
  { id: "music-25", category: "Musik", prompt: "Vilket band gav ut låten Bohemian Rhapsody?", answer: "Queen", promptEn: "Which band released the song Bohemian Rhapsody?", answerEn: "Queen" },
  { id: "music-26", category: "Musik", prompt: "Vad heter den svenska tävling som utser Sveriges bidrag till Eurovision?", answer: "Melodifestivalen", promptEn: "What is the Swedish competition that selects Sweden's Eurovision entry called?", answerEn: "Melodifestivalen" },
  { id: "music-27", category: "Musik", prompt: "Vilken artist kallades The Material Girl?", answer: "Madonna", promptEn: "Which artist was called The Material Girl?", answerEn: "Madonna" },
  { id: "music-28", category: "Musik", prompt: "Vilken genre förknippas med artister som Louis Armstrong och Ella Fitzgerald?", answer: "Jazz", promptEn: "Which genre is associated with artists such as Louis Armstrong and Ella Fitzgerald?", answerEn: "Jazz" },
  { id: "music-29", category: "Musik", prompt: "Vad heter symbolen som höjer en ton ett halvt tonsteg?", answer: "Korsförtecken", promptEn: "What is the symbol that raises a note by a semitone called?", answerEn: "Sharp" },
  { id: "music-30", category: "Musik", prompt: "Vilket band hade medlemmarna John Lennon, Paul McCartney, George Harrison och Ringo Starr?", answer: "The Beatles", promptEn: "Which band had the members John Lennon, Paul McCartney, George Harrison and Ringo Starr?", answerEn: "The Beatles" },
  { id: "music-31", category: "Musik", prompt: "Vilken svensk artist slog igenom internationellt med låten Habits?", answer: "Tove Lo", promptEn: "Which Swedish artist broke through internationally with the song Habits?", answerEn: "Tove Lo" },
  { id: "music-32", category: "Musik", prompt: "Vad heter den låga manliga sångrösten under baryton?", answer: "Bas", promptEn: "What is the low male singing voice below baritone called?", answerEn: "Bass" },
  { id: "music-33", category: "Musik", prompt: "Vilken amerikansk artist kallades ofta The Boss?", answer: "Bruce Springsteen", promptEn: "Which American artist was often called The Boss?", answerEn: "Bruce Springsteen" },
  { id: "music-34", category: "Musik", prompt: "Vilket instrument är känt för att ha 88 tangenter?", answer: "Piano", promptEn: "Which instrument is known for having 88 keys?", answerEn: "Piano" },
  { id: "music-35", category: "Musik", prompt: "Vad heter den klassiska musikperiod som kom efter barocken och före romantiken?", answer: "Wienklassicismen", promptEn: "What is the classical music period that came after the Baroque and before the Romantic era called?", answerEn: "The Classical period (Viennese Classicism)" },
  { id: "music-36", category: "Musik", prompt: "Vilken artist släppte albumet Thriller?", answer: "Michael Jackson", promptEn: "Which artist released the album Thriller?", answerEn: "Michael Jackson" },
  { id: "music-37", category: "Musik", prompt: "Vad kallas en ensam sång- eller instrumentalinsats i ett större verk?", answer: "Solo", promptEn: "What is a performance by a single singer or instrumentalist within a larger work called?", answerEn: "Solo" },
  { id: "music-38", category: "Musik", prompt: "Vilken svensk artist vann Eurovision 2012 med låten Euphoria?", answer: "Loreen", promptEn: "Which Swedish artist won Eurovision 2012 with the song Euphoria?", answerEn: "Loreen" },
  { id: "music-39", category: "Musik", prompt: "Vilket instrument har ventiler och förknippas starkt med jazz och blåsorkestrar?", answer: "Trumpet", promptEn: "Which instrument has valves and is strongly associated with jazz and brass bands?", answerEn: "Trumpet" },
  { id: "music-40", category: "Musik", prompt: "Vilket band gav ut albumet Nevermind?", answer: "Nirvana", promptEn: "Which band released the album Nevermind?", answerEn: "Nirvana" },
  { id: "music-41", category: "Musik", prompt: "Vad heter den italienska termen för att spela mycket starkt?", answer: "Fortissimo", promptEn: "What is the Italian term for playing very loudly?", answerEn: "Fortissimo" },
  { id: "music-42", category: "Musik", prompt: "Vilken artist är känd som Rocket Man efter sin låt med samma namn?", answer: "Elton John", promptEn: "Which artist is known as Rocket Man after his song of the same name?", answerEn: "Elton John" },
  { id: "music-43", category: "Musik", prompt: "Vilken musikgenre växte fram i Jamaica och förknippas med Bob Marley?", answer: "Reggae", promptEn: "Which music genre emerged in Jamaica and is associated with Bob Marley?", answerEn: "Reggae" },
  { id: "music-44", category: "Musik", prompt: "Vad heter notsystemets fem horisontella linjer tillsammans?", answer: "Notlinjer", promptEn: "What are the five horizontal lines of musical notation called together?", answerEn: "Staff (stave)" },
  { id: "music-45", category: "Musik", prompt: "Vilken tonsättare skrev operan Carmen?", answer: "Georges Bizet", promptEn: "Which composer wrote the opera Carmen?", answerEn: "Georges Bizet" },
  { id: "music-46", category: "Musik", prompt: "Vilken artist låg bakom albumet Back to Black?", answer: "Amy Winehouse", promptEn: "Which artist was behind the album Back to Black?", answerEn: "Amy Winehouse" },
  { id: "music-47", category: "Musik", prompt: "Vad heter det svenska popbandet bakom låten It Takes a Fool to Remain Sane?", answer: "The Ark", promptEn: "What is the Swedish pop band behind the song It Takes a Fool to Remain Sane called?", answerEn: "The Ark" },
  { id: "music-48", category: "Musik", prompt: "Vilken artist hade hiten Rolling in the Deep?", answer: "Adele", promptEn: "Which artist had the hit Rolling in the Deep?", answerEn: "Adele" },
  { id: "music-49", category: "Musik", prompt: "Vilken del av ett trumset slås ofta med fotpedal och står längst ner?", answer: "Bastrumma", promptEn: "Which part of a drum kit is usually played with a foot pedal and sits at the bottom?", answerEn: "Bass drum" },
  { id: "music-50", category: "Musik", prompt: "Vad kallas ett verk för en ensam solist och orkester?", answer: "Konsert", promptEn: "What is a work for a single soloist and orchestra called?", answerEn: "Concerto" },

  { id: "nature-1", category: "Natur", prompt: "Vad kallas ett träd som tappar sina blad på hösten?", answer: "Lövträd", promptEn: "What is a tree that loses its leaves in autumn called?", answerEn: "Deciduous tree" },
  { id: "nature-2", category: "Natur", prompt: "Vilket är jordens största djur?", answer: "Blå valen", promptEn: "What is the largest animal on Earth?", answerEn: "Blue whale" },
  { id: "nature-3", category: "Natur", prompt: "Vad heter den process där växter gör syre av solljus?", answer: "Fotosyntes", promptEn: "What is the process in which plants produce oxygen using sunlight called?", answerEn: "Photosynthesis" },
  { id: "nature-4", category: "Natur", prompt: "Vilket djur är känt som djungelns konung?", answer: "Lejon", promptEn: "Which animal is known as the king of the jungle?", answerEn: "Lion" },
  { id: "nature-5", category: "Natur", prompt: "Vad heter en grupp vargar tillsammans?", answer: "Flock", promptEn: "What is a group of wolves called?", answerEn: "Pack" },
  { id: "nature-6", category: "Natur", prompt: "Vilken årstid kommer efter sommaren?", answer: "Höst", promptEn: "Which season comes after summer?", answerEn: "Autumn" },
  { id: "nature-7", category: "Natur", prompt: "Vilket djur bygger dammar av träd och grenar?", answer: "Bäver", promptEn: "Which animal builds dams out of trees and branches?", answerEn: "Beaver" },
  { id: "nature-8", category: "Natur", prompt: "Vad heter vatten i frusen form?", answer: "Is", promptEn: "What is water in frozen form called?", answerEn: "Ice" },
  { id: "nature-9", category: "Natur", prompt: "Vilken del av blomman utvecklas till frukt efter befruktning?", answer: "Fruktämnet", promptEn: "Which part of the flower develops into fruit after fertilisation?", answerEn: "The ovary" },
  { id: "nature-10", category: "Natur", prompt: "Vad kallas läran om svampar?", answer: "Mykologi", promptEn: "What is the study of fungi called?", answerEn: "Mycology" },
  { id: "nature-11", category: "Natur", prompt: "Vilket däggdjur kan flyga aktivt utan att bara glidflyga?", answer: "Fladdermus", promptEn: "Which mammal can actively fly rather than just glide?", answerEn: "Bat" },
  { id: "nature-12", category: "Natur", prompt: "Vad heter den geologiska process där jordskorpans plattor rör sig?", answer: "Plattektonik", promptEn: "What is the geological process in which the plates of the Earth's crust move called?", answerEn: "Plate tectonics" },
  { id: "nature-13", category: "Natur", prompt: "Vilken typ av moln förknippas ofta med åskväder?", answer: "Cumulonimbus", promptEn: "Which type of cloud is often associated with thunderstorms?", answerEn: "Cumulonimbus" },
  { id: "nature-14", category: "Natur", prompt: "Vilket träslag kommer kork från?", answer: "Korkek", promptEn: "Which tree does cork come from?", answerEn: "Cork oak" },
  { id: "nature-15", category: "Natur", prompt: "Vad heter världens största regnskog?", answer: "Amazonas regnskog", promptEn: "What is the world's largest rainforest called?", answerEn: "The Amazon rainforest" },
  { id: "nature-16", category: "Natur", prompt: "Vilket ämne i barrträd ger den typiska doften och kan användas för att göra terpentin?", answer: "Kåda", promptEn: "Which substance in conifers gives them their typical scent and can be used to make turpentine?", answerEn: "Resin" },
  { id: "nature-17", category: "Natur", prompt: "Vad kallas en djurart som bara finns naturligt inom ett begränsat område?", answer: "Endemisk art", promptEn: "What is a species that occurs naturally only within a limited area called?", answerEn: "Endemic species" },
  { id: "nature-18", category: "Natur", prompt: "Vilket naturfenomen mäts med Richterskalan eller momentmagnitudskalan?", answer: "Jordbävning", promptEn: "Which natural phenomenon is measured on the Richter scale or the moment magnitude scale?", answerEn: "Earthquake" },
  { id: "nature-19", category: "Natur", prompt: "Vilken fågel är Sveriges nationalfågel?", answer: "Koltrast", promptEn: "Which bird is Sweden's national bird?", answerEn: "Blackbird" },
  { id: "nature-20", category: "Natur", prompt: "Vad kallas den zon i havet där solljuset fortfarande når ner tillräckligt för fotosyntes?", answer: "Den fotiska zonen", promptEn: "What is the zone of the ocean where sunlight still reaches far enough for photosynthesis called?", answerEn: "The photic zone" },
  { id: "nature-21", category: "Natur", prompt: "Vad heter den största kattarten i världen?", answer: "Tiger", promptEn: "What is the largest cat species in the world?", answerEn: "Tiger" },
  { id: "nature-22", category: "Natur", prompt: "Vilket djur är känt för att kunna byta färg snabbt för kamouflage?", answer: "Kameleont", promptEn: "Which animal is known for being able to change colour quickly for camouflage?", answerEn: "Chameleon" },
  { id: "nature-23", category: "Natur", prompt: "Vad kallas övergången från larv till vuxen insekt i flera steg?", answer: "Metamorfos", promptEn: "What is the transformation from larva to adult insect in several stages called?", answerEn: "Metamorphosis" },
  { id: "nature-24", category: "Natur", prompt: "Vilken typ av skog dominerar stora delar av norra Sverige och Finland?", answer: "Barrskog", promptEn: "Which type of forest dominates large parts of northern Sweden and Finland?", answerEn: "Coniferous forest" },
  { id: "nature-25", category: "Natur", prompt: "Vad heter den största björnarten på land?", answer: "Isbjörn", promptEn: "What is the largest bear species on land?", answerEn: "Polar bear" },
  { id: "nature-26", category: "Natur", prompt: "Vilken stenart bildas när lava svalnar snabbt ovan jord?", answer: "Vulkanisk bergart", promptEn: "Which type of rock forms when lava cools quickly above ground?", answerEn: "Volcanic rock" },
  { id: "nature-27", category: "Natur", prompt: "Vad kallas en grupp fiskar som simmar tillsammans?", answer: "Stim", promptEn: "What is a group of fish swimming together called?", answerEn: "School (shoal)" },
  { id: "nature-28", category: "Natur", prompt: "Vilket grundämne är viktigast för växters klorofyll och ger bladen deras gröna färg indirekt genom molekylen?", answer: "Magnesium", promptEn: "Which element is at the centre of the chlorophyll molecule that gives plant leaves their green colour?", answerEn: "Magnesium" },
  { id: "nature-29", category: "Natur", prompt: "Vilken typ av nederbörd bildas av iskristaller i moln och faller som flingor?", answer: "Snö", promptEn: "Which type of precipitation forms from ice crystals in clouds and falls as flakes?", answerEn: "Snow" },
  { id: "nature-30", category: "Natur", prompt: "Vad heter den period varje år då renar och många andra hjortdjur parar sig?", answer: "Brunst", promptEn: "What is the period each year when reindeer and many other deer mate called?", answerEn: "Rut" },
  { id: "nature-31", category: "Natur", prompt: "Vilket djur förknippas med nässeldjur och har tentakler som kan brännas?", answer: "Manet", promptEn: "Which animal belongs to the cnidarians and has tentacles that can sting?", answerEn: "Jellyfish" },
  { id: "nature-32", category: "Natur", prompt: "Vad kallas ett område där sötvatten möter saltvatten, till exempel vid flodmynningar?", answer: "Estuarium", promptEn: "What is an area where fresh water meets salt water, for example at a river mouth, called?", answerEn: "Estuary" },
  { id: "nature-33", category: "Natur", prompt: "Vilket djur är världens snabbaste på land?", answer: "Gepard", promptEn: "Which animal is the fastest on land?", answerEn: "Cheetah" },
  { id: "nature-34", category: "Natur", prompt: "Vad heter det tunna lagret av gaser som omger jorden?", answer: "Atmosfären", promptEn: "What is the thin layer of gases that surrounds the Earth called?", answerEn: "The atmosphere" },
  { id: "nature-35", category: "Natur", prompt: "Vilken typ av djur är en axolotl?", answer: "Salamander", promptEn: "What type of animal is an axolotl?", answerEn: "Salamander" },
  { id: "nature-36", category: "Natur", prompt: "Vad kallas de enorma vågor som kan uppstå efter jordbävningar under havsytan?", answer: "Tsunami", promptEn: "What are the huge waves that can be caused by earthquakes under the sea called?", answerEn: "Tsunami" },
  { id: "nature-37", category: "Natur", prompt: "Vilken fågel är känd för att kunna stå stilla i luften medan den spanar efter byte?", answer: "Tornfalk", promptEn: "Which bird is known for hovering still in the air while it looks for prey?", answerEn: "Kestrel" },
  { id: "nature-38", category: "Natur", prompt: "Vad heter den biologiska relation där båda arterna gynnas?", answer: "Mutualism", promptEn: "What is the biological relationship in which both species benefit called?", answerEn: "Mutualism" },
  { id: "nature-39", category: "Natur", prompt: "Vilken typ av djur är blåvalen trots sitt namn?", answer: "Däggdjur", promptEn: "What type of animal is the blue whale, despite being called a whale?", answerEn: "Mammal" },
  { id: "nature-40", category: "Natur", prompt: "Vad kallas området i ett träd där årsringarna bildas och transport sker?", answer: "Kambium", promptEn: "What is the layer in a tree where the annual rings are formed called?", answerEn: "Cambium" },
  { id: "nature-41", category: "Natur", prompt: "Vilken naturtyp kännetecknas av permanent frusen mark som kallas permafrost?", answer: "Tundra", promptEn: "Which type of landscape is characterised by permanently frozen ground called permafrost?", answerEn: "Tundra" },
  { id: "nature-42", category: "Natur", prompt: "Vad heter den punkt då vattenånga övergår till flytande vatten i luften och dagg kan bildas?", answer: "Daggpunkt", promptEn: "What is the temperature at which water vapour in the air turns into liquid water and dew can form called?", answerEn: "Dew point" },
  { id: "nature-43", category: "Natur", prompt: "Vilket djur kallas ibland naturens ingenjör eftersom det bygger stora dammar och förändrar landskapet?", answer: "Bäver", promptEn: "Which animal is sometimes called nature's engineer because it builds large dams and changes the landscape?", answerEn: "Beaver" },
  { id: "nature-44", category: "Natur", prompt: "Vad kallas den hårda yttre delen hos många insekter och kräftdjur?", answer: "Exoskelett", promptEn: "What is the hard outer shell of many insects and crustaceans called?", answerEn: "Exoskeleton" },
  { id: "nature-45", category: "Natur", prompt: "Vilken stor katt är bäst anpassad till kyla och höga berg i Centralasien?", answer: "Snöleopard", promptEn: "Which big cat is best adapted to the cold and the high mountains of Central Asia?", answerEn: "Snow leopard" },
  { id: "nature-46", category: "Natur", prompt: "Vad heter den process då bergarter bryts ner av vind, vatten och temperaturväxlingar?", answer: "Vittring", promptEn: "What is the process in which rocks are broken down by wind, water and temperature changes called?", answerEn: "Weathering" },
  { id: "nature-47", category: "Natur", prompt: "Vilken typ av växtlighet dominerar i en savann?", answer: "Gräs", promptEn: "Which type of vegetation dominates a savanna?", answerEn: "Grass" },
  { id: "nature-48", category: "Natur", prompt: "Vad heter de glödande partiklar som ses på himlen när solvinden träffar jordens magnetfält?", answer: "Norrsken", promptEn: "What are the glowing lights seen in the sky when the solar wind hits the Earth's magnetic field called?", answerEn: "Northern lights (aurora)" },
  { id: "nature-49", category: "Natur", prompt: "Vilket havsdjur har tre hjärtan och blått blod?", answer: "Bläckfisk", promptEn: "Which sea creature has three hearts and blue blood?", answerEn: "Octopus" },
  { id: "nature-50", category: "Natur", prompt: "Vad kallas det när en art dör ut helt från jorden?", answer: "Utdöende", promptEn: "What is it called when a species dies out completely from the Earth?", answerEn: "Extinction" },
];

export function buildTriviaDeck(selectedCategories: TriviaCategory[], questionsPerPlayer: number, playerCount: number) {
  const allowed = TRIVIA_QUESTIONS.filter((question) => selectedCategories.includes(question.category));
  const targetCount = questionsPerPlayer * playerCount;

  if (allowed.length === 0) {
    return [];
  }

  const deck: TriviaQuestion[] = [];

  while (deck.length < targetCount) {
    const source = shuffleQuestions(allowed);
    for (const question of source) {
      if (deck.length >= targetCount) {
        break;
      }
      deck.push(question);
    }
  }

  return deck;
}

function shuffleQuestions(input: TriviaQuestion[]) {
  const copy = [...input];
  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }
  return copy;
}

let questionsBySwedishPrompt: Map<string, TriviaQuestion> | null = null;

/**
 * Turns store the Swedish question/answer text. Look the question up by its Swedish
 * prompt and return the text in the player's language (falls back to the stored text).
 */
export function localizeTriviaTurn(questionText: string, answerText: string, language: TriviaLanguage) {
  if (language !== "en") {
    return { question: questionText, answer: answerText };
  }
  if (!questionsBySwedishPrompt) {
    questionsBySwedishPrompt = new Map(TRIVIA_QUESTIONS.map((question) => [question.prompt.trim(), question]));
  }
  const match = questionsBySwedishPrompt.get(questionText.trim());
  if (!match) {
    return { question: questionText, answer: answerText };
  }
  return { question: match.promptEn, answer: match.answerEn };
}
