export type TriviaCategory =
  | "Mat"
  | "Film"
  | "Geografi"
  | "Historia"
  | "Sport"
  | "Vetenskap"
  | "Musik"
  | "Natur";

export type TriviaQuestion = {
  id: string;
  category: TriviaCategory;
  prompt: string;
  answer: string;
};

export const TRIVIA_CATEGORIES: TriviaCategory[] = [
  "Mat",
  "Film",
  "Geografi",
  "Historia",
  "Sport",
  "Vetenskap",
  "Musik",
  "Natur",
];

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  { id: "mat-1", category: "Mat", prompt: "Vilket land är ursprunget till pizza margherita?", answer: "Italien" },
  { id: "mat-2", category: "Mat", prompt: "Vad heter den japanska rätten med vinägerat ris och ofta fisk?", answer: "Sushi" },
  { id: "mat-3", category: "Mat", prompt: "Vilken frukt är huvudingrediensen i guacamole?", answer: "Avokado" },
  { id: "mat-4", category: "Mat", prompt: "Vad kallas en fransk tunn pannkaka?", answer: "Crêpe" },
  { id: "mat-5", category: "Mat", prompt: "Vilken ost används ofta på grekisk sallad?", answer: "Fetaost" },
  { id: "mat-6", category: "Mat", prompt: "Vilken dryck gör man oftast av malt, humle, jäst och vatten?", answer: "Öl" },
  { id: "mat-7", category: "Mat", prompt: "Vad heter den italienska efterrätten med kaffe och mascarpone?", answer: "Tiramisu" },
  { id: "mat-8", category: "Mat", prompt: "Vilken krydda ger gul färg till mycket curry och risrätter?", answer: "Gurkmeja" },
  { id: "mat-9", category: "Mat", prompt: "Vilken sås är huvudingrediens i klassisk eggs benedict tillsammans med pocherat ägg?", answer: "Hollandaisesås" },
  { id: "mat-10", category: "Mat", prompt: "Vad heter den spanska risrätten som ofta innehåller saffran och skaldjur?", answer: "Paella" },
  { id: "mat-11", category: "Mat", prompt: "Vilken nöt används traditionellt för att göra pesto alla genovese?", answer: "Pinjenöt" },
  { id: "mat-12", category: "Mat", prompt: "Vilket land förknippas starkast med rätten gulasch?", answer: "Ungern" },
  { id: "mat-13", category: "Mat", prompt: "Vad heter den koreanska fermenterade kål-rätten som ofta serveras som tillbehör?", answer: "Kimchi" },
  { id: "mat-14", category: "Mat", prompt: "Vilken fiskrom används traditionellt i rysk kaviar från stör?", answer: "Störrom" },
  { id: "mat-15", category: "Mat", prompt: "Vad kallas den franska matlagningstermen när man tillagar i vakuum vid låg temperatur?", answer: "Sous vide" },
  { id: "mat-16", category: "Mat", prompt: "Vilken typ av deg används traditionellt till italiensk focaccia?", answer: "Jästdeg" },
  { id: "mat-17", category: "Mat", prompt: "Vilket mjöl används oftast till polenta?", answer: "Majsmjöl" },
  { id: "mat-18", category: "Mat", prompt: "Vad heter den japanska nudelsoppan med misobuljong som ofta serveras med fläsk?", answer: "Ramen" },
  { id: "mat-19", category: "Mat", prompt: "Vilken fransk moder-sås bygger på mjölk, smör och vetemjöl?", answer: "Béchamelsås" },
  { id: "mat-20", category: "Mat", prompt: "Vad heter den indiska ugnen som används för naan och tandoorirätter?", answer: "Tandoor" },
  { id: "mat-21", category: "Mat", prompt: "Vilken citrusfrukt används ofta i key lime pie?", answer: "Lime" },
  { id: "mat-22", category: "Mat", prompt: "Vad heter den mexikanska rätten där tortilla ofta fylls och rullas ihop?", answer: "Burrito" },
  { id: "mat-23", category: "Mat", prompt: "Vilken ost används traditionellt i italiensk risotto alla milanese tillsammans med saffran?", answer: "Parmesan" },
  { id: "mat-24", category: "Mat", prompt: "Vad kallas det när man snabbt kokar grönsaker och sedan kyler dem i isvatten?", answer: "Blanchera" },
  { id: "mat-25", category: "Mat", prompt: "Vilket bär används i en klassisk svensk drottningsylt tillsammans med blåbär?", answer: "Hallon" },
  { id: "mat-26", category: "Mat", prompt: "Vad heter den italienska lufttorkade skinkan från Parma?", answer: "Prosciutto" },
  { id: "mat-27", category: "Mat", prompt: "Vilken baljväxt är huvudingrediens i hummus?", answer: "Kikärta" },
  { id: "mat-28", category: "Mat", prompt: "Vilken delikatess framställs av gås- eller anklever?", answer: "Foie gras" },
  { id: "mat-29", category: "Mat", prompt: "Vad heter den tunna japanska nudeln gjord på bovete?", answer: "Soba" },
  { id: "mat-30", category: "Mat", prompt: "Vilken dessert består av maräng, grädde och ofta bär eller frukt?", answer: "Pavlova" },
  { id: "mat-31", category: "Mat", prompt: "Vilken rotfrukt används för att göra chips med smaken salt and vinegar om de är gjorda på grönsak i stället för potatis?", answer: "Palsternacka" },
  { id: "mat-32", category: "Mat", prompt: "Vad heter den marockanska grytan som också gett namn åt kokkärlet?", answer: "Tagine" },
  { id: "mat-33", category: "Mat", prompt: "Vilken typ av vin används oftast i rätten coq au vin?", answer: "Rödvin" },
  { id: "mat-34", category: "Mat", prompt: "Vad heter den spanska kallserverade tomatsoppan?", answer: "Gazpacho" },
  { id: "mat-35", category: "Mat", prompt: "Vilken nöt dominerar i nougat enligt medelhavstradition?", answer: "Hasselnöt" },
  { id: "mat-36", category: "Mat", prompt: "Vad heter den franska potatisgratängen som tillagas med grädde och vitlök?", answer: "Gratin dauphinois" },
  { id: "mat-37", category: "Mat", prompt: "Vilken fransk kaka görs traditionellt upp och ned med karamelliserade äpplen?", answer: "Tarte tatin" },
  { id: "mat-38", category: "Mat", prompt: "Vad heter den kinesiska kryddblandningen som ofta innehåller stjärnanis, kanel och nejlika?", answer: "Five spice" },
  { id: "mat-39", category: "Mat", prompt: "Vilken ostmassa används som bas i indisk paneer?", answer: "Färskost" },
  { id: "mat-40", category: "Mat", prompt: "Vilken svamp anses särskilt exklusiv och växer ofta under jord nära trädens rötter?", answer: "Tryffel" },
  { id: "mat-41", category: "Mat", prompt: "Vad heter den tunna italienska efterrättskakan som betyder ungefär 'dubbelt kokt'?", answer: "Biscotti" },
  { id: "mat-42", category: "Mat", prompt: "Vilket asiatiskt land är ursprunget till rätten pho?", answer: "Vietnam" },
  { id: "mat-43", category: "Mat", prompt: "Vilken ört ger bearnaisesås sin tydliga klassiska smak?", answer: "Dragon" },
  { id: "mat-44", category: "Mat", prompt: "Vad heter den spanska lufttorkade skinkan från svartfotssvin som räknas som extra exklusiv?", answer: "Jamón ibérico" },
  { id: "mat-45", category: "Mat", prompt: "Vilken ost används oftast i en klassisk caprese tillsammans med tomat och basilika?", answer: "Mozzarella" },
  { id: "mat-46", category: "Mat", prompt: "Vad kallas de små italienska potatisdumplingarna?", answer: "Gnocchi" },
  { id: "mat-47", category: "Mat", prompt: "Vilken ingrediens ger ceviche dess tillagade känsla utan värme?", answer: "Citrusjuice" },
  { id: "mat-48", category: "Mat", prompt: "Vad heter den japanska friteringsmetoden med lätt, frasigt frityrsmet?", answer: "Tempura" },
  { id: "mat-49", category: "Mat", prompt: "Vilken del av vaniljväxten används som krydda i matlagning och bakning?", answer: "Vaniljstång" },
  { id: "mat-50", category: "Mat", prompt: "Vad kallas den franska matlagningstermer för 'allt på plats' innan tillagning?", answer: "Mise en place" },

  { id: "film-1", category: "Film", prompt: "Vilken filmserie handlar om trollkarlen Harry Potter?", answer: "Harry Potter" },
  { id: "film-2", category: "Film", prompt: "Vad heter lejonungen i Disneys The Lion King?", answer: "Simba" },
  { id: "film-3", category: "Film", prompt: "Vilken film har repliken 'I'll be back'?", answer: "The Terminator" },
  { id: "film-4", category: "Film", prompt: "Vilken film vann Oscar för bästa film 1998 och handlar om ett stort skepp?", answer: "Titanic" },
  { id: "film-5", category: "Film", prompt: "Vad heter clownfisken i Hitta Nemo?", answer: "Nemo" },
  { id: "film-6", category: "Film", prompt: "Vilken superhjälte är alter egot till Bruce Wayne?", answer: "Batman" },
  { id: "film-7", category: "Film", prompt: "I vilken science fiction-film är Darth Vader en central figur?", answer: "Star Wars" },
  { id: "film-8", category: "Film", prompt: "Vad heter ogret i DreamWorks filmserie med samma namn?", answer: "Shrek" },
  { id: "film-9", category: "Film", prompt: "Vem regisserade filmen Inception?", answer: "Christopher Nolan" },
  { id: "film-10", category: "Film", prompt: "Vilken film från 1999 handlar om Neo, Morpheus och en simulerad verklighet?", answer: "The Matrix" },
  { id: "film-11", category: "Film", prompt: "Vad heter ringenas skapare i Sagan om ringen-universumet?", answer: "Sauron" },
  { id: "film-12", category: "Film", prompt: "Vilken skådespelare spelade Jokern i The Dark Knight?", answer: "Heath Ledger" },
  { id: "film-13", category: "Film", prompt: "Vilken film av Bong Joon-ho vann Oscar för bästa film 2020?", answer: "Parasite" },
  { id: "film-14", category: "Film", prompt: "Vad heter hotellet i Stanley Kubricks The Shining?", answer: "Overlook Hotel" },
  { id: "film-15", category: "Film", prompt: "Vilken regissör ligger bakom Pulp Fiction?", answer: "Quentin Tarantino" },
  { id: "film-16", category: "Film", prompt: "Vad heter huvudpersonen som spelas av Russell Crowe i Gladiator?", answer: "Maximus" },
  { id: "film-17", category: "Film", prompt: "Vilken film har figurerna Woody och Buzz Lightyear?", answer: "Toy Story" },
  { id: "film-18", category: "Film", prompt: "Vilken svensk skådespelare spelade It i filmerna baserade på Stephen Kings bok?", answer: "Bill Skarsgård" },
  { id: "film-19", category: "Film", prompt: "Vilken film vann första Oscarsstatyetten för bästa animerade långfilm 2002?", answer: "Shrek" },
  { id: "film-20", category: "Film", prompt: "Vad heter planeten där mycket av handlingen i Avatar utspelar sig?", answer: "Pandora" },
  { id: "film-21", category: "Film", prompt: "Vilken film av Steven Spielberg handlar om en haj som terroriserar en badort?", answer: "Hajen" },
  { id: "film-22", category: "Film", prompt: "Vad heter den kvinnliga huvudrollen i Pretty Woman?", answer: "Vivian" },
  { id: "film-23", category: "Film", prompt: "Vilken filmserie innehåller figuren Ethan Hunt?", answer: "Mission: Impossible" },
  { id: "film-24", category: "Film", prompt: "Vem regisserade E.T. the Extra-Terrestrial?", answer: "Steven Spielberg" },
  { id: "film-25", category: "Film", prompt: "Vad heter den fiktiva afrikanska nationen i Black Panther?", answer: "Wakanda" },
  { id: "film-26", category: "Film", prompt: "Vilken film från 1994 handlar om Andy Dufresne i ett fängelse?", answer: "Nyckeln till frihet" },
  { id: "film-27", category: "Film", prompt: "Vad heter regissören bakom Pans labyrint och The Shape of Water?", answer: "Guillermo del Toro" },
  { id: "film-28", category: "Film", prompt: "Vilken film har figuren Jack Sparrow?", answer: "Pirates of the Caribbean" },
  { id: "film-29", category: "Film", prompt: "Vilken skådespelare spelade huvudrollen i filmen Forrest Gump?", answer: "Tom Hanks" },
  { id: "film-30", category: "Film", prompt: "Vad heter den koreanska filmen från 2003 där huvudpersonen söker hämnd efter lång fångenskap?", answer: "Oldboy" },
  { id: "film-31", category: "Film", prompt: "Vilken Disneyfilm utspelar sig i kungariket Arendal?", answer: "Frost" },
  { id: "film-32", category: "Film", prompt: "Vad heter den imaginära vännen i filmen Fight Club enligt huvudpersonens senare insikt?", answer: "Tyler Durden" },
  { id: "film-33", category: "Film", prompt: "Vilken regissör gjorde filmerna Spirited Away och Min granne Totoro?", answer: "Hayao Miyazaki" },
  { id: "film-34", category: "Film", prompt: "Vad heter boxaren som Sylvester Stallone spelar i en klassisk filmserie?", answer: "Rocky Balboa" },
  { id: "film-35", category: "Film", prompt: "Vilken film från 2016 följer en lingvist som försöker kommunicera med utomjordingar?", answer: "Arrival" },
  { id: "film-36", category: "Film", prompt: "Vad heter karaktären som Keanu Reeves spelar i actionserien med samma namn?", answer: "John Wick" },
  { id: "film-37", category: "Film", prompt: "Vilken film av Francis Ford Coppola utspelar sig kring familjen Corleone?", answer: "Gudfadern" },
  { id: "film-38", category: "Film", prompt: "Vilken film vann Oscar för bästa film 2024?", answer: "Oppenheimer" },
  { id: "film-39", category: "Film", prompt: "Vad heter huvudroboten i Pixars film WALL-E?", answer: "WALL-E" },
  { id: "film-40", category: "Film", prompt: "Vilken film från 2014 följer en trummis och hans hänsynslöse lärare Fletcher?", answer: "Whiplash" },
  { id: "film-41", category: "Film", prompt: "Vad heter den klassiska stumfilmskomikern med plommonstop, käpp och mustasch?", answer: "Charlie Chaplin" },
  { id: "film-42", category: "Film", prompt: "Vilken film handlar om en nöjespark där dinosaurier återskapas genom DNA?", answer: "Jurassic Park" },
  { id: "film-43", category: "Film", prompt: "Vilken skådespelerska spelar huvudrollen i La La Land tillsammans med Ryan Gosling?", answer: "Emma Stone" },
  { id: "film-44", category: "Film", prompt: "Vad heter den första filmen i Marvel Cinematic Universe?", answer: "Iron Man" },
  { id: "film-45", category: "Film", prompt: "Vilken film regisserades av Greta Gerwig och blev en stor biosuccé 2023?", answer: "Barbie" },
  { id: "film-46", category: "Film", prompt: "Vad heter de små gula figurerna i Dumma mej?", answer: "Minions" },
  { id: "film-47", category: "Film", prompt: "Vilken film från 1991 vann fem stora Oscar, inklusive bästa film och bästa regi, och handlar om Hannibal Lecter?", answer: "När lammen tystnar" },
  { id: "film-48", category: "Film", prompt: "Vad heter den brittiske agenten med kodnummer 007?", answer: "James Bond" },
  { id: "film-49", category: "Film", prompt: "Vilken film av Denis Villeneuve är baserad på Frank Herberts science fiction-roman?", answer: "Dune" },
  { id: "film-50", category: "Film", prompt: "Vad heter filmen där Robin Williams spelar en inspirerande internatskolelärare?", answer: "Dead Poets Society" },

  { id: "geo-1", category: "Geografi", prompt: "Vad är Sveriges huvudstad?", answer: "Stockholm" },
  { id: "geo-2", category: "Geografi", prompt: "Vilken världsdel ligger Brasilien i?", answer: "Sydamerika" },
  { id: "geo-3", category: "Geografi", prompt: "Vilken stad är huvudstad i Frankrike?", answer: "Paris" },
  { id: "geo-4", category: "Geografi", prompt: "Vilket hav ligger mellan Sverige och Finland?", answer: "Östersjön" },
  { id: "geo-5", category: "Geografi", prompt: "Vilket land har formen av en stövel på kartan?", answer: "Italien" },
  { id: "geo-6", category: "Geografi", prompt: "Vilken är världens största ocean?", answer: "Stilla havet" },
  { id: "geo-7", category: "Geografi", prompt: "Vad heter Egyptens längsta flod?", answer: "Nilen" },
  { id: "geo-8", category: "Geografi", prompt: "Vilket land ligger direkt väst om Sverige?", answer: "Norge" },
  { id: "geo-9", category: "Geografi", prompt: "Vilken är Kanadas huvudstad?", answer: "Ottawa" },
  { id: "geo-10", category: "Geografi", prompt: "Vad heter världens högsta berg över havet?", answer: "Mount Everest" },
  { id: "geo-11", category: "Geografi", prompt: "Vilket land har flest invånare i Afrika?", answer: "Nigeria" },
  { id: "geo-12", category: "Geografi", prompt: "Vilken ö är den största i Medelhavet?", answer: "Sicilien" },
  { id: "geo-13", category: "Geografi", prompt: "Vad heter havet mellan Afrika och Arabiska halvön?", answer: "Röda havet" },
  { id: "geo-14", category: "Geografi", prompt: "Vilken stad är huvudstad i Australien?", answer: "Canberra" },
  { id: "geo-15", category: "Geografi", prompt: "Vad heter bergskedjan som sträcker sig längs västra Sydamerika?", answer: "Anderna" },
  { id: "geo-16", category: "Geografi", prompt: "Vilket land omger Lesotho helt och hållet?", answer: "Sydafrika" },
  { id: "geo-17", category: "Geografi", prompt: "Vilket sund skiljer Asien från Nordamerika?", answer: "Berings sund" },
  { id: "geo-18", category: "Geografi", prompt: "Vad heter Grönlands huvudstad?", answer: "Nuuk" },
  { id: "geo-19", category: "Geografi", prompt: "Vilken europeisk flod rinner genom Wien, Bratislava, Budapest och Belgrad?", answer: "Donau" },
  { id: "geo-20", category: "Geografi", prompt: "Vilket land har huvudstaden Ulaanbaatar?", answer: "Mongoliet" },
  { id: "geo-21", category: "Geografi", prompt: "Vilken stad är huvudstad i Portugal?", answer: "Lissabon" },
  { id: "geo-22", category: "Geografi", prompt: "Vilket land är världens största till ytan?", answer: "Ryssland" },
  { id: "geo-23", category: "Geografi", prompt: "Vad heter öknen som täcker stora delar av norra Afrika?", answer: "Sahara" },
  { id: "geo-24", category: "Geografi", prompt: "Vilket land har huvudstaden Reykjavik?", answer: "Island" },
  { id: "geo-25", category: "Geografi", prompt: "Vilken amerikansk delstat kallas The Sunshine State?", answer: "Florida" },
  { id: "geo-26", category: "Geografi", prompt: "Vad heter Japans högsta berg?", answer: "Fuji" },
  { id: "geo-27", category: "Geografi", prompt: "Vilket land delas i en nordlig och en sydlig del av den demilitariserade zonen?", answer: "Korea" },
  { id: "geo-28", category: "Geografi", prompt: "Vilken stad är huvudstad i Argentina?", answer: "Buenos Aires" },
  { id: "geo-29", category: "Geografi", prompt: "Vilket land har flest öar i världen enligt vanliga uppskattningar?", answer: "Sverige" },
  { id: "geo-30", category: "Geografi", prompt: "Vad heter sundet mellan Spanien och Marocko?", answer: "Gibraltarsundet" },
  { id: "geo-31", category: "Geografi", prompt: "Vilken stad är huvudstad i Kenya?", answer: "Nairobi" },
  { id: "geo-32", category: "Geografi", prompt: "Vilket land har huvudstaden Ljubljana?", answer: "Slovenien" },
  { id: "geo-33", category: "Geografi", prompt: "Vad heter den största öknen i Asien?", answer: "Gobiöknen" },
  { id: "geo-34", category: "Geografi", prompt: "Vilken flod rinner genom Paris?", answer: "Seine" },
  { id: "geo-35", category: "Geografi", prompt: "Vilken stad är huvudstad i Nya Zeeland?", answer: "Wellington" },
  { id: "geo-36", category: "Geografi", prompt: "Vilket land ligger mellan Frankrike och Spanien på Iberiska halvön?", answer: "Andorra" },
  { id: "geo-37", category: "Geografi", prompt: "Vad heter Afrikas högsta berg?", answer: "Kilimanjaro" },
  { id: "geo-38", category: "Geografi", prompt: "Vilket land har huvudstaden Bogotá?", answer: "Colombia" },
  { id: "geo-39", category: "Geografi", prompt: "Vilken sjö är världens största till ytan?", answer: "Kaspiska havet" },
  { id: "geo-40", category: "Geografi", prompt: "Vilken stad är huvudstad i Thailand?", answer: "Bangkok" },
  { id: "geo-41", category: "Geografi", prompt: "Vilket hav gränsar både till Jordanien och Israel men är egentligen en salt sjö?", answer: "Döda havet" },
  { id: "geo-42", category: "Geografi", prompt: "Vilket land har huvudstaden Tallinn?", answer: "Estland" },
  { id: "geo-43", category: "Geografi", prompt: "Vad heter halvön där Norge och Sverige ligger?", answer: "Skandinaviska halvön" },
  { id: "geo-44", category: "Geografi", prompt: "Vilken stad är huvudstad i Peru?", answer: "Lima" },
  { id: "geo-45", category: "Geografi", prompt: "Vilket land är helt omgivet av Italien och har Vatikanstaten som granne?", answer: "San Marino" },
  { id: "geo-46", category: "Geografi", prompt: "Vad heter den största ön i Karibien?", answer: "Kuba" },
  { id: "geo-47", category: "Geografi", prompt: "Vilken flod är längst i Sydamerika?", answer: "Amazonas" },
  { id: "geo-48", category: "Geografi", prompt: "Vilket land har huvudstaden Hanoi?", answer: "Vietnam" },
  { id: "geo-49", category: "Geografi", prompt: "Vad heter världens djupaste kända havsgrav?", answer: "Marianergraven" },
  { id: "geo-50", category: "Geografi", prompt: "Vilken stad är huvudstad i Marocko?", answer: "Rabat" },

  { id: "hist-1", category: "Historia", prompt: "Vilket århundrade började år 1701?", answer: "1700-talet" },
  { id: "hist-2", category: "Historia", prompt: "Vilket fartyg sjönk på sin jungfruresa 1912?", answer: "Titanic" },
  { id: "hist-3", category: "Historia", prompt: "Vilket land styrdes av faraoner i forntiden?", answer: "Egypten" },
  { id: "hist-4", category: "Historia", prompt: "Vilken mur föll 1989 och blev en symbol för kalla krigets slut?", answer: "Berlinmuren" },
  { id: "hist-5", category: "Historia", prompt: "Vem var Sveriges drottning som abdikerade 1654?", answer: "Drottning Kristina" },
  { id: "hist-6", category: "Historia", prompt: "Vad kallades perioden då människan använde stenredskap?", answer: "Stenåldern" },
  { id: "hist-7", category: "Historia", prompt: "Vilket imperium styrdes av Julius Caesar som general och ledare?", answer: "Romarriket" },
  { id: "hist-8", category: "Historia", prompt: "Vilket krig pågick mellan 1939 och 1945?", answer: "Andra världskriget" },
  { id: "hist-9", category: "Historia", prompt: "Vilken fransk ledare besegrades slutgiltigt vid Waterloo 1815?", answer: "Napoleon Bonaparte" },
  { id: "hist-10", category: "Historia", prompt: "Vad hette skeppet som förde pilgrimerna till Nordamerika 1620?", answer: "Mayflower" },
  { id: "hist-11", category: "Historia", prompt: "Vilken svensk kung stupade vid Lützen 1632?", answer: "Gustav II Adolf" },
  { id: "hist-12", category: "Historia", prompt: "Vad kallades återuppväckandet av konst och vetenskap i Europa mellan medeltiden och modern tid?", answer: "Renässansen" },
  { id: "hist-13", category: "Historia", prompt: "Vilken stad förstördes av vulkanutbrottet från Vesuvius år 79?", answer: "Pompeji" },
  { id: "hist-14", category: "Historia", prompt: "Vilket år inleddes den franska revolutionen med stormningen av Bastiljen?", answer: "1789" },
  { id: "hist-15", category: "Historia", prompt: "Vad hette dokumentet som begränsade den engelske kungens makt 1215?", answer: "Magna Carta" },
  { id: "hist-16", category: "Historia", prompt: "Vilken civilisation byggde Machu Picchu?", answer: "Inkariket" },
  { id: "hist-17", category: "Historia", prompt: "Vilken amerikansk president avskaffade slavarna genom Emancipation Proclamation?", answer: "Abraham Lincoln" },
  { id: "hist-18", category: "Historia", prompt: "Vad hette Sovjetunionens siste ledare?", answer: "Michail Gorbatjov" },
  { id: "hist-19", category: "Historia", prompt: "Vilken kinesisk dynasti räknas som den första kejsardynastin?", answer: "Qin-dynastin" },
  { id: "hist-20", category: "Historia", prompt: "Vilket fredsavtal avslutade första världskriget formellt 1919?", answer: "Versaillesfreden" },
  { id: "hist-21", category: "Historia", prompt: "Vilken upptäcktsresande förknippas med att ha nått Amerika 1492?", answer: "Christofer Columbus" },
  { id: "hist-22", category: "Historia", prompt: "Vad hette den engelska drottning som regerade under stora delar av 1800-talet?", answer: "Drottning Victoria" },
  { id: "hist-23", category: "Historia", prompt: "Vilken stad var centrum för det antika grekiska stadsstaten med Akropolis?", answer: "Aten" },
  { id: "hist-24", category: "Historia", prompt: "Vad kallades handelsvägen mellan Kina och Europa under antiken och medeltiden?", answer: "Sidenvägen" },
  { id: "hist-25", category: "Historia", prompt: "Vilken svensk kung kallades Karl den tolfte?", answer: "Karl XII" },
  { id: "hist-26", category: "Historia", prompt: "Vilket år föll Västromerska riket enligt traditionell historieskrivning?", answer: "476" },
  { id: "hist-27", category: "Historia", prompt: "Vad hette skeppet som exploderade i Havanna 1898 och bidrog till spansk-amerikanska kriget?", answer: "USS Maine" },
  { id: "hist-28", category: "Historia", prompt: "Vilken stad var delad i öst och väst under kalla kriget?", answer: "Berlin" },
  { id: "hist-29", category: "Historia", prompt: "Vad hette reformatorn som spikade upp sina teser i Wittenberg 1517?", answer: "Martin Luther" },
  { id: "hist-30", category: "Historia", prompt: "Vilket nordiskt land blev först med kvinnlig rösträtt i nationella val?", answer: "Finland" },
  { id: "hist-31", category: "Historia", prompt: "Vilket slag år 1066 gav Vilhelm Erövraren makten över England?", answer: "Slaget vid Hastings" },
  { id: "hist-32", category: "Historia", prompt: "Vad hette den österrikiske tronföljare vars mord utlöste första världskriget?", answer: "Franz Ferdinand" },
  { id: "hist-33", category: "Historia", prompt: "Vilken organisation grundades 1945 för att främja internationell fred och säkerhet?", answer: "FN" },
  { id: "hist-34", category: "Historia", prompt: "Vilket år landade människan på månen för första gången?", answer: "1969" },
  { id: "hist-35", category: "Historia", prompt: "Vilken egyptisk drottning hade relationer med både Julius Caesar och Marcus Antonius?", answer: "Kleopatra" },
  { id: "hist-36", category: "Historia", prompt: "Vad kallades den period i USA då alkohol var förbjudet genom lag?", answer: "Förbudstiden" },
  { id: "hist-37", category: "Historia", prompt: "Vilken stad förstördes av atombomben den 6 augusti 1945?", answer: "Hiroshima" },
  { id: "hist-38", category: "Historia", prompt: "Vilken civilisation är känd för städer som Tikal och Chichén Itzá?", answer: "Mayariket" },
  { id: "hist-39", category: "Historia", prompt: "Vad hette den sydafrikanske ledaren som satt fängslad länge och senare blev president?", answer: "Nelson Mandela" },
  { id: "hist-40", category: "Historia", prompt: "Vilken kung lät bygga slottet Versailles som symbol för fransk absolutism?", answer: "Ludvig XIV" },
  { id: "hist-41", category: "Historia", prompt: "Vilket imperium styrdes från Konstantinopel efter Västroms fall?", answer: "Bysantinska riket" },
  { id: "hist-42", category: "Historia", prompt: "Vad kallades rymdkapplöpningen mellan USA och Sovjetunionen under kalla kriget?", answer: "Rymdkapplöpningen" },
  { id: "hist-43", category: "Historia", prompt: "Vilken svensk statsminister mördades 1986?", answer: "Olof Palme" },
  { id: "hist-44", category: "Historia", prompt: "Vilket havskrig 1571 stoppade i stor utsträckning Osmanska rikets expansion i Medelhavet?", answer: "Slaget vid Lepanto" },
  { id: "hist-45", category: "Historia", prompt: "Vad hette den stora pestepidemi som drabbade Europa på 1300-talet?", answer: "Digerdöden" },
  { id: "hist-46", category: "Historia", prompt: "Vilken stad var huvudstad i Östromerska riket och heter i dag Istanbul?", answer: "Konstantinopel" },
  { id: "hist-47", category: "Historia", prompt: "Vilket land koloniserade Brasilien?", answer: "Portugal" },
  { id: "hist-48", category: "Historia", prompt: "Vad hette freden 1648 som ofta markerar slutet på trettioåriga kriget?", answer: "Westfaliska freden" },
  { id: "hist-49", category: "Historia", prompt: "Vilken ideologisk konflikt dominerade relationen mellan USA och Sovjetunionen efter andra världskriget?", answer: "Kalla kriget" },
  { id: "hist-50", category: "Historia", prompt: "Vad hette den franska hjältinnan som ledde trupper under hundraårskriget och senare helgonförklarades?", answer: "Jeanne d'Arc" },

  { id: "sport-1", category: "Sport", prompt: "Hur många spelare har ett fotbollslag på planen samtidigt?", answer: "11" },
  { id: "sport-2", category: "Sport", prompt: "I vilken sport används racket och fjäderboll?", answer: "Badminton" },
  { id: "sport-3", category: "Sport", prompt: "Vad heter sporten där man gör strike och spare?", answer: "Bowling" },
  { id: "sport-4", category: "Sport", prompt: "Vilken sport förknippas starkast med Wimbledon?", answer: "Tennis" },
  { id: "sport-5", category: "Sport", prompt: "Hur många poäng är en vanlig korg värd i basket?", answer: "2" },
  { id: "sport-6", category: "Sport", prompt: "Vilken sport utövar man i Vasaloppet?", answer: "Längdskidor" },
  { id: "sport-7", category: "Sport", prompt: "Vad heter sporten där man surfar på snö?", answer: "Snowboard" },
  { id: "sport-8", category: "Sport", prompt: "Vilket land kommer fotbollsklubben FC Barcelona ifrån?", answer: "Spanien" },
  { id: "sport-9", category: "Sport", prompt: "Vilket land vann fotbolls-VM 2014 för herrar?", answer: "Tyskland" },
  { id: "sport-10", category: "Sport", prompt: "Vad heter den svenska stavhopparen som satt flera världsrekord under 2020-talet?", answer: "Armand Duplantis" },
  { id: "sport-11", category: "Sport", prompt: "Hur lång är en maratondistans i kilometer?", answer: "42,195 kilometer" },
  { id: "sport-12", category: "Sport", prompt: "Vilken sport utövas i turneringen Ryder Cup?", answer: "Golf" },
  { id: "sport-13", category: "Sport", prompt: "Vad kallas den högsta poängen i gymnastikens gamla tiopoängssystem?", answer: "Perfect 10" },
  { id: "sport-14", category: "Sport", prompt: "I vilken sport spelar man på arenor som kallas velodromer?", answer: "Bancykling" },
  { id: "sport-15", category: "Sport", prompt: "Vilken nation har vunnit flest herr-VM i ishockey genom tiderna om Sovjetunionen räknas separat?", answer: "Kanada" },
  { id: "sport-16", category: "Sport", prompt: "Vilket simtag är oftast snabbast i tävlingssimning?", answer: "Frisim" },
  { id: "sport-17", category: "Sport", prompt: "Vad heter pokalen som vinnaren av NHL-slutspelet får?", answer: "Stanley Cup" },
  { id: "sport-18", category: "Sport", prompt: "Vilken sport utövar man i tävlingen Tour de France?", answer: "Landsvägscykling" },
  { id: "sport-19", category: "Sport", prompt: "Hur många set måste man normalt vinna i en herrsingelfinal i Grand Slam-tennis?", answer: "Tre set" },
  { id: "sport-20", category: "Sport", prompt: "Vilken boxare var känd som The Greatest och hette Cassius Clay som ung?", answer: "Muhammad Ali" },
  { id: "sport-21", category: "Sport", prompt: "Vilken sport utövas i Allsvenskan?", answer: "Fotboll" },
  { id: "sport-22", category: "Sport", prompt: "Hur många hål spelas normalt i en golfrunda?", answer: "18" },
  { id: "sport-23", category: "Sport", prompt: "Vilken sport har positionerna pitcher, catcher och shortstop?", answer: "Baseball" },
  { id: "sport-24", category: "Sport", prompt: "Vad kallas det när man gör tre mål i samma match i fotboll eller ishockey?", answer: "Hat trick" },
  { id: "sport-25", category: "Sport", prompt: "Vilket land är känt för rugbylaget All Blacks?", answer: "Nya Zeeland" },
  { id: "sport-26", category: "Sport", prompt: "Vilken friidrottsgren innebär hopp över en horisontell ribba med hjälp av stav?", answer: "Stavhopp" },
  { id: "sport-27", category: "Sport", prompt: "I vilken sport tävlar man om att vinna gula tröjan i en tre veckor lång tävling i Frankrike?", answer: "Cykling" },
  { id: "sport-28", category: "Sport", prompt: "Vad kallas den serie i USA där lag som Lakers och Celtics spelar?", answer: "NBA" },
  { id: "sport-29", category: "Sport", prompt: "Vilken sport förknippas med tävlingen Davis Cup?", answer: "Tennis" },
  { id: "sport-30", category: "Sport", prompt: "Vad heter den stora internationella multisporttävlingen för vinteridrotter?", answer: "Vinter-OS" },
  { id: "sport-31", category: "Sport", prompt: "Hur många spelare per lag är på planen samtidigt i volleyboll?", answer: "6" },
  { id: "sport-32", category: "Sport", prompt: "Vilken svensk fotbollsspelare har spelat i klubbar som Ajax, Juventus, Inter, Barcelona, Milan och PSG?", answer: "Zlatan Ibrahimović" },
  { id: "sport-33", category: "Sport", prompt: "Vad heter den årliga amerikanska finalen i amerikansk fotboll?", answer: "Super Bowl" },
  { id: "sport-34", category: "Sport", prompt: "Vilken idrott utövas i rinken med sopande lagkamrater och en sten som glider på is?", answer: "Curling" },
  { id: "sport-35", category: "Sport", prompt: "Vad heter den snabbaste grenen i alpint där fart snarare än tekniska svängar står i centrum?", answer: "Störtlopp" },
  { id: "sport-36", category: "Sport", prompt: "I vilken sport används begreppet birdie?", answer: "Golf" },
  { id: "sport-37", category: "Sport", prompt: "Vilken nation förknippas starkast med sporten sumobrottning?", answer: "Japan" },
  { id: "sport-38", category: "Sport", prompt: "Hur många ringar finns i den olympiska symbolen?", answer: "5" },
  { id: "sport-39", category: "Sport", prompt: "Vad heter världens mest kända långlopp inom hundspann i Alaska?", answer: "Iditarod" },
  { id: "sport-40", category: "Sport", prompt: "Vilken sport utövar man i UFC?", answer: "MMA" },
  { id: "sport-41", category: "Sport", prompt: "Vilket land arrangerade sommar-OS 2016?", answer: "Brasilien" },
  { id: "sport-42", category: "Sport", prompt: "Vad heter den svenska skidorten där många alpina världscuptävlingar arrangeras?", answer: "Åre" },
  { id: "sport-43", category: "Sport", prompt: "I vilken sport finns termerna scrum och try?", answer: "Rugby" },
  { id: "sport-44", category: "Sport", prompt: "Hur många poäng är en touchdown värd i amerikansk fotboll innan extrapoäng?", answer: "6" },
  { id: "sport-45", category: "Sport", prompt: "Vad heter turneringen där Europas bästa fotbollsklubbar möts varje säsong?", answer: "Champions League" },
  { id: "sport-46", category: "Sport", prompt: "Vilken motorsport körs på banor som Monza, Silverstone och Suzuka?", answer: "Formel 1" },
  { id: "sport-47", category: "Sport", prompt: "Vad heter den jamaicanske sprintstjärnan som dominerade OS på 100 och 200 meter?", answer: "Usain Bolt" },
  { id: "sport-48", category: "Sport", prompt: "Vilken sport utövas i tävlingen America's Cup?", answer: "Segling" },
  { id: "sport-49", category: "Sport", prompt: "Hur många minuter är ordinarie speltid i en handbollsmatch för seniorer?", answer: "60 minuter" },
  { id: "sport-50", category: "Sport", prompt: "Vilken sport utövar man om man tävlar i decathlon?", answer: "Friidrott" },

  { id: "science-1", category: "Vetenskap", prompt: "Vilken planet är närmast solen i vårt solsystem?", answer: "Merkurius" },
  { id: "science-2", category: "Vetenskap", prompt: "Vad kallas H2O i vardagligt tal?", answer: "Vatten" },
  { id: "science-3", category: "Vetenskap", prompt: "Vilket organ pumpar runt blodet i kroppen?", answer: "Hjärtat" },
  { id: "science-4", category: "Vetenskap", prompt: "Vilken gas andas människan in för att överleva?", answer: "Syre" },
  { id: "science-5", category: "Vetenskap", prompt: "Vad heter kraften som drar saker mot jorden?", answer: "Gravitation" },
  { id: "science-6", category: "Vetenskap", prompt: "Vilket djur är det största landlevande djuret i dag?", answer: "Elefant" },
  { id: "science-7", category: "Vetenskap", prompt: "Vilken metall har den kemiska beteckningen Fe?", answer: "Järn" },
  { id: "science-8", category: "Vetenskap", prompt: "Vilken planet kallas den röda planeten?", answer: "Mars" },
  { id: "science-9", category: "Vetenskap", prompt: "Vad heter den minsta enheten i ett grundämne som fortfarande behåller ämnets egenskaper?", answer: "Atom" },
  { id: "science-10", category: "Vetenskap", prompt: "Vilken forskare formulerade rörelselagarna och gravitationslagen?", answer: "Isaac Newton" },
  { id: "science-11", category: "Vetenskap", prompt: "Vad heter processen när en vätska övergår till gas vid sin yta?", answer: "Avdunstning" },
  { id: "science-12", category: "Vetenskap", prompt: "Vilken del av cellen innehåller vanligtvis arvsmassan i eukaryota organismer?", answer: "Cellkärnan" },
  { id: "science-13", category: "Vetenskap", prompt: "Vad står DNA för?", answer: "Deoxiribonukleinsyra" },
  { id: "science-14", category: "Vetenskap", prompt: "Vilken partikel har negativ elektrisk laddning?", answer: "Elektron" },
  { id: "science-15", category: "Vetenskap", prompt: "Vad heter måttenheten för elektrisk resistans?", answer: "Ohm" },
  { id: "science-16", category: "Vetenskap", prompt: "Vilket grundämne har atomnummer 79?", answer: "Guld" },
  { id: "science-17", category: "Vetenskap", prompt: "Vad kallas teorin om universums uppkomst genom en snabb expansion från ett extremt tätt tillstånd?", answer: "Big Bang" },
  { id: "science-18", category: "Vetenskap", prompt: "Vilken organell kallas ofta cellens kraftverk?", answer: "Mitokondrie" },
  { id: "science-19", category: "Vetenskap", prompt: "Vad heter skalan som används för att mäta hårdheten hos mineral?", answer: "Mohs skala" },
  { id: "science-20", category: "Vetenskap", prompt: "Vilken forskare är mest förknippad med relativitetsteorin?", answer: "Albert Einstein" },
  { id: "science-21", category: "Vetenskap", prompt: "Vilket grundämne är vanligast i jordskorpan?", answer: "Syre" },
  { id: "science-22", category: "Vetenskap", prompt: "Vad heter den process där växter tar upp koldioxid och avger syre?", answer: "Fotosyntes" },
  { id: "science-23", category: "Vetenskap", prompt: "Vilket blodkärl leder blod från hjärtat ut i kroppen?", answer: "Artär" },
  { id: "science-24", category: "Vetenskap", prompt: "Vad heter den vetenskapliga ordningen av organismer: art, släkte, familj och så vidare?", answer: "Taxonomi" },
  { id: "science-25", category: "Vetenskap", prompt: "Vilken planet har de mest framträdande ringarna i solsystemet?", answer: "Saturnus" },
  { id: "science-26", category: "Vetenskap", prompt: "Vad kallas övergången från fast form direkt till gas?", answer: "Sublimering" },
  { id: "science-27", category: "Vetenskap", prompt: "Vilken del av örat ansvarar bland annat för balanssinnet?", answer: "Innerörat" },
  { id: "science-28", category: "Vetenskap", prompt: "Vilket ämne har den kemiska symbolen Na?", answer: "Natrium" },
  { id: "science-29", category: "Vetenskap", prompt: "Vad kallas ett djur som reglerar kroppstemperaturen med hjälp av omgivningen?", answer: "Växelvarmt djur" },
  { id: "science-30", category: "Vetenskap", prompt: "Vilken fysikalisk storhet mäts i newton?", answer: "Kraft" },
  { id: "science-31", category: "Vetenskap", prompt: "Vad heter galaxen som vårt solsystem befinner sig i?", answer: "Vintergatan" },
  { id: "science-32", category: "Vetenskap", prompt: "Vilket vitamin bildas i huden vid exponering för solljus?", answer: "D-vitamin" },
  { id: "science-33", category: "Vetenskap", prompt: "Vad heter den geologiska tidsperiod då dinosaurierna dominerade?", answer: "Mesozoikum" },
  { id: "science-34", category: "Vetenskap", prompt: "Vilken gas är vanligast i jordens atmosfär?", answer: "Kväve" },
  { id: "science-35", category: "Vetenskap", prompt: "Vilken svensk vetenskapsman skapade temperaturskalan med samma namn?", answer: "Anders Celsius" },
  { id: "science-36", category: "Vetenskap", prompt: "Vad kallas den process där två atomkärnor slås samman?", answer: "Kärnfusion" },
  { id: "science-37", category: "Vetenskap", prompt: "Vilken del av hjärnan förknippas starkt med koordination och balans?", answer: "Lillhjärnan" },
  { id: "science-38", category: "Vetenskap", prompt: "Vad heter världens hårdaste naturliga material?", answer: "Diamant" },
  { id: "science-39", category: "Vetenskap", prompt: "Vilket instrument används för att se mycket små strukturer, till exempel celler?", answer: "Mikroskop" },
  { id: "science-40", category: "Vetenskap", prompt: "Vad kallas den bana jorden rör sig i runt solen?", answer: "Omloppsbana" },
  { id: "science-41", category: "Vetenskap", prompt: "Vilken planet är störst i vårt solsystem?", answer: "Jupiter" },
  { id: "science-42", category: "Vetenskap", prompt: "Vad heter den molekyl som lagrar energi kortsiktigt i kroppens celler?", answer: "ATP" },
  { id: "science-43", category: "Vetenskap", prompt: "Vilken gren av fysiken behandlar ljus?", answer: "Optik" },
  { id: "science-44", category: "Vetenskap", prompt: "Vad kallas den punkt där ett ämne inte längre kan skiljas mellan vätska och gas?", answer: "Kritisk punkt" },
  { id: "science-45", category: "Vetenskap", prompt: "Vilken naturvetenskap studerar jordens bergarter, inre och processer?", answer: "Geologi" },
  { id: "science-46", category: "Vetenskap", prompt: "Vad heter den minsta benämnda enheten i genetisk information?", answer: "Gen" },
  { id: "science-47", category: "Vetenskap", prompt: "Vilken fysiker upptäckte penicillin av en slump?", answer: "Alexander Fleming" },
  { id: "science-48", category: "Vetenskap", prompt: "Vilket djur användes av Darwin som viktigt exempel under studierna på Galápagos?", answer: "Finkar" },
  { id: "science-49", category: "Vetenskap", prompt: "Vad kallas vetenskapen om väder och atmosfär?", answer: "Meteorologi" },
  { id: "science-50", category: "Vetenskap", prompt: "Vilken partikel i atomkärnan saknar elektrisk laddning?", answer: "Neutron" },

  { id: "music-1", category: "Musik", prompt: "Vilken svensk grupp sjöng 'Dancing Queen'?", answer: "ABBA" },
  { id: "music-2", category: "Musik", prompt: "Hur många strängar har en vanlig gitarr oftast?", answer: "6" },
  { id: "music-3", category: "Musik", prompt: "Vilken artist är känd för låten 'Shake It Off'?", answer: "Taylor Swift" },
  { id: "music-4", category: "Musik", prompt: "Vad kallas personen som leder en orkester?", answer: "Dirigent" },
  { id: "music-5", category: "Musik", prompt: "Vilket instrument har svarta och vita tangenter?", answer: "Piano" },
  { id: "music-6", category: "Musik", prompt: "Vilken artist kallas ofta The King of Pop?", answer: "Michael Jackson" },
  { id: "music-7", category: "Musik", prompt: "Vad heter tävlingen där länder tävlar med egna låtar i Europa?", answer: "Eurovision Song Contest" },
  { id: "music-8", category: "Musik", prompt: "Vilken artist sjunger 'Hello' och 'Someone Like You'?", answer: "Adele" },
  { id: "music-9", category: "Musik", prompt: "Vilken kompositör skrev de fyra årstiderna?", answer: "Antonio Vivaldi" },
  { id: "music-10", category: "Musik", prompt: "Vilken artist var frontfigur i Queen?", answer: "Freddie Mercury" },
  { id: "music-11", category: "Musik", prompt: "Vad kallas tempobeteckningen som betyder långsamt på italienska?", answer: "Adagio" },
  { id: "music-12", category: "Musik", prompt: "Vilket instrument spelar Yo-Yo Ma?", answer: "Cello" },
  { id: "music-13", category: "Musik", prompt: "Vilken tonsättare blev döv senare i livet men fortsatte komponera?", answer: "Ludwig van Beethoven" },
  { id: "music-14", category: "Musik", prompt: "Vad heter bandet som gav ut albumet The Dark Side of the Moon?", answer: "Pink Floyd" },
  { id: "music-15", category: "Musik", prompt: "Vilken svensk producent har arbetat med artister som Britney Spears, Backstreet Boys och Taylor Swift?", answer: "Max Martin" },
  { id: "music-16", category: "Musik", prompt: "Vilken jazzmusiker är känd för albumet Kind of Blue?", answer: "Miles Davis" },
  { id: "music-17", category: "Musik", prompt: "Vilken artist släppte albumet Lemonade 2016?", answer: "Beyoncé" },
  { id: "music-18", category: "Musik", prompt: "Vad kallas en grupp om fyra musiker eller sångare?", answer: "Kvartett" },
  { id: "music-19", category: "Musik", prompt: "Vilken opera av Mozart handlar om en förförare från Sevilla?", answer: "Don Giovanni" },
  { id: "music-20", category: "Musik", prompt: "Vilken musikgenre förknippas med artister som Avicii, Swedish House Mafia och Alesso?", answer: "EDM" },
  { id: "music-21", category: "Musik", prompt: "Vilket instrument spelade Jimi Hendrix framför allt?", answer: "Gitarr" },
  { id: "music-22", category: "Musik", prompt: "Vad heter musikfestivalen i Kalifornien som ofta nämns tillsammans med stora internationella artister?", answer: "Coachella" },
  { id: "music-23", category: "Musik", prompt: "Vilken artist låg bakom albumet 21?", answer: "Adele" },
  { id: "music-24", category: "Musik", prompt: "Vad kallas den kvinnliga sångrösten mellan mezzosopran och alt i körsammanhang?", answer: "Alt" },
  { id: "music-25", category: "Musik", prompt: "Vilket band gav ut låten Bohemian Rhapsody?", answer: "Queen" },
  { id: "music-26", category: "Musik", prompt: "Vad heter den svenska tävling som utser Sveriges bidrag till Eurovision?", answer: "Melodifestivalen" },
  { id: "music-27", category: "Musik", prompt: "Vilken artist kallades The Material Girl?", answer: "Madonna" },
  { id: "music-28", category: "Musik", prompt: "Vilken genre förknippas med artister som Louis Armstrong och Ella Fitzgerald?", answer: "Jazz" },
  { id: "music-29", category: "Musik", prompt: "Vad heter symbolen som höjer en ton ett halvt tonsteg?", answer: "Korsförtecken" },
  { id: "music-30", category: "Musik", prompt: "Vilket band hade medlemmarna John Lennon, Paul McCartney, George Harrison och Ringo Starr?", answer: "The Beatles" },
  { id: "music-31", category: "Musik", prompt: "Vilken svensk artist slog igenom internationellt med låten Habits?", answer: "Tove Lo" },
  { id: "music-32", category: "Musik", prompt: "Vad heter den låga manliga sångrösten under baryton?", answer: "Bas" },
  { id: "music-33", category: "Musik", prompt: "Vilken amerikansk artist kallades ofta The Boss?", answer: "Bruce Springsteen" },
  { id: "music-34", category: "Musik", prompt: "Vilket instrument är känt för att ha 88 tangenter?", answer: "Piano" },
  { id: "music-35", category: "Musik", prompt: "Vad heter den klassiska musikperiod som kom efter barocken och före romantiken?", answer: "Wienklassicismen" },
  { id: "music-36", category: "Musik", prompt: "Vilken artist släppte albumet Thriller?", answer: "Michael Jackson" },
  { id: "music-37", category: "Musik", prompt: "Vad kallas en ensam sång- eller instrumentalinsats i ett större verk?", answer: "Solo" },
  { id: "music-38", category: "Musik", prompt: "Vilken svensk artist vann Eurovision 2012 med låten Euphoria?", answer: "Loreen" },
  { id: "music-39", category: "Musik", prompt: "Vilket instrument har ventiler och förknippas starkt med jazz och blåsorkestrar?", answer: "Trumpet" },
  { id: "music-40", category: "Musik", prompt: "Vilket band gav ut albumet Nevermind?", answer: "Nirvana" },
  { id: "music-41", category: "Musik", prompt: "Vad heter den italienska termen för att spela mycket starkt?", answer: "Fortissimo" },
  { id: "music-42", category: "Musik", prompt: "Vilken artist är känd som Rocket Man efter sin låt med samma namn?", answer: "Elton John" },
  { id: "music-43", category: "Musik", prompt: "Vilken musikgenre växte fram i Jamaica och förknippas med Bob Marley?", answer: "Reggae" },
  { id: "music-44", category: "Musik", prompt: "Vad heter notsystemets fem horisontella linjer tillsammans?", answer: "Notlinjer" },
  { id: "music-45", category: "Musik", prompt: "Vilken tonsättare skrev operan Carmen?", answer: "Georges Bizet" },
  { id: "music-46", category: "Musik", prompt: "Vilken artist låg bakom albumet Back to Black?", answer: "Amy Winehouse" },
  { id: "music-47", category: "Musik", prompt: "Vad heter den svenska popduon bakom låten It Takes a Fool to Remain Sane?", answer: "The Ark" },
  { id: "music-48", category: "Musik", prompt: "Vilken artist hade hiten Rolling in the Deep?", answer: "Adele" },
  { id: "music-49", category: "Musik", prompt: "Vilken del av ett trumset slås ofta med fotpedal och står längst ner?", answer: "Bastrumma" },
  { id: "music-50", category: "Musik", prompt: "Vad kallas ett verk för en ensam solist och orkester?", answer: "Konsert" },

  { id: "nature-1", category: "Natur", prompt: "Vad kallas ett träd som tappar sina blad på hösten?", answer: "Lövträd" },
  { id: "nature-2", category: "Natur", prompt: "Vilket är jordens största djur?", answer: "Blå valen" },
  { id: "nature-3", category: "Natur", prompt: "Vad heter den process där växter gör syre av solljus?", answer: "Fotosyntes" },
  { id: "nature-4", category: "Natur", prompt: "Vilket djur är känt som djungelns konung?", answer: "Lejon" },
  { id: "nature-5", category: "Natur", prompt: "Vad heter en grupp vargar tillsammans?", answer: "Flock" },
  { id: "nature-6", category: "Natur", prompt: "Vilken årstid kommer efter sommaren?", answer: "Höst" },
  { id: "nature-7", category: "Natur", prompt: "Vilket djur bygger dammar av träd och grenar?", answer: "Bäver" },
  { id: "nature-8", category: "Natur", prompt: "Vad heter vatten i frusen form?", answer: "Is" },
  { id: "nature-9", category: "Natur", prompt: "Vilken del av blomman utvecklas till frukt efter befruktning?", answer: "Fruktämnet" },
  { id: "nature-10", category: "Natur", prompt: "Vad kallas läran om svampar?", answer: "Mykologi" },
  { id: "nature-11", category: "Natur", prompt: "Vilket däggdjur kan flyga aktivt utan att bara glidflyga?", answer: "Fladdermus" },
  { id: "nature-12", category: "Natur", prompt: "Vad heter den geologiska process där jordskorpans plattor rör sig?", answer: "Plattektonik" },
  { id: "nature-13", category: "Natur", prompt: "Vilken typ av moln förknippas ofta med åskväder?", answer: "Cumulonimbus" },
  { id: "nature-14", category: "Natur", prompt: "Vilket träslag kommer kork från?", answer: "Korkek" },
  { id: "nature-15", category: "Natur", prompt: "Vad heter världens största regnskog?", answer: "Amazonas regnskog" },
  { id: "nature-16", category: "Natur", prompt: "Vilket ämne i barrträd ger den typiska doften och kan användas för att göra terpentin?", answer: "Kåda" },
  { id: "nature-17", category: "Natur", prompt: "Vad kallas en djurart som bara finns naturligt inom ett begränsat område?", answer: "Endemisk art" },
  { id: "nature-18", category: "Natur", prompt: "Vilket väderfenomen mäts med Richterskalan eller momentmagnitudskalan?", answer: "Jordbävning" },
  { id: "nature-19", category: "Natur", prompt: "Vilken fågel är Sveriges nationalfågel?", answer: "Koltrast" },
  { id: "nature-20", category: "Natur", prompt: "Vad kallas den zon i havet där solljuset fortfarande når ner tillräckligt för fotosyntes?", answer: "Den fotiska zonen" },
  { id: "nature-21", category: "Natur", prompt: "Vad heter den största kattarten i världen?", answer: "Tiger" },
  { id: "nature-22", category: "Natur", prompt: "Vilket djur är känt för att kunna byta färg snabbt för kamouflage?", answer: "Kameleont" },
  { id: "nature-23", category: "Natur", prompt: "Vad kallas övergången från larv till vuxen insekt i flera steg?", answer: "Metamorfos" },
  { id: "nature-24", category: "Natur", prompt: "Vilken typ av skog dominerar stora delar av norra Sverige och Finland?", answer: "Barrskog" },
  { id: "nature-25", category: "Natur", prompt: "Vad heter den största björnarten på land?", answer: "Isbjörn" },
  { id: "nature-26", category: "Natur", prompt: "Vilken stenart bildas när lava svalnar snabbt ovan jord?", answer: "Vulkanisk bergart" },
  { id: "nature-27", category: "Natur", prompt: "Vad kallas en grupp fiskar som simmar tillsammans?", answer: "Stim" },
  { id: "nature-28", category: "Natur", prompt: "Vilket grundämne är viktigast för växters klorofyll och ger bladen deras gröna färg indirekt genom molekylen?", answer: "Magnesium" },
  { id: "nature-29", category: "Natur", prompt: "Vilken typ av nederbörd bildas av iskristaller i moln och faller som flingor?", answer: "Snö" },
  { id: "nature-30", category: "Natur", prompt: "Vad heter den period varje år då renar och många andra hjortdjur parar sig?", answer: "Brunst" },
  { id: "nature-31", category: "Natur", prompt: "Vilket djur förknippas med nässeldjur och har tentakler som kan brännas?", answer: "Manet" },
  { id: "nature-32", category: "Natur", prompt: "Vad kallas ett område där sötvatten möter saltvatten, till exempel vid flodmynningar?", answer: "Estuarium" },
  { id: "nature-33", category: "Natur", prompt: "Vilket djur är världens snabbaste på land?", answer: "Gepard" },
  { id: "nature-34", category: "Natur", prompt: "Vad heter det tunna lagret av gaser som omger jorden?", answer: "Atmosfären" },
  { id: "nature-35", category: "Natur", prompt: "Vilken typ av djur är en axolotl?", answer: "Salamander" },
  { id: "nature-36", category: "Natur", prompt: "Vad kallas de enorma vågor som kan uppstå efter jordbävningar under havsytan?", answer: "Tsunami" },
  { id: "nature-37", category: "Natur", prompt: "Vilken fågel är känd för att kunna stå stilla i luften medan den spanar efter byte?", answer: "Tornfalk" },
  { id: "nature-38", category: "Natur", prompt: "Vad heter den biologiska relation där båda arterna gynnas?", answer: "Mutualism" },
  { id: "nature-39", category: "Natur", prompt: "Vilken typ av djur är blåvalen trots sitt namn?", answer: "Däggdjur" },
  { id: "nature-40", category: "Natur", prompt: "Vad kallas området i ett träd där årsringarna bildas och transport sker?", answer: "Kambium" },
  { id: "nature-41", category: "Natur", prompt: "Vilken naturtyp kännetecknas av permanent frusen mark som kallas permafrost?", answer: "Tundra" },
  { id: "nature-42", category: "Natur", prompt: "Vad heter den punkt då vattenånga övergår till flytande vatten i luften och dagg kan bildas?", answer: "Daggpunkt" },
  { id: "nature-43", category: "Natur", prompt: "Vilket djur kallas ibland havets ingenjör eftersom det bygger stora dammar och förändrar landskapet?", answer: "Bäver" },
  { id: "nature-44", category: "Natur", prompt: "Vad kallas den hårda yttre delen hos många insekter och kräftdjur?", answer: "Exoskelett" },
  { id: "nature-45", category: "Natur", prompt: "Vilken stor katt är bäst anpassad till kyla och höga berg i Centralasien?", answer: "Snöleopard" },
  { id: "nature-46", category: "Natur", prompt: "Vad heter den process då bergarter bryts ner av vind, vatten och temperaturväxlingar?", answer: "Vittring" },
  { id: "nature-47", category: "Natur", prompt: "Vilken typ av växtlighet dominerar i en savann?", answer: "Gräs" },
  { id: "nature-48", category: "Natur", prompt: "Vad heter de glödande partiklar som ses på himlen när solvinden träffar jordens magnetfält?", answer: "Norrsken" },
  { id: "nature-49", category: "Natur", prompt: "Vilket havsdjur har tre hjärtan och blått blod?", answer: "Bläckfisk" },
  { id: "nature-50", category: "Natur", prompt: "Vad kallas det när en art dör ut helt från jorden?", answer: "Utdöende" },
];

export function buildTriviaDeck(selectedCategories: TriviaCategory[], questionsPerPlayer: number, playerCount: number) {
  const allowed = TRIVIA_QUESTIONS.filter((question) => selectedCategories.includes(question.category));
  const targetCount = questionsPerPlayer * playerCount;

  if (allowed.length === 0) {
    return [];
  }

  const deck: TriviaQuestion[] = [];

  while (deck.length < targetCount) {
    const source = shuffleQuestions(allowed);
    for (const question of source) {
      if (deck.length >= targetCount) {
        break;
      }
      deck.push(question);
    }
  }

  return deck;
}

function shuffleQuestions(input: TriviaQuestion[]) {
  const copy = [...input];
  for (let index = copy.length - 1; index > 0; index -= 1) {
    const swapIndex = Math.floor(Math.random() * (index + 1));
    [copy[index], copy[swapIndex]] = [copy[swapIndex], copy[index]];
  }
  return copy;
}
